// src/components/userflow/Shared/sharedStyles.tsx
import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import planWaterBg from "../../../assets/cultures/plan_water.png";
import { COLORS, SHADOWS, TYPOGRAPHY, FONTS, baseStyles } from "./styles";

const useSharedStyles = makeStyles()((theme: Theme) => ({
  loadingLayout: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%", 
    height: "100vh",
    backgroundColor: "#FFFFFFE5",
  },
  loadingLogo: {
    width: "250px",
  },
  layout: {
    minHeight: "100vh",
    width: "100%",
    overflowX: "hidden",
    overflowY: "visible",
  },
  mobileContactBar: {
    position: "fixed",
    left: theme.spacing(2),
    bottom: theme.spacing(2),
    display: "none",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(0),
    background: "transparent",
    boxShadow: "none",
    zIndex: 999,
    [theme.breakpoints.down("md")]: {
      display: "flex",
    },
  },
  mobileContactButton: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    border: "none",
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
  },
  mobileContactBackdropPad: {
    height: 0,
    display: "none",
  },
  contactBoxModalContainer: {
    width: "90%",
    position: "absolute",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    maxWidth: "300px",
    display: "flex",
    justifyContent: "center",
  },
  contactBoxFloating: {
    position: "fixed",
    left: theme.spacing(2),
    bottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(0.5),
    zIndex: 90,
  },
  contactBoxButton: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    cursor: "pointer",
    zIndex: 5,
    "& img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
  },
  footerRoot: {
    width: "100%",
    minHeight: 530,
    position: "relative",
    paddingTop: 0,
    paddingBottom: 0,
    overflow: "hidden",
    marginTop: 50,
    [theme.breakpoints.down("lg")]: {
      minHeight: 650,
    },
  },
  footerBg: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "100%",
    height: "400px",
    objectFit: "cover",
    objectPosition: "top",
    zIndex: 1,
    [theme.breakpoints.down("lg")]: {
      height: "560px",
    },
    [theme.breakpoints.down("md")]: {
      height: "580px",
    },
  },
  footerBg1: {
    position: "absolute",
    top: 40,
    left: 0,
    width: "120%",
    objectFit: "cover",
    objectPosition: "top",
    zIndex: 0,
    [theme.breakpoints.down("md")]: {
      width:"140%",
    },
  },
  footerBg2: {
    position: "absolute",
    top: "40px",
    left: "-100px",
    width: "120%",
    // height: "430px",
    objectFit: "cover",
    objectPosition: "top",
    zIndex: 0,
  },
  footerBg3: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "120%",
    objectFit: "cover",
    objectPosition: "top",
    zIndex: 0,
  },
  footerContent: {
    position: "relative",
    zIndex: 1,
    marginTop: "100px",
    paddingLeft: theme.spacing(8),
    paddingRight: theme.spacing(8),
    paddingTop: theme.spacing(8),
    paddingBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    [theme.breakpoints.down("md")]: {
      paddingBottom: 50,
      marginTop: "50px",
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
    },
  },
  footerLogoBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginBottom: 0,
    [theme.breakpoints.down("md")]: {
      justifyContent: "flex-start",
      marginBottom: theme.spacing(2),
    },
  },
  footerLogo: {
    width: 180,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      width: 80,
      marginTop: 20,
    },
  },
  subscribeBox: {
    width: "100%",
    maxWidth: 350,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacing(4),
    marginTop: theme.spacing(2),
    gap: 0,
    justifyContent: "center",
    position: "relative",
    //[theme.breakpoints.down("md")]: {
    //  flexDirection: "column",
    //  gap: theme.spacing(2),
    //  },
  },
  subscribeInput: {
    flex: 1,
    borderRadius: 999,
    background: COLORS.WHITE,
    border: `1px solid transparent`,
    paddingLeft: theme.spacing(2),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    ...TYPOGRAPHY.subtitle1(theme),
    boxShadow: SHADOWS.DARK_CARD,
    height: 42,
    paddingRight: 0,
    width: "auto",
    minWidth: 0,
    marginBottom: 0,
    //[theme.breakpoints.down("md")]: {
      //...TYPOGRAPHY.body1(theme),
     // height: "24px",
     // fontSize: "12px",
      //width: "auto",
     // borderRadius: 10,
      //marginTop: 30,
      //marginBottom: 10,
      //padding: "1.5px 0px 1.5px 10px",
        
   // },
  },
  subscribeInputError: {
    border: `1px solid #d32f2f`,
  },
  subscribeButton: {
    ...baseStyles.button(theme),
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    marginRight: theme.spacing(2),
    height: 28,
    letterSpacing: 0.5,
    minWidth: 0,
    "&:hover": { background: COLORS.HERO_BLUE },
    //[theme.breakpoints.down("md")]: {
      //...TYPOGRAPHY.body1(theme),
      //...baseStyles.button(theme),
      //background: COLORS.SECONDARY_BLUE,
      //color: COLORS.WHITE,
     // marginRight: theme.spacing(1),
      //height: 28,
      //letterSpacing: 0.5,
      //width:100
    //},
  },
  topInBig: {
    marginTop: "90px",
    [theme.breakpoints.down("lg")]: {
      marginTop: 0,
    },
  },
  linksFlex: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
  },
  navLinks1: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
  },
  navLink: {
    color: COLORS.WHITE,
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
    cursor: "pointer",
    textDecoration: "none",
  },
  navLinks2: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
  },
  navLinkBold: {
    color: COLORS.WHITE,
    ...TYPOGRAPHY.subtitle1(theme),
    fontWeight: 500,
    marginBottom: 4,
    cursor: "pointer",
    textDecoration: "none",
  },
  contactBox: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    alignItems: "flex-start",
    minWidth: 160,
    marginTop: 0,
    [theme.breakpoints.down("lg")]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  contactTitle: {
    ...TYPOGRAPHY.subtitle1(theme),
    color: COLORS.WHITE,
    marginBottom: 8,
    textAlign: "center",
  },
  contactRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: COLORS.WHITE,
    marginBottom: 4,
  },
  footerContactLink: {
    color: COLORS.WHITE,
    textDecoration: "none",
    '&:hover': { color: COLORS.WHITE, textDecoration: "none" },
    '&:visited': { color: COLORS.WHITE, textDecoration: "none" },
    '&:active': { color: COLORS.WHITE, textDecoration: "none" },
  },
  contactText: {
    ...TYPOGRAPHY.body2(theme),
    color: COLORS.WHITE,
  },
  socialIcons: {
    display: "flex",
    gap: 16,
    marginTop: 16,
    justifyContent: "center",
  },
  mapBox: {
    minWidth: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    [theme.breakpoints.down("lg")]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  mapImg: {
    width: 220,
    height: 160,
    borderRadius: 3,
    objectFit: "cover",
    [theme.breakpoints.down("lg")]: {
      width: 180,
      height: 140,
    },
  },
  copyright: {
    width: "100%",
    borderTop: `1px solid ${COLORS.LIGHT_GRAY}`,
    paddingTop: theme.spacing(2),
    paddingBottom: theme.spacing(2),
    marginTop: 0,
    textAlign: "center",
    color: COLORS.WHITE,
    ...TYPOGRAPHY.body1(theme),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    position: "absolute",
    left: 0,
    bottom: 0,
    background: "transparent",
    fontFamily: FONTS.INTER,
    fontWeight: 500,
  },
  footerLogoBoxMobile: {
    display: "flex",
    justifyContent: "flex-start",
    marginBottom: 16,
    [theme.breakpoints.up("lg")]: {
      display: "none",
      marginBottom: 0,
    },
  },
  navLinksBoxMobile: {
    width: "50%",
    marginBottom: 20,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-start",
    paddingLeft: 8,
  },
  navLinksBoxMobile2: {
    alignItems: "flex-end",
  },
  navLinksBoxDesktop: {
    gap: 12,
  },
  contactBoxMobile: {
    width: "50%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-start",
    paddingLeft: 8,
    marginTop: 16,
  },
  contactBoxDesktop: {
    minWidth: 160,
    gap: 8,
  },
  flexRoot: {
    width: "100%",
    display: "flex",
    flexWrap: "wrap",
    
  },
  flexSide: {
    display: "flex",
    width: "100%",
    gap: "20px",
  },
  mapBoxMobile: {
    width: "50%",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-start",
    minWidth: 0,
    marginTop: 16,
  },
  mapBoxDesktop: {
    minWidth: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  logoBoxDesktop: {
    minWidth: 120,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    [theme.breakpoints.down("lg")]: {
      display: "none",
    },
  },
  footerLogoDesktop: {
    width: 180,
    marginBottom: 16,
  },
  footerDesktopRow: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 16,
    gap: 32,
    marginBottom: 16,
  },
  navLinkMobile: {
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
  },
  cursorPointer: {
    cursor: "pointer",
  },
  headerContactLink: {
    textDecoration: "none",
    color: "inherit",
    cursor: "pointer",
  },
  headerContactText: {
    textDecoration: "none",
  },
  navLinkBoldMobile: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontWeight: 500,
    marginBottom: 4,
  },
  navLinkDesktop: {
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
  },
  navLinkBoldDesktop: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 16,
    fontWeight: 500,
    marginBottom: 4,
  },
  contactRowInline: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  contactTitleMobile: {
    ...TYPOGRAPHY.subtitle1(theme),
    marginBottom: 8,
  },
  contactTitleDesktop: {
    ...TYPOGRAPHY.subtitle1(theme),
    color: COLORS.WHITE,
    marginBottom: 8,
    textAlign: "center",
  },
  contactTextMobile: {
    ...TYPOGRAPHY.body2(theme),
  },
  contactTextDesktop: {
    ...TYPOGRAPHY.body2(theme),
  },
  socialIconsMobile: {
    display: "flex",
    gap: 16,
    marginTop: 16,
  },
  socialIconsDesktop: {
    display: "flex",
    gap: 12,
    marginTop: 16,
    justifyContent: "center",
  },
  mapImgMobile: {
    width: 40,
    height: 90,
    borderRadius: "20px",
    [theme.breakpoints.up("lg")]: {
      width: 150,
      height: 150,
    },
  },
  mapImgDesktop: {
    marginTop: "20px",
    width: 320,
    height: 230,
    borderRadius: 20,
  },
  copyrightMobile: {
    ...TYPOGRAPHY.body2(theme),
    zIndex: "10",
  },
  copyrightDesktop: {
    ...TYPOGRAPHY.body1(theme),
    fontSize: 14,
    zIndex: "10",
  },
  copyrightIcon: {
    width: 18,
    height: 18,
    margin: "0 0 0 1px",
    [theme.breakpoints.down("lg")]: {
      width: 14,
      height: 14,
    },
  },
  appBar: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    zIndex: 200,
    transition: "background 0.3s, color 0.3s, box-shadow 0.3s",
  },
  appBarTrigger: {
    background: COLORS.WHITE,
    color: theme.palette.primary.main,
    boxShadow: SHADOWS.SUBTLE,
  },
  appBarNoTrigger: {
    background: "transparent",
    color: COLORS.WHITE,
    boxShadow: "none",
  },
  mobileTopBar: {
    width: "100vw",
    maxWidth: "100vw",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-evenly",
    background: COLORS.WHITE,
    color: theme.palette.primary.main,
    paddingLeft: 0,
    paddingRight: 0,
    minHeight: 36,
    borderBottom: `1px solid ${COLORS.BBB}`,
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1301,
    ...TYPOGRAPHY.body2(theme),
  },
  mobileContact: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontWeight: 500,
    fontSize: 10,
  },
  mobileFont: {
    ...TYPOGRAPHY.body2(theme),
  },
  mobileDivider: {
    width: 1,
    height: 16,
    background: theme.palette.primary.main,
  },
  mobileSidebarBtn: {
    background: COLORS.SECONDARY_BLUE,
    color: theme.palette.primary.main,
    borderRadius: "50%",
    width: 35,
    height: 35,
    boxShadow: SHADOWS.SUBTLE,
    margin: "0px 15px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      background: COLORS.SECONDARY_BLUE,
    },
  },
  mobileSidebarIcon: {
    width: 18,
    height: 18,
    display: "block",
    color: "white",
  },
  mobileHeaderBar: {
    width: "100vw",
    maxWidth: "100vw",
    display: "flex",
    alignItems: "center",
    justifyItems: "justify-between",
    background: "white",
    padding: "5px",
    minHeight: 44,
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1301,
  },
  logo_mb: {
    paddingRight: "10px",
  },
  mobileFlex: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  desktopTopBar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    width: "100%",
    transition: "background 0.3s, color 0.3s, border-bottom 0.3s",
  },
  desktopTopBarTrigger: {
    background: COLORS.WHITE,
    color: theme.palette.primary.main,
  },
  desktopTopBarNoTrigger: {
    background: "transparent",
    color: COLORS.WHITE,
  },
  desktopContact: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "nowrap",
    width: "auto",
  },
  desktopDivider: {
    width: 1,
    height: 20,
    background: theme.palette.primary.main,
  },
  desktopDividerNoTrigger: {
    background: COLORS.LIGHT_BLUE,
  },
  desktopSearchPaper: {
    padding: "3px 6px",
    display: "flex",
    alignItems: "center",
    width: 300,
    borderRadius: 999,
    marginRight: theme.spacing(1),
    border: `1.5px solid ${COLORS.WHITE}`,
    boxShadow: "none",
    background: "transparent",
    transition: "background 0.3s, border 0.3s",
  },
  searchSuggestWrapper: {
    position: "relative",
    width: 300,
    display: "flex",
    justifyContent: "flex-end",
  },
  // When suggestions are open, flatten the Paper bottom so it merges with the dropdown
  searchSuggestOpenPaper: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    position: "relative",
    zIndex: 3001,
  },
  searchSuggestBox: {
    position: "absolute",
    right: 0,
    top: 43,
    zIndex: 3000,
    background: COLORS.WHITE,
    color: COLORS.DARK,
    borderRadius: "8px",
    boxShadow: SHADOWS.MEDIUM,
    width: "100%",
    maxHeight: 300,
    overflowY: "auto",
    border: `1px solid ${COLORS.LGRAY}`,
    borderTop: "none",
  },
  searchSuggestItem: {
    padding: "6px 10px",
    cursor: "pointer",
    fontFamily: FONTS.INTER,
    fontSize: 12,
    lineHeight: 1.4,
    "&:hover": {
      textDecoration: "none",
    },
  },
  searchSuggestActive: {
    fontWeight: 600,
    textDecoration: "none",
  },
  searchSuggestText: {
    color: "inherit",
    textDecoration: "none",
    fontFamily: FONTS.INTER,
    fontSize: 12,
    lineHeight: 1.4,
  },
  desktopSearchPaperTrigger: {
    border: `1.5px solid ${theme.palette.primary.main}`,
  },
  desktopToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1),
    minHeight: 64,
    background: "transparent",
  },
  desktopLogo: {
    height: 95,
    width: 95,
    marginRight: theme.spacing(4),
    borderRadius: 2,
  },
  desktopNav: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: theme.spacing(4),
    gap: 24,
    flexWrap: "wrap",
    overflow: "visible",
  },
  desktopNavItem: {
    fontWeight: 500,
    background: "transparent",
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0,
    borderRadius: 0,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  desktopNavItemActiveTrigger: {
    color: COLORS.WHITE,
    background: theme.palette.primary.main,
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: "999px",
    boxShadow: SHADOWS.SUBTLE,
  },
  desktopNavItemInactiveTrigger: {
    color: theme.palette.primary.main,
    background: "transparent",
    fontWeight: 600,
  },
  desktopNavItemActiveNoTrigger: {
    color: theme.palette.primary.main,
    background: COLORS.LIGHTWHITE,
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: "999px",
  },
  desktopNavItemInactiveNoTrigger: {
    color: COLORS.WHITE,
    background: "transparent",
  },
  drawerPaper: {
    width: 320,
    background: "#F5F5F5",
    boxShadow: "none",
    paddingTop: 0,
  },
  drawerBackdrop: {
    background: COLORS.DARK_SHADOW,
  },
  drawerNavItem: {
    fontWeight: 500,
    color: "inherit",
    background: "transparent",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 2,
    cursor: "pointer",
    width: "100%",
    transition: "all 0.2s",
  },
  drawerNavItemActive: {
    fontWeight: 700,
    color: theme.palette.primary.main,
    background: theme.palette.action.selected,
  },
  // New Sidebar Styles
  sidebarContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "#F6F7F9",
  },
  sidebarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: theme.spacing(2),
  },
  sidebarLogoContainer: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
  },
  sidebarLogo: {
    width: 60,
    height: 60,
    borderRadius: "50%",
    background: COLORS.WHITE,
  },
  sidebarCompanyName: {
    fontSize: "12px",
    fontWeight: 600,
    color: theme.palette.primary.main,
    lineHeight: 1.2,
  },
  sidebarCloseButton: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: COLORS.WHITE,
    color: "#F34646",
    boxShadow: SHADOWS.SUBTLE,
    "& svg": {
      width: 20,
      height: 20,
    },
  },
  sidebarSearchContainer: {
    padding: "16px 20px 16px 10px",
    boxShadow: "none",
  },
  sidebarSearchPaper: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    borderRadius: 12,
    border: "1px solid #0463EE",
    background: COLORS.WHITE,
    padding: theme.spacing(1, 0.5),
    boxShadow: "none",
  },
  sidebarSearchIcon: {
    color: theme.palette.primary.main,
    marginLeft: theme.spacing(1),
    marginRight: theme.spacing(2),
  },
  sidebarSearchInput: {
    flex: 1,
    fontSize: "14px",
    color: "#333",
    "&::placeholder": {
      color: "#999",
      opacity: 1,
    },
  },
  sidebarNavContainer: {
    flex: 1,
    padding: theme.spacing(1),
    overflowY: "auto",
    msOverflowStyle: "none",
    background: "transparent",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      width: 0,
      height: 0,
    },
  },
  sidebarNavItemContainer: {
    marginBottom: theme.spacing(2),
  },
  sidebarNavItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: theme.spacing("8px", "10px"),
    borderRadius: 4,
    cursor: "pointer",
    transition: "all 0.2s",
    "&:hover": {
      background: "#E8F4FD",
    },
  },
  sidebarNavItemActive: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: "10px",
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
    },
    "& span": {
      color: COLORS.WHITE,
    },
    "& p": {
      color: COLORS.WHITE,
    },
  },
  sidebarNavItemActiveWithChildren: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: "12px 12px 0 0",
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
    },
    "& span": {
      color: COLORS.WHITE,
    },
    "& p": {
      color: COLORS.WHITE,
    },
  },
  sidebarNavItemText: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#363A44",
  },
  sidebarExpandIcon: {
    fontSize: "20px",
  },
  sidebarSubcategoryList: {
    padding: 0,
    backgroundColor: "#F0F6FB",
    boxShadow: "0 2px 6px 0 #0A4FA429",
    paddingTop: "10px",
  },
  sidebarSubcategoryItem: {
    padding: 0,
    marginBottom: theme.spacing(0.5),
  },
  sidebarSubcategoryText: {
    color: "#666",
    padding: theme.spacing(0.5, 2),
    borderRadius: 4,
    transition: "all 0.2s",
    "&:hover": {
      background: "#E8F4FD",
      color: theme.palette.primary.main,
    },
    "& span": {
      fontSize: "12px",
    },
  },
  sidebarHighlight: {
    background: "#FFF59D",
    color: "inherit",
    padding: "0 2px",
    borderRadius: 2,
  },
  sidebarSubcategoryActive: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 600,
  },
  // Generic link reset classes for sidebar links
  sidebarLinkReset: {
    textDecoration: "none",
  },
  sidebarSubLink: {
    textDecoration: "none",
    width: "100%",
    display: "block",
  },
  desktopSearchIcon: {
    padding: 6,
    color: theme.palette.primary.main,
  },
  desktopSearchInput: {
    marginLeft: 6,
    flex: 1,
    ...TYPOGRAPHY.body2(theme),
    fontSize: "12px",
    color: COLORS.DARK,
    "&::placeholder": {
      color: COLORS.MEDIUM_GRAY,
      opacity: 1,
    },
  },
  footerSocialIconWhite: {
    color: COLORS.WHITE,
    width: 24,
    height: 24,
    objectFit: "contain",
  },
  twitterIconWhite: {
    color: COLORS.WHITE,
    width: 14,
    height: 14,
    objectFit: "contain",
  },
  headerSearchIcon: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 22,
    color: COLORS.WHITE,
  },
  headerSearchIconTrigger: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 22,
    color: theme.palette.primary.main,
  },
  hideInBig: {
    [theme.breakpoints.up("lg")]: {
      display: "none",
    },
  },

  // ContactBox styles
  contactBoxWrapper: {
    width: "100%",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: 12,
    boxShadow: SHADOWS.DARK_CARD,
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    fontSize: 16,
    gap: theme.spacing(1.5),
  },
  contactBoxTitle: {
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 18,
    color: COLORS.SECONDARY_BLUE,
    marginBottom: 4,
  },
  contactBoxLabel: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
    marginBottom: 4,
  },
  contactBoxValue: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
  },
  contactBoxIcon: {
    color: COLORS.SECONDARY_BLUE,
    fontSize: 18,
    width: 17,
  },
  contactBoxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },

  // Testimonials
}));

export const usePlansStyles = makeStyles()((theme: Theme) => ({
  plansRoot: {
    width: "97vw",
    position: "relative",
    left: "50%",
    right: "50%",
    marginLeft: "-49vw",
    marginRight: "-49vw",
    marginTop: "40px",
    marginBottom: "40px",
    backgroundImage: `url(${planWaterBg})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(8),
    paddingLeft: "12px",
    borderRadius: "10px",
    border: "2px solid #57B6FF",
    zIndex: 1,
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1,
    },
    [theme.breakpoints.down("md")]: {
      paddingLeft: 0,
    },
  },
  plansHeader: {
    position: "relative",
    zIndex: 2,
    width: "fit-content",
    margin: "0 auto",
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    padding: theme.spacing(1.5, 4),
    borderRadius: 999,
    boxShadow: SHADOWS.SUBTLE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 24,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
      padding: theme.spacing(1, 3),
    },
  },
  plansHeaderBlue: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: COLORS.SECONDARY_BLUE,
    borderRadius: 999,
    zIndex: -1,
    transform: "scale(1.1)",
  },
  plansContainer: {
    position: "relative",
    zIndex: 2,
    marginTop: theme.spacing(4),
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: 1400,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    "& .MuiGrid-root": {
      marginBottom: "30px",
    },
  },
  plansCard: {
    background: COLORS.WHITE,
    borderRadius: 16,
    boxShadow: SHADOWS.LARGE,
    padding: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1),
    height: "100%",
    minHeight: 400,
    marginBottom: "20px",
    flex: 1,
  },
  plansCardHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(1),
    width: "100%",
  },
  plansBadge: {
    position: "absolute",
    top: -12,
    right: 12,
    background: "#87CEEB",
    color: COLORS.WHITE,
    borderRadius: 999,
    padding: theme.spacing(0.5, 1.5),
    fontSize: 12,
    boxShadow: SHADOWS.SUBTLE,
  },
  plansTitleChip: {
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 999,
    padding: theme.spacing(0.5, 3),
    fontWeight: 600,
    width: "fit-content",
    margin: "0 auto",
  },
  plansPrice: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.WHITE,
    fontSize: 18,
  },
  plansList: {
    marginTop: theme.spacing(1),
    paddingLeft: theme.spacing(2),
    flex: 1,
  },
  plansListItem: {
    marginBottom: theme.spacing(1),
  },
  plansCta: {
    marginTop: "auto",
    alignSelf: "center",
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    textTransform: "none",
    padding: theme.spacing(0.75, 3),
    borderRadius: 999,
    boxShadow: SHADOWS.SUBTLE,
    "&:hover": {
      background: COLORS.HERO_BLUE,
    },
  },

  // New styles moved from sx props
  plansHeaderBanner: {
    width: "fit-content",
    margin: "0 auto",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    padding: "12px 32px",
    marginBottom: "60px",
    marginTop: "-65px",
    borderRadius: 999,
  },
  plansHeaderTitle: {
    fontSize: "24px",
    marginBottom: "20px",
    color: COLORS.SECONDARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    textAlign: "center",
    background: "white",
    padding: "12px 76px",
    borderRadius: 999,
    maxWidth: "fit-content",
    margin: "-80px auto 40px auto",
    boxShadow: "0 2px 10px 0 #0463EE66",
    [theme.breakpoints.down("md")]: {
      padding: "12px 20px",
      fontSize: "14px",
    },
  },
  plansBadgeNew: {
    position: "absolute",
    top: 0,
    left: 0,
    background: "#DBECF9",
    color: "#0A4FA4",
    borderRadius: "20px 0 20px 0",
    padding: "8px 12px",
    fontSize: "14px",
    fontWeight: 600,
    zIndex: 10,
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },
  plansCardHeaderNew: {
    background: COLORS.PRIMARY_BLUE,
    color: "white",
    borderRadius: "16px 16px 0 0",
    padding: "20px",
    margin: "-16px -16px 16px -16px",
    minHeight: "80px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    gap: "15px",
  },
  plansCardTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
    background: COLORS.WHITE,
    padding: "2px 26px",
    borderRadius: "4px",
    maxWidth: "fit-content",
    textAlign: "center",
    width: "100%",
  },
  plansCardPrice: {
    fontSize: "1.2em",
    opacity: 0.9,
    color: "white",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
  },
  plansCardList: {
    marginTop: 2,
    paddingLeft: 3,
    flex: 1,
    listStyle: "none",
  },
  plansCardListItem: {
    marginBottom: 9,
    position: "relative",
    paddingLeft: "20px",
    fontSize: "14px",
    color: COLORS.DARK,
    lineHeight: 1.4,
    fontFamily: FONTS.POPPINS,
    fontWeight: 400,
    "&::before": {
      content: '"•"',
      position: "absolute",
      left: 0,
      color: COLORS.DARK,
      fontWeight: "bold",
    },
  },
  plansCardButton: {
    marginTop: "auto",
    alignSelf: "center",
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    textTransform: "none",
    padding: "5px 25px",
    borderRadius: "999px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    fontWeight: 600,
    "&:hover": {
      background: COLORS.SECONDARY_BLUE,
    },
  },

  // New styles for aquaculture type selection
  plansCardImage: {
    width: "100%",
    height: "200px",
    objectFit: "cover",
    borderRadius: "8px",
    marginBottom: "15px",
  },

  plansCardImageContainer: {
    width: "100%",
    height: "200px",
    overflow: "hidden",
    borderRadius: "16px 16px 0 0",
  },

  plansCardTitleBanner: {
    background: COLORS.PRIMARY_BLUE,
    padding: "12px 16px",
    borderRadius: "0 0 16px 16px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "60px",
  },

  plansCardTitleText: {
    color: COLORS.WHITE,
    fontSize: "14px",
    fontWeight: 600,
    textAlign: "center",
    lineHeight: 1.2,
  },

  plansBackButtonContainer: {
    marginTop: "32px",
    display: "flex",
    justifyContent: "flex-start",
    paddingLeft: "16px",
  },

  plansBackButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: COLORS.PRIMARY_BLUE,
    background: "rgba(255, 255, 255, 0.9)",
    textTransform: "none",
    padding: "8px 16px",
    borderRadius: "8px",
    fontWeight: 500,
    "&:hover": {
      background: "rgba(255, 255, 255, 1)",
    },
  },

  plansBackIcon: {
    color: COLORS.PRIMARY_BLUE,
    background: "rgba(255, 255, 255, 0.9)",
    "&:hover": {
      background: "rgba(255, 255, 255, 1)",
    },
  },
  plansBackText: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 500,
    fontSize: "16px",
  },

  // Step 2 specific styles - Aquaculture Type Selection
  step2Root: {
    width: "97vw",
    position: "relative",
    left: "50%",
    right: "50%",
    marginLeft: "-49vw",
    marginRight: "-49vw",
    marginTop: "40px",
    background: "#DBECF9",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(1),
    paddingLeft: "12px",
    borderRadius: "10px",
    border: "2px solid #57B6FF",
    zIndex: 1,
    [theme.breakpoints.down("md")]: {
      paddingLeft: 0,
    },
  },

  step2Header: {
    width: "fit-content",
    margin: "0 auto",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    padding: "12px 32px",
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    marginBottom: "32px",
    textAlign: "center",
  },

  step2HeaderTitle: {
    fontSize: "1.2em",
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
    textAlign: "center",
    margin: 0,
  },

  step2Container: {
    position: "relative",
    zIndex: 2,
    margin: theme.spacing(4),
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: 1400,
    paddingLeft: theme.spacing(2),
    placeContent: "center",
    paddingRight: theme.spacing(2),
    gap: "20px 0",
    placeItems: "center",
  },

  step2Card: {
    background: COLORS.WHITE,
    borderRadius: 16,
    boxShadow: SHADOWS.LARGE,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 300,
    marginBottom: "20px",
    flex: 1,
    overflow: "hidden",
  },

  step2CardImageContainer: {
    width: "100%",
    height: "270px",
    overflow: "hidden",
    borderRadius: "16px 16px 0 0",
    position: "relative",
  },

  step2CardImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },

  step2CardTitleBanner: {
    background: COLORS.PRIMARY_BLUE,
    padding: "6px 16px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },

  step2CardTitleText: {
    color: COLORS.WHITE,
    fontSize: "14px",
    fontWeight: 600,
    textAlign: "center",
    lineHeight: 1.3,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },

  step2BackButtonContainer: {
    marginBottom: "10px",
    display: "flex",
    justifyContent: "flex-start",
    paddingLeft: "16px",
  },

  step2BackButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: COLORS.PRIMARY_BLUE,
    cursor: "pointer",
    textTransform: "none",
    fontSize: "16px",
    transition: "all 0.2s ease",
    fontFamily: FONTS.INTER,
    fontWeight: 600,
  },

  // Make step 2 cards clickable with hover affordance
  step2CardClickable: {
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    margin: "10px",
  },

  // Step 3 illustration sizing
  step3Illustration: {
    width: "100%",
    height: "auto",
    maxWidth: 360,
    display: "block",
    margin: "0 auto",
  },

  // Step 3 form styles
  step3FormCol: {
    width: "100%",
    maxWidth: 620,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  step3FieldsGrid: {
    width: "100%",
    gap: "6px 16px",
  },
  step3FieldTop: {
    marginTop: -40,
    [theme.breakpoints.down("md")]: {
      marginTop: 0,
    },
  },
  step3Field: {
    marginBottom: 8,
    borderRadius: 8,
    background: "transparent",
    border: "none",
    "& .MuiSelect-select": {
      border: "1px solid #57B6FF",
      background: "white",
      padding: "10px",
      borderRadius: "8px",
    },
    "& .MuiOutlinedInput-root": {
      background: COLORS.WHITE,
      borderRadius: 8,
      border: "1px solid #57B6FF",
      padding: 0,
      "& .MuiOutlinedInput-input": {
        padding: "8px 10px",
      },
    },
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiInputBase-input::placeholder": {
      color: "#333333",
      opacity: 1,
    },
    "& .MuiFormHelperText-root": {
      margin: "0",
      background: "#DBECF9",
    },
  },
  step3Label: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 13,
    marginBottom: 4,
    display: "inline-block",
  },
  step3Asterisk: {
    color: "#f44336",
  },
  step3ButtonWrapper: {
    display: "flex",
    justifyContent: "center",
    marginTop: theme.spacing(3),
  },

  // Step 4 styles
  step4FormField: {
    marginBottom: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
  },

  step4DateField: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    background: COLORS.WHITE,
    borderRadius: 8,
    border: "1px solid #57B6FF",
    padding: "12px 10px",
  },

  step4CalendarIcon: {
    width: 20,
    height: 20,
    marginRight: 25,
    opacity: 0.7,
  },

  step4DateInput: {
    border: "none",
    outline: "none",
    background: "transparent",
    flex: 1,
    fontSize: 14,
    fontFamily: FONTS.INTER,
    color: COLORS.DARK,
    "&::placeholder": {
      color: "#333333",
    },
  },

  // Custom Select styling for Step 4 month dropdowns
  step4Select: {
    flex: 1,
    margin: 0,
    background: "transparent",
    border: "none",
    "& .MuiOutlinedInput-root": {
      background: "transparent",
      borderRadius: 8,
      border: "none",
      padding: 0,
      boxShadow: "none",
      "& .MuiOutlinedInput-input": {
        padding: "0 8px",
        height: 24,
        display: "flex",
        alignItems: "center",
      },
    },
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiSelect-select": {
      padding: 0,
      background: "transparent",
      color: COLORS.DARK,
      fontFamily: FONTS.INTER,
      fontSize: 14,
    },
    "& .MuiSvgIcon-root": {
      color: "#666",
    },
  },

  step4MenuPaper: {
    maxHeight: 260,
    overflowY: "auto",
    boxShadow: SHADOWS.SUBTLE,
    "& .MuiMenuItem-root": {
      fontFamily: FONTS.INTER,
      fontSize: 14,
    },
  },

  step4AvailableGroup: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },

  step4BottomSection: {
    display: "flex",
    flexDirection: "column",
    padding: theme.spacing(0, 0, 2, 0),
  },

  step4Checkbox: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    "& input[type='checkbox']": {
      width: 18,
      height: 18,
      accentColor: COLORS.PRIMARY_BLUE,
      border: "1px solid #0A4FA4",
      boxShadow: "0 2px 8px 0 #0A4FA424",
      borderRadius: "8px",
    },
    "& label": {
      fontFamily: FONTS.INTER,
      fontWeight: 600,
      fontSize: 14,
      color: COLORS.PRIMARY_BLUE,
      cursor: "pointer",
    },
  },

  step4ButtonWrapper: {
    display: "flex",
    justifyContent: "center",
  },

  step3FormField: {
    marginBottom: theme.spacing(0.5),
  },
  step3FlexColumn: {
    display: "flex",
    flexDirection: "column",
  },

  step3Error: {
    color: "#E62310",
    fontSize: 12,
    fontFamily: FONTS.INTER,
    marginTop: theme.spacing(0.5),
    marginLeft: theme.spacing(1),
    background: "transparent",
  },

  // Step 5 Summary
  step5Card: {
    padding: theme.spacing(2),
  },
  step5Divider: {
    margin: "12px 0",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  step5DividerIcon: {
    width: "100%",
    height: "auto",
    maxHeight: 2,
    marginLeft: "-55px",
    [theme.breakpoints.down("lg")]: {
      marginLeft: "0px",
    },
    [theme.breakpoints.down("md")]: {
      marginLeft: "-55px",
    },
  },
  step5Grid: {
    display: "grid",
    gridTemplateColumns: "140px 1fr",
    rowGap: 4,
    columnGap: 16,
  },
  step5GridSpace: {
    paddingLeft: 25,
  },
  step5SectionTitle: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontWeight: 700,
    color: COLORS.PRIMARY_BLUE,
    marginBottom: 4,
  },

  // Utility classes
  gridFlexItem: {
    display: "flex",
  },
  fullWidthBox: {
    width: "100%",
  },

  // Step 5 summary styles
  step5SectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1),
  },
  step5SectionIcon: {
    width: 24,
    height: 24,
  },
  step5SectionTitleWithIcon: {
    fontSize: 18,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
  },
  step5DetailItem: {
    marginBottom: theme.spacing(1),
    fontSize: 14,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
  },
  step5DetailLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    marginBottom: theme.spacing(0.5),
  },
  step5DetailValue: {
    fontSize: 14,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    marginBottom: theme.spacing(1),
  },
  step5DetailValueSpace: {
    paddingRight: "15px",
  },

  // Step 6 payment styles
  step6PaymentCard: {
    padding: theme.spacing(4),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 200,
  },
  step6RazorpayLogo: {
    maxWidth: 300,
    height: "auto",
  },

  // Step 7 success styles
  step7SuccessContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 400,
  },
  step7SuccessIcon: {
    width: 120,
    height: 120,
    marginBottom: theme.spacing(1),
  },
  step7TickIcon: {
    width: 120,
    height: 120,
    color: "white",
  },
  step7SuccessTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: "#4CAF50",
    fontFamily: FONTS.INTER,
    marginBottom: theme.spacing(0.5),
  },
  step7SuccessMessage: {
    fontSize: 13,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    textAlign: "center",
    marginBottom: theme.spacing(2.5),
    maxWidth: 600,
    fontWeight: 600,
  },
  step7DownloadButton: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    backgroundColor: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    padding: `${theme.spacing(1)} ${theme.spacing(2)}`,
    borderRadius: 8,
    textDecoration: "none",
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    border: "none",
    cursor: "pointer",
  },
  step7PdfIcon: {
    width: 24,
    height: 24,
  },

  // Step 8 payment failed styles
  step8FailedContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 400,
  },
  step8FailedIcon: {
    width: 120,
    height: 120,
    marginBottom: theme.spacing(1),
  },
  step8ErrorIcon: {
    width: 120,
    height: 120,
    color: "#E62310",
  },
  step8FailedTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: "#E62310",
    fontFamily: FONTS.INTER,
    marginBottom: theme.spacing(0.5),
  },
  step8FailedMessage: {
    fontSize: 13,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    textAlign: "center",
    marginBottom: theme.spacing(2.5),
    maxWidth: 600,
    fontWeight: 600,
  },
  step8RetryButton: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    backgroundColor: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    padding: `${theme.spacing(1)} ${theme.spacing(3)}`,
    borderRadius: 6,
    textDecoration: "none",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    fontSize: 14,
    border: "none",
    cursor: "pointer",
    boxShadow: SHADOWS.MEDIUM,
  },
  desktopSearchResults: {
    position: "absolute",
    top: 44,
    right: 8,
    minWidth: 260,
    maxWidth: 420,
    maxHeight: 320,
    overflowY: "auto",
    background: COLORS.WHITE,
    borderRadius: 8,
    boxShadow: SHADOWS.DARK_CARD,
    zIndex: 300,
  },
  desktopSearchResultItem: {
    display: "flex",
    alignItems: "center",
    padding: "10px 12px",
    cursor: "pointer",
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontSize: 14,
    "&:hover": {
      background: COLORS.WHITE_GRAY,
    },
  },
}));

export default useSharedStyles;
