import { makeStyles } from 'tss-react/mui';
import type { Theme } from '@mui/material';

const useSharedStyles = makeStyles()((theme: Theme) => ({
  layout:{
    minHeight: '100vh',width:"100%",overflow:"hidden"
  },
  footerRoot: {
    width: '100%',
    minHeight: 550,
    position: 'relative',
    paddingTop: 0,
    paddingBottom: 0,
    overflow: 'hidden',
    [theme.breakpoints.down('md')]: {
      minHeight: 750,
    },
  },
  footerBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '120%',
    objectFit: 'cover',
    objectPosition: 'top',
    zIndex: 0,
    [theme.breakpoints.down('md')]: {
      height: '100%',
    },
  },
  footerContent: {
    position: 'relative',
    marginTop: 100,
    zIndex: 1,
    paddingLeft: theme.spacing(8),
    paddingRight: theme.spacing(8),
    paddingTop: theme.spacing(8),
    paddingBottom: theme.spacing(2),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    [theme.breakpoints.down('md')]: {
      marginTop: 85,
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
      paddingTop: theme.spacing(3),
    },
  },
  footerLogoBox: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 0,
    [theme.breakpoints.down('md')]: {
      justifyContent: 'flex-start',
      marginBottom: theme.spacing(2),
    },
  },
  footerLogo: {
    width: 180,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      width: 120,
      marginTop: 20,
    },
  },
  subscribeBox: {
    width: '100%',
    maxWidth: 600,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing(4),
    marginTop: theme.spacing(2),
    gap: 0,
    justifyContent: 'center',
    [theme.breakpoints.down('md')]: {
      flexDirection: 'column',
      gap: theme.spacing(2),
      marginBottom: theme.spacing(4),
      marginTop: theme.spacing(2),
    },
  },
  subscribeInput: {
    flex: 1,
    background: '#fff',
    borderRadius: 3,
    paddingLeft: theme.spacing(2),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    fontSize: 22,
    boxShadow: '0 2px 8px 0 #0A4FA422',
    height: 56,
    paddingRight: 0,
    width: 'auto',
    minWidth: 0,
    marginBottom: 0,
    [theme.breakpoints.down('md')]: {
      fontSize: 16,
      height: 44,
      width: '100%',
      marginBottom: theme.spacing(1),
    },
  },
  subscribeButton: {
    background: '#0463EE',
    color: '#fff',
    fontWeight: 400,
    fontSize: 16,
    borderRadius: 999,
    marginRight: theme.spacing(2),
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    height: 'fit-content',
    boxShadow: '0 2px 8px 0 #0A4FA422',
    textTransform: 'none',
    letterSpacing: 0.5,
    minWidth: 0,
    '&:hover': { background: '#1251a3' },
    [theme.breakpoints.down('md')]: {
      fontSize: 14,
    },
  },
  navLinks1: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-start',
  },
  navLink: {
    color: '#fff',
    fontWeight: 400,
    fontSize: 16,
    marginBottom: 4,
    cursor: 'pointer',
    '&:hover': { textDecoration: 'underline' },
    [theme.breakpoints.down('md')]: {
      fontSize: 14,
      marginBottom: 2,
    },
  },
  navLinks2: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-start',
  },
  navLinkBold: {
    color: '#fff',
    fontWeight: 700,
    fontSize: 16,
    marginBottom: 4,
    cursor: 'pointer',
    '&:hover': { textDecoration: 'underline' },
    [theme.breakpoints.down('md')]: {
      fontSize: 14,
      marginBottom: 2,
    },
  },
  contactBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    alignItems: 'flex-start',
    minWidth: 160,
    marginTop: 0,
    [theme.breakpoints.down('md')]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  contactTitle: {
    color: '#fff',
    fontWeight: 700,
    fontSize: 18,
    marginBottom: 8,
    textAlign: 'center',
    [theme.breakpoints.down('md')]: {
      fontSize: 15,
      marginBottom: 4,
    },
  },
  contactRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: '#fff',
    marginBottom: 4,
  },
  contactText: {
    fontSize: 15,
    [theme.breakpoints.down('md')]: {
      fontSize: 13,
    },
  },
  socialIcons: {
    display: 'flex',
    gap: 16,
    marginTop: 16,
    justifyContent: 'center',
  },
  mapBox: {
    minWidth: 120,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    [theme.breakpoints.down('md')]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  mapImg: {
    width: 220,
    height: 160,
    borderRadius: 3,
    boxShadow: theme.shadows[2],
    objectFit: 'cover',
    [theme.breakpoints.down('md')]: {
      width: 120,
      height: 90,
    },
  },
  copyright: {
    width: '100%',
    borderTop: '1px solid #e0e7ef',
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    marginTop: 0,
    textAlign: 'center',
    color: '#fff',
    fontSize: 17,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    position: 'absolute',
    left: 0,
    bottom: 0,
    background: 'transparent',
    [theme.breakpoints.down('md')]: {
      fontSize: 13,
    },
  },
  footerLogoBoxMobile: {
    width: '100%',
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: 16,
    [theme.breakpoints.up('md')]: {
      display: 'none',
      marginBottom:0
    },
  },
  navLinksBoxMobile: {
    width: '50%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    alignItems: 'flex-start',
    paddingLeft: 8,
  },
  navLinksBoxDesktop: {
    gap: 12,
  },
  contactBoxMobile: {
    width: '50%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    alignItems: 'flex-start',
    paddingLeft: 8,
    marginTop: 16,
  },
  contactBoxDesktop: {
    minWidth: 160,
    gap: 8,
  },
  mapBoxMobile: {
    width: '50%',
    boxSizing: 'border-box',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 0,
    marginTop: 16,
  },
  mapBoxDesktop: {
    minWidth: 120,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBoxDesktop: {
    minWidth: 120,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  footerLogoDesktop: {
    width: 180,
    marginBottom: 16,
  },
  navLinkMobile: {
    fontSize: 14,
    fontWeight: 400,
    marginBottom: 4,
  },
  navLinkBoldMobile: {
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 4,
  },
  navLinkDesktop: {
    fontSize: 16,
    fontWeight: 400,
    marginBottom: 4,
  },
  navLinkBoldDesktop: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 4,
  },
  contactTitleMobile: {
    fontWeight: 700,
    fontSize: 15,
    marginBottom: 8,
  },
  contactTitleDesktop: {
    color: '#fff',
    fontWeight: 700,
    fontSize: 18,
    marginBottom: 8,
    textAlign: 'center',
  },
  contactTextMobile: {
    fontSize: 13,
  },
  contactTextDesktop: {
    fontSize: 15,
  },
  socialIconsMobile: {
    gap: 16,
    marginTop: 16,
  },
  socialIconsDesktop: {
    gap: 16,
    marginTop: 16,
    justifyContent: 'center',
  },
  mapImgMobile: {
    width: 120,
    height: 90,
  },
  mapImgDesktop: {
    width: 220,
    height: 160,
  },
  copyrightMobile: {
    fontSize: 13,
  },
  copyrightDesktop: {
    fontSize: 17,
  },
  appBar: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    zIndex: 1200,
    transition: 'background 0.3s, color 0.3s, box-shadow 0.3s',
  },
  appBarTrigger: {
    background: '#fff',
    color: '#000',
    boxShadow: theme.shadows[2],
  },
  appBarNoTrigger: {
    background: 'transparent',
    color: '#fff',
    boxShadow: 'none',
  },
  mobileTopBar: {
    width: '100vw',
    maxWidth: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    background: '#fff',
    color: theme.palette.primary.main,
    paddingLeft: 0,
    paddingRight: 0,
    minHeight: 36,
    borderBottom: '1px solid #e0e0e0',
    position: 'fixed',
    top: 0,
    left: 0,
    zIndex: 1301,
    fontSize: 12,
  },
  mobileContact: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontWeight: 500,
    fontSize: 10,
  },
  mobileFont:{
    fontSize:13,
  },
  mobileDivider: {
    width: 1,
    height: 16,
    background: theme.palette.primary.main,
  },
  mobileSidebarBtn: {
    background: '#fff',
    color: theme.palette.primary.main,
    borderRadius: '50%',
    width: 30,
    height: 30,
    boxShadow: theme.shadows[1],
    marginTop: 16,
    marginLeft: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileSidebarIcon: {
    width: 14,
    height: 14,
    display: 'block',
  },
  mobileHeaderBar: {
    width: '100vw',
    maxWidth: '100vw',
    display: 'flex',
    alignItems: 'center',
    background: 'transparent',
    paddingLeft: 0,
    paddingRight: 0,
    minHeight: 44,
    position: 'fixed',
    top: 36,
    left: 0,
    zIndex: 1301,
  },
  desktopTopBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    width: '100%',
    transition: 'background 0.3s, color 0.3s, border-bottom 0.3s',
  },
  desktopTopBarTrigger: {
    background: '#fff',
    color: theme.palette.primary.main,
  },
  desktopTopBarNoTrigger: {
    background: 'transparent',
    color: '#fff',
  },
  desktopContact: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'nowrap',
    width: 'auto',
  },
  desktopDivider: {
    width: 1,
    height: 20,
    background: theme.palette.primary.main,
  },
  desktopDividerNoTrigger: {
    background: '#1976d2',
  },
  desktopSearchPaper: {
    padding: '1px 6px',
    display: 'flex',
    alignItems: 'center',
    width: 300,
    borderRadius:999,
    marginRight: theme.spacing(8),
    border: 'none',
    boxShadow: 'none',
    background: '#fff',
    transition: 'background 0.3s, border 0.3s',
  },
  desktopSearchPaperTrigger: {
    border: `1.5px solid ${theme.palette.primary.main}`,
  },
  desktopToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1),
    minHeight: 64,
    background: 'transparent',
  },
  desktopLogo: {
    height: 80,
    width: 80,
    marginRight: theme.spacing(4),
    borderRadius: 2,
  },
  desktopNav: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginLeft: theme.spacing(4),
    gap: 24,
  },
  desktopNavItem: {
    fontWeight: 500,
    background: 'transparent',
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0,
    borderRadius: 0,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  desktopNavItemActiveTrigger: {
    color: '#fff',
    background: theme.palette.primary.main,
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: 5,
  },
  desktopNavItemInactiveTrigger: {
    color: theme.palette.primary.main,
    background: 'transparent',
  },
  desktopNavItemActiveNoTrigger: {
    color: theme.palette.primary.main,
    background: '#fff',
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: 5,
  },
  desktopNavItemInactiveNoTrigger: {
    color: '#fff',
    background: 'transparent',
  },
  drawerPaper: {
    width: 220,
    background: '#fff',
    boxShadow: 'none',
    paddingTop: theme.spacing(2),
  },
  drawerBackdrop: {
    background: 'rgba(0,0,0,0.2)',
  },
  drawerNavItem: {
    fontWeight: 500,
    color: 'inherit',
    background: 'transparent',
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 2,
    cursor: 'pointer',
    width: '100%',
    transition: 'all 0.2s',
  },
  drawerNavItemActive: {
    fontWeight: 700,
    color: theme.palette.primary.main,
    background: theme.palette.action.selected,
  },
  desktopSearchIcon: {
    padding: 6,
    color: theme.palette.primary.main,
  },
  desktopSearchInput: {
    marginLeft: 12,
    flex: 1,
    fontSize: 12,
    color: '#000',
    '&::placeholder': {
      color: '#9A9EA5',
      opacity: 1,
    },
  },
  footerSocialIconWhite: {
    color: '#fff',
  },
  headerSearchIcon: {
    fontSize: 20,
    color: theme.palette.primary.main,
  },
}));

export default useSharedStyles; 