import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, SHADOWS, TYPOGRAPHY, FONTS, baseStyles } from "./styles";

const useSharedStyles = makeStyles()((theme: Theme) => ({
  loadingLayout: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100vh",
  },
  layout: {
    minHeight: "100vh",
    width: "100%",
    overflow: "hidden",
  },
  footerRoot: {
    width: "100%",
    minHeight: 550,
    position: "relative",
    paddingTop: 0,
    paddingBottom: 0,
    overflow: "hidden",
    [theme.breakpoints.down("lg")]: {
      minHeight: 650,
    },
  },
  footerBg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "120%",
    objectFit: "cover",
    objectPosition: "top",
    zIndex: 0,
    [theme.breakpoints.down("lg")]: {
      height: "100%",
    },
  },
  footerContent: {
    position: "relative",
    marginTop: 100,
    zIndex: 1,
    paddingLeft: theme.spacing(8),
    paddingRight: theme.spacing(8),
    paddingTop: theme.spacing(8),
    paddingBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    [theme.breakpoints.down("lg")]: {
      paddingBottom: 50,
      marginTop: "50px",
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
    },
  },
  footerLogoBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginBottom: 0,
    [theme.breakpoints.down("lg")]: {
      justifyContent: "flex-start",
      marginBottom: theme.spacing(2),
    },
  },
  footerLogo: {
    width: 180,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("lg")]: {
      width: 80,
      marginTop: 20,
    },
  },
  subscribeBox: {
    width: "100%",
    maxWidth: 350,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacing(4),
    marginTop: theme.spacing(2),
    gap: 0,
    justifyContent: "center",
    [theme.breakpoints.down("lg")]: {
      flexDirection: "column",
      gap: theme.spacing(2),
    },
  },
  subscribeInput: {
    flex: 1,
    borderRadius: 999,
    background: COLORS.WHITE,
    paddingLeft: theme.spacing(2),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    ...TYPOGRAPHY.subtitle1(theme),
    boxShadow: SHADOWS.DARK_CARD,
    height: 42,
    paddingRight: 0,
    width: "auto",
    minWidth: 0,
    marginBottom: 0,
    [theme.breakpoints.down("lg")]: {
      ...TYPOGRAPHY.body1(theme),
      height: "24px",
      fontSize: "12px",
      width: "100%",
      borderRadius: 10,
      marginTop: 30,
      marginBottom: 10,
      padding: "1.5px 0px 1.5px 10px",
    },
  },
  subscribeButton: {
    ...baseStyles.button(theme),
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    marginRight: theme.spacing(2),
    height: 28,
    letterSpacing: 0.5,
    minWidth: 0,
    "&:hover": { background: COLORS.HERO_BLUE },
    [theme.breakpoints.down("lg")]: {
      ...TYPOGRAPHY.body1(theme),
    },
  },
  topInBig: {
    marginTop: "90px",
    [theme.breakpoints.down("lg")]: {
      marginTop: 0,
    },
  },
  linksFlex: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
  },
  navLinks1: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
  },
  navLink: {
    color: COLORS.WHITE,
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
    cursor: "pointer",
    "&:hover": { textDecoration: "underline" },
  },
  navLinks2: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
  },
  navLinkBold: {
    color: COLORS.WHITE,
    ...TYPOGRAPHY.subtitle1(theme),
    fontWeight: 500,
    marginBottom: 4,
    cursor: "pointer",
    "&:hover": { textDecoration: "underline" },
  },
  contactBox: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    alignItems: "flex-start",
    minWidth: 160,
    marginTop: 0,
    [theme.breakpoints.down("lg")]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  contactTitle: {
    ...TYPOGRAPHY.subtitle1(theme),
    color: COLORS.WHITE,
    marginBottom: 8,
    textAlign: "center",
  },
  contactRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: COLORS.WHITE,
    marginBottom: 4,
  },
  contactText: {
    ...TYPOGRAPHY.body2(theme),
    color: COLORS.WHITE,
  },
  socialIcons: {
    display: "flex",
    gap: 16,
    marginTop: 16,
    justifyContent: "center",
  },
  mapBox: {
    minWidth: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    [theme.breakpoints.down("lg")]: {
      minWidth: 0,
      marginTop: theme.spacing(2),
    },
  },
  mapImg: {
    width: 220,
    height: 160,
    borderRadius: 3,
    objectFit: "cover",
    [theme.breakpoints.down("lg")]: {
      width: 180,
      height: 140,
    },
  },
  copyright: {
    width: "100%",
    borderTop: `1px solid ${COLORS.LIGHT_GRAY}`,
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    marginTop: 0,
    textAlign: "center",
    color: COLORS.WHITE,
    ...TYPOGRAPHY.body1(theme),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    position: "absolute",
    left: 0,
    bottom: 0,
    background: "transparent",
  },
  footerLogoBoxMobile: {
    display: "flex",
    justifyContent: "flex-start",
    marginBottom: 16,
    [theme.breakpoints.up("lg")]: {
      display: "none",
      marginBottom: 0,
    },
  },
  navLinksBoxMobile: {
    width: "50%",
    marginBottom: 20,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-start",
    paddingLeft: 8,
  },
  navLinksBoxMobile2: {
    alignItems: "flex-end",
  },
  navLinksBoxDesktop: {
    gap: 12,
  },
  contactBoxMobile: {
    width: "50%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-start",
    paddingLeft: 8,
    marginTop: 16,
  },
  contactBoxDesktop: {
    minWidth: 160,
    gap: 8,
  },
  flexRoot: {
    width: "100%",
    display: "flex",
    flexWrap: "wrap",
  },
  flexSide: {
    display: "flex",
    width: "100%",
    gap: "20px",
  },
  mapBoxMobile: {
    width: "50%",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-start",
    minWidth: 0,
    marginTop: 16,
  },
  mapBoxDesktop: {
    minWidth: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  logoBoxDesktop: {
    minWidth: 120,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    [theme.breakpoints.down("lg")]: {
      display: "none",
    },
  },
  footerLogoDesktop: {
    width: 180,
    marginBottom: 16,
  },
  navLinkMobile: {
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
  },
  navLinkBoldMobile: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontWeight: 500,
    marginBottom: 4,
  },
  navLinkDesktop: {
    ...TYPOGRAPHY.body1(theme),
    marginBottom: 4,
  },
  navLinkBoldDesktop: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 16,
    fontWeight: 500,
    marginBottom: 4,
  },
  contactTitleMobile: {
    ...TYPOGRAPHY.subtitle1(theme),
    marginBottom: 8,
  },
  contactTitleDesktop: {
    ...TYPOGRAPHY.subtitle1(theme),
    color: COLORS.WHITE,
    marginBottom: 8,
    textAlign: "center",
  },
  contactTextMobile: {
    ...TYPOGRAPHY.body2(theme),
  },
  contactTextDesktop: {
    ...TYPOGRAPHY.body2(theme),
  },
  socialIconsMobile: {
    display: "flex",
    gap: 16,
    marginTop: 16,
  },
  socialIconsDesktop: {
    display: "flex",
    gap: 12,
    marginTop: 16,
    justifyContent: "center",
  },
  mapImgMobile: {
    width: 40,
    height: 90,
    borderRadius: "20px",
    [theme.breakpoints.up("lg")]: {
      width: 150,
      height: 150,
    },
  },
  mapImgDesktop: {
    marginTop: "20px",
    width: 320,
    height: 230,
    borderRadius: 20,
  },
  copyrightMobile: {
    ...TYPOGRAPHY.body2(theme),
  },
  copyrightDesktop: {
    ...TYPOGRAPHY.body1(theme),
  },
  appBar: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    zIndex: 1200,
    transition: "background 0.3s, color 0.3s, box-shadow 0.3s",
  },
  appBarTrigger: {
    background: COLORS.WHITE,
    color: COLORS.DARK,
    boxShadow: SHADOWS.SUBTLE,
  },
  appBarNoTrigger: {
    background: "transparent",
    color: COLORS.WHITE,
    boxShadow: "none",
  },
  mobileTopBar: {
    width: "100vw",
    maxWidth: "100vw",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-evenly",
    background: COLORS.WHITE,
    color: theme.palette.primary.main,
    paddingLeft: 0,
    paddingRight: 0,
    minHeight: 36,
    borderBottom: `1px solid ${COLORS.BBB}`,
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1301,
    ...TYPOGRAPHY.body2(theme),
  },
  mobileContact: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontWeight: 500,
    fontSize: 10,
  },
  mobileFont: {
    ...TYPOGRAPHY.body2(theme),
  },
  mobileDivider: {
    width: 1,
    height: 16,
    background: theme.palette.primary.main,
  },
  mobileSidebarBtn: {
    background: COLORS.SECONDARY_BLUE,
    color: theme.palette.primary.main,
    borderRadius: "50%",
    width: 35,
    height: 35,
    boxShadow: SHADOWS.SUBTLE,
    margin: "0px 15px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileSidebarIcon: {
    width: 18,
    height: 18,
    display: "block",
    color: "white",
  },
  mobileHeaderBar: {
    width: "100vw",
    maxWidth: "100vw",
    display: "flex",
    alignItems: "center",
    justifyItems: "justify-between",
    background: "white",
    padding: "5px",
    minHeight: 44,
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1301,
  },
  logo_mb: {
    paddingRight: "10px",
  },
  mobileFlex: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  desktopTopBar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    width: "100%",
    transition: "background 0.3s, color 0.3s, border-bottom 0.3s",
  },
  desktopTopBarTrigger: {
    background: COLORS.WHITE,
    color: theme.palette.primary.main,
  },
  desktopTopBarNoTrigger: {
    background: "transparent",
    color: COLORS.WHITE,
  },
  desktopContact: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "nowrap",
    width: "auto",
  },
  desktopDivider: {
    width: 1,
    height: 20,
    background: theme.palette.primary.main,
  },
  desktopDividerNoTrigger: {
    background: COLORS.LIGHT_BLUE,
  },
  desktopSearchPaper: {
    padding: "3px 6px",
    display: "flex",
    alignItems: "center",
    width: 300,
    borderRadius: 999,
    marginRight: theme.spacing(1),
    border: `1.5px solid ${COLORS.WHITE}`,
    boxShadow: "none",
    background: "transparent",
    transition: "background 0.3s, border 0.3s",
  },
  desktopSearchPaperTrigger: {
    border: `1.5px solid ${theme.palette.primary.main}`,
  },
  desktopToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1),
    minHeight: 64,
    background: "transparent",
  },
  desktopLogo: {
    height: 95,
    width: 95,
    marginRight: theme.spacing(4),
    borderRadius: 2,
  },
  desktopNav: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-around",
    marginLeft: theme.spacing(4),
    gap: 24,
  },
  desktopNavItem: {
    fontWeight: 500,
    background: "transparent",
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0,
    borderRadius: 0,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  desktopNavItemActiveTrigger: {
    color: COLORS.WHITE,
    background: theme.palette.primary.main,
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: "999px",
  },
  desktopNavItemInactiveTrigger: {
    color: theme.palette.primary.main,
    background: "transparent",
  },
  desktopNavItemActiveNoTrigger: {
    color: theme.palette.primary.main,
    background: COLORS.LIGHTWHITE,
    fontWeight: 700,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    borderRadius: "999px",
  },
  desktopNavItemInactiveNoTrigger: {
    color: COLORS.WHITE,
    background: "transparent",
  },
  drawerPaper: {
    width: 220,
    background: COLORS.WHITE,
    boxShadow: "none",
    paddingTop: theme.spacing(2),
  },
  drawerBackdrop: {
    background: COLORS.DARK_SHADOW,
  },
  drawerNavItem: {
    fontWeight: 500,
    color: "inherit",
    background: "transparent",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 2,
    cursor: "pointer",
    width: "100%",
    transition: "all 0.2s",
  },
  drawerNavItemActive: {
    fontWeight: 700,
    color: theme.palette.primary.main,
    background: theme.palette.action.selected,
  },
  desktopSearchIcon: {
    padding: 6,
    color: theme.palette.primary.main,
  },
  desktopSearchInput: {
    marginLeft: 6,
    flex: 1,
    ...TYPOGRAPHY.body2(theme),
    fontSize: "12px",
    color: COLORS.DARK,
    "&::placeholder": {
      color: COLORS.MEDIUM_GRAY,
      opacity: 1,
    },
  },
  footerSocialIconWhite: {
    color: COLORS.WHITE,
  },
  headerSearchIcon: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 22,
    color: COLORS.WHITE,
  },
  headerSearchIconTrigger: {
    ...TYPOGRAPHY.subtitle1(theme),
    fontSize: 22,
    color: theme.palette.primary.main,
  },
  hideInBig: {
    [theme.breakpoints.up("lg")]: {
      display: "none",
    },
  },

  // ContactBox styles
  contactBoxWrapper: {
    width: "100%",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: 12,
    boxShadow: SHADOWS.DARK_CARD,
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    fontSize: 16,
    gap: theme.spacing(1.5),
  },
  contactBoxTitle: {
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 18,
    color: COLORS.SECONDARY_BLUE,
    marginBottom: 4,
  },
  contactBoxLabel: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
    marginBottom: 4,
  },
  contactBoxValue: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
  },
  contactBoxIcon: {
    color: COLORS.SECONDARY_BLUE,
    fontSize: 18,
  },
  contactBoxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },

  // Testimonials
}));

export default useSharedStyles;
