// src/components/userflow/Cultures/culturesStyles.tsx
import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";
import pdfWaterBg from "../../../assets/cultures/pdf_water.png";

const useCulturesStyles = makeStyles()((theme: Theme) => ({
  // Layout styles
  culturesLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  culturesMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
    },
  },
  culturesMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(20),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },

  // Hero styles
  culturesHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  culturesHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  culturesHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  culturesHeroColorOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "#0A4FA469",
    opacity: 0.45,
    zIndex: 3,
  },
  culturesHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  culturesHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 64,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  culturesHeroSubtitle: {
    color: COLORS.WHITE,
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    fontSize: 18,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  culturesHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      marginTop: theme.spacing(2),
    },
  },

  // Sidebar styles
  culturesSidebarWrapper: {
    width: 240,
    display: "flex",
    position:'relative',
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  culturesSidebar: {
    position:'absolute',
    zIndex:'100',
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  culturesSidebarNavTitle: {
    fontWeight: 700,
    fontSize: 40,
    margin: theme.spacing(1),
  },
  culturesSidebarNavItem: {
    fontWeight: 500,
    fontSize: 18,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 999,
    cursor: "pointer",
    fontFamily: "Roboto",
    background: "transparent",
    color: COLORS.WHITE,
    textDecoration: "none",
    transition: "300ms ease",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 600,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  culturesSidebarFish: {
    marginTop: theme.spacing(4),
    width: "100%",
    display: "flex",
    justifyContent: "center",
    "& img": {
      width: "80%",
      objectFit: "contain",
      opacity: 0.7,
    },
  },

  sideImg: {
    maxWidth: "200px",
    maxHeight: "200px",
    display: "block",
  },
  culturesSideImg: {
    position: "absolute",
    top: -20,
    right: "20px",
    maxWidth: "400px",
    maxHeight: "200px",
    opacity: 0.6,
    zIndex: 1,
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },

  // Culture Page Header Styles
  culturePageHeader: {
    position: "relative",
    marginBottom: theme.spacing(10),
    width: "100%",
    display: "flex",
    alignItems: "center",
  },
  culturePageBanner: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100%",
    zIndex: 2,
  },
  culturePageIcon: {
    position: "absolute",
    left: "-40px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "180px",
    height: "180px",
    borderRadius: "50%",
    borderRight: "4px solid #F7FAFC",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #0A4FA4 0%, #041E3E 100%)",
    zIndex: 3,
    // Keep visual style consistent; scale container via transform to avoid gradient/shape changes
    [theme.breakpoints.down("md")]: {
      transform: "translateY(-50%) scale(0.7)",
      transformOrigin: "left center",
      left: "-20px",
      width: "180px",
      height: "180px",
    },
  },
  culturePageIconImg: {
    width: "130px",
    height: "130px",
    objectFit: "contain",
    filter: "brightness(0) invert(1)",
    [theme.breakpoints.down("md")]: {
      width: "80px",
      height: "80px",
    },
  },
  culturePageTextContent: {
    background: "linear-gradient(135deg, #0A4FA4 0%, #041E3E 100%)",
    borderRadius: "0 16px 16px 0",
    padding: theme.spacing(4, 8, 4, 14),
    marginLeft: "60px",
    flex: 1,
    height: "auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.3)",
    // Keep background appearance identical across breakpoints (no opacity/padding change)
    opacity: 1,
    [theme.breakpoints.down("md")]: {
      // scale the whole block uniformly to match desktop styling while reducing size
      transform: "scale(0.9)",
      transformOrigin: "left center",
      marginLeft: "40px",
    },
  },
  culturePageTitle: {
    margin: 0,
    fontSize: "44px",
    fontWeight: 400,
    textTransform: "capitalize",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.WHITE,
    letterSpacing: "1px",
    lineHeight: 1.1,
    [theme.breakpoints.down("md")]: {
      fontSize: "24px",
    },
  },
  culturePageSubtitle: {
    margin: "14px 0 0 0",
    fontSize: "18px",
    opacity: 0.95,
    fontFamily: FONTS.INTER,
    color: COLORS.WHITE,
    fontWeight: 400,
    lineHeight: 1.4,
    [theme.breakpoints.down("lg")]: {
      fontSize: "16px",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "13px",
      marginTop: "10px",
    },
  },
  culturePageFishBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
    zIndex: 1,
    overflow: "visible",
  },

  // Card styles
  culturesCard: {
    background: COLORS.WHITE_GRAY,
    borderRadius: 12,
    boxShadow: SHADOWS.LARGE,
    padding: theme.spacing(4),
    marginBottom: theme.spacing(8),
    position: "relative",
    transition: "box-shadow 0.2s",
    minWidth: 0,
    maxWidth: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(2),
      marginBottom: theme.spacing(6),
    },
  },
  culturesCardTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: theme.spacing(2),
    fontSize: 32,
    [theme.breakpoints.down("md")]: {
      fontSize: 22,
      marginBottom: theme.spacing(1.5),
    },
  },
  culturesCardDesc: {
    fontSize: 20,
    fontWeight: 500,
    color: COLORS.DARK,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      marginBottom: theme.spacing(4),
    },
  },
  culturesCardImg: {
    width: "100%",
    borderRadius: 8,
    marginBottom: theme.spacing(2),
    marginTop: theme.spacing(1),
    display: "block",
  },

  // PDF Download Section styles
  pdfDownloadSection: {
    width: "100vw",
    position: "relative",
    left: "50%",
    right: "50%",
    marginLeft: "-50vw",
    marginRight: "-50vw",
    marginTop: theme.spacing(4),
    marginBottom: theme.spacing(8),
    backgroundImage: `url(${pdfWaterBg})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundColor: COLORS.PRIMARY_BLUE,
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(4),
      marginBottom: theme.spacing(4),
    },
  },
  pdfDownloadContainer: {
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(8),
    [theme.breakpoints.down("md")]: {
      gap: theme.spacing(2),
    },
    [theme.breakpoints.down("sm")]: {
      gap: theme.spacing(0.5),
    },
  },
  pdfDownloadImageSection: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  pdfDownloadFishImage: {
    width: "auto",
    height: "100%",
    objectFit: "contain",
    filter: "drop-shadow(0 8px 16px rgba(0, 0, 0, 0.3))",
    maxHeight: "200px",
    [theme.breakpoints.down("md")]: {
      maxWidth: "200px",
    },
    [theme.breakpoints.down("sm")]: {
      maxWidth: "150px",
    },
  },
  pdfDownloadContent: {
    flex: 1,
    color: COLORS.WHITE,
    padding: "10px",
    [theme.breakpoints.down("sm")]: {
      padding: "5px",
    },
  },
  pdfDownloadTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    fontSize: "2rem",
    lineHeight: 1.2,
    marginBottom: theme.spacing(1.5),
    color: COLORS.WHITE,
    [theme.breakpoints.down("md")]: {
      fontSize: "1.25rem",
      marginBottom: theme.spacing(0.5),
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "1rem",
    },
  },
  pdfDownloadDescription: {
    fontSize: "0.9rem",
    lineHeight: 1.6,
    marginBottom: theme.spacing(2.5),
    fontStyle: FONTS.INTER,
    opacity: 0.95,
    maxWidth: "600px",
    [theme.breakpoints.down("md")]: {
      fontSize: "0.7rem",
      marginBottom: theme.spacing(1),
      maxWidth: "100%",
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "0.6rem",
    },
  },
  pdfDownloadButton: {
    backgroundColor: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    fontWeight: 400,
    fontSize: "1rem",
    padding: theme.spacing(0.5, 2),
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    borderRadius: "8px",
    textTransform: "none",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.2)",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
    marginBottom: 1,
    "&:hover": {
      backgroundColor: COLORS.WHITE,
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.3)",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "0.7rem",
      padding: theme.spacing(0.5, 1),
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "0.6rem",
    },
  },
  pdfDownloadButtonIcon: {
    fontSize: "1.2rem",
    display: "flex",
    alignItems: "center",
    "& img": {
      width: 23,
      height: 23,
      display: "block",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "0.7rem",
      "& img": {
        width: 14,
        height: 14,
      },
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "0.6rem",
      "& img": {
        width: 12,
        height: 12,
      },
    },
  },

  // PDF Modal styles
  pdfDialogPaper: {
    borderRadius: 12,
    overflow: "hidden",
    background: "linear-gradient(0deg, #9BC4FF 0%, #FFFFFF 100%)",
    paddingLeft: theme.spacing(0),
    paddingRight: theme.spacing(0),
    paddingBottom: theme.spacing(3),
    "& .MuiDialogContent-root": {
      overflowY: "scroll",
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
      scrollbarWidth: "none",
      msOverflowStyle: "none",
    },
    "& .MuiDialogContent-root::-webkit-scrollbar": {
      width: 0,
      height: 0,
    },
    "& .MuiDialogContent-root::-webkit-scrollbar-thumb": {
      background: "transparent",
    },
  },
  pdfDialogTitle: {
    textAlign: "center",
    paddingTop: theme.spacing(2),
    paddingBottom: theme.spacing(2),
  },
  pdfDialogTitlePill: {
    display: "inline-block",
    paddingLeft: theme.spacing(2.5),
    paddingRight: theme.spacing(2.5),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    backgroundColor: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 999,
    fontWeight: 600,
    fontSize: 14,
    maxWidth: "fit-content",
    margin: "10px auto 5px auto",
  },
  pdfDialogTitlePillFloat: {
    backgroundColor: COLORS.SECONDARY_BLUE,
    borderRadius: "10px",
    textTransform: "capitalize",
    margin: "auto",
  },
  pdfDialogFlex: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pdfDialogContentContainer: {
    paddingTop: 0,
    overflow: "hidden",
  },
  pdfDialogStack: {
    maxWidth: 520,
    marginLeft: "auto",
    marginRight: "auto",
  },
  pdfDialogImage: {
    width: "100%",
    maxWidth: 300,
    display: "block",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 8,
    boxShadow: SHADOWS.LARGE,
    marginBottom: theme.spacing(2),
  },
  pdfDialogSectionTitle: {
    fontWeight: 400,
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(1),
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: "20px",
    color: COLORS.PRIMARY_BLUE,
  },
  pdfDialogList: {
    color: COLORS.PRIMARY_BLUE,
    paddingTop: 0,
    marginBottom: theme.spacing(1.5),
    "& .MuiListItemIcon-root": {
      color: COLORS.PRIMARY_BLUE,
    },
    "& .MuiListItemText-primary": {
      color: COLORS.PRIMARY_BLUE,
    },
  },
  pdfDialogListItem: {
    "& .MuiListItemText-root": {
      margin: 0,
      fontFamily: FONTS.INTER,
      "& .MuiListItemText-primary": {
        fontWeight: 600,
      },
    },
  },
  pdfDialogListItemIcon: {
    minWidth: 14,
    marginRight: theme.spacing(1),
  },
  pdfDialogBulletDot: {
    width: 6,
    height: 6,
    marginRight: "10px",
    borderRadius: 999,
    background: COLORS.PRIMARY_BLUE,
    display: "inline-block",
  },
  pdfDialogPrimaryButton: {
    marginBottom: theme.spacing(2),
    backgroundColor: COLORS.WHITE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.SECONDARY_BLUE,
    fontSize: "16px",
    textTransform: "none",
    fontWeight: 400,
    width: "fit-content",
    boxShadow: "none",
    border: "15px",
    borderRadius: "7px",
    "&.Mui-disabled": {
      backgroundColor: COLORS.WHITE,
      color: COLORS.SECONDARY_BLUE,
      opacity: 1,
      boxShadow: "none",
      pointerEvents: "none",
      cursor: "default",
    },
  },
  pdfDialogPrimaryButtonIconImg: {
    width: 20,
    height: 20,
    display: "block",
  },
  pdfDialogSecondaryButton: {
    backgroundColor: COLORS.SECONDARY_BLUE,
  },

  // CulturePage styles
  culturePageCardsGrid: {
    marginTop: theme.spacing(6),
  },
  culturePageIconRotated: {
    transform: "rotate(-100deg)",
    transition: "transform 0.3s ease",
  },
  culturePageIconNormal: {
    transform: "rotate(0deg)",
    transition: "transform 0.3s ease",
  },
}));

export default useCulturesStyles;
