import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";

const useCulturesStyles = makeStyles()((theme: Theme) => ({
  // Layout styles
  culturesLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  culturesMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
    },
  },
  culturesMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(20),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },

  // Hero styles
  culturesHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  culturesHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  culturesHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  culturesHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  culturesHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 48,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  culturesHeroSubtitle: {
    color: COLORS.WHITE,
    fontWeight: 700,
    fontSize: 22,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  culturesHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      marginTop: theme.spacing(2),
    },
  },

  // Sidebar styles
  culturesSidebarWrapper: {
    width: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  culturesSidebar: {
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  culturesSidebarNavTitle: {
    fontWeight: 700,
    fontSize: 40,
    margin: theme.spacing(1),
  },
  culturesSidebarNavItem: {
    fontWeight: 500,
    fontSize: 18,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 999,
    cursor: "pointer",
    fontFamily: "Roboto",
    background: "transparent",
    color: COLORS.WHITE,
    transition: "300ms ease",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 600,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  culturesSidebarFish: {
    marginTop: theme.spacing(4),
    width: "100%",
    display: "flex",
    justifyContent: "center",
    "& img": {
      width: "80%",
      objectFit: "contain",
      opacity: 0.7,
    },
  },

  // Header styles
  culturesHeaderTitle: {
    color: theme.palette.primary.dark,
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 55,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      maxWidth: "fit-content",
      margin: "auto",
      textAlign: "center",
      marginTop: "-10px",
      marginBottom: "15px",
      padding: "0.5px 60px",
      borderRadius: 999,
      color: COLORS.WHITE,
      background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    },
  },
  culturesHeaderSubtitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 1.3,
    marginTop: 0,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      marginTop: theme.spacing(1),
    },
  },
  culturesHeaderImg: {
    width: "100%",
    marginTop: theme.spacing(5),
    borderRadius: 12,
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(3),
    },
  },
  sideImg: {
    maxWidth: "200px",
    maxHeight: "200px",
    display: "block",
  },
  culturesSideImg: {
    position: "absolute",
    top: -20,
    right: "20px",
    maxWidth: "400px",
    maxHeight: "200px",
    opacity: 0.6,
    zIndex: 1,
  },

  // Culture Page Header Styles
  culturePageHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: theme.spacing(4),
    position: "relative",
    overflow: "hidden",
  },
  culturePageBanner: {
    background: "linear-gradient(135deg, #0A4FA4 0%, #041E3E 100%)",
    color: COLORS.WHITE,
    padding: theme.spacing(2.5, 3.75),
    borderRadius: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(3),
    maxHeight: 90,
    overflow: "visible",
    flex: 1,
  },
  culturePageIcon: {
    width: 180,
    height: 180,
    borderRadius: "50%",
    border: "2px solid white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #0A4FA4 0%, #041E3E 100%)",
    flexShrink: 0,
  },
  culturePageIconImg: {
    width: 60,
    height: 60,
    objectFit: "contain",
    filter: "brightness(0) invert(1)",
  },
  culturePageTitle: {
    margin: 0,
    fontSize: "2.5rem",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  culturePageSubtitle: {
    margin: "10px 0 0 0",
    fontSize: "1.1rem",
    opacity: 0.9,
  },

  // Card styles
  culturesCard: {
    background: COLORS.WHITE_GRAY,
    borderRadius: 12,
    boxShadow: SHADOWS.LARGE,
    padding: theme.spacing(4),
    marginBottom: theme.spacing(8),
    position: "relative",
    transition: "box-shadow 0.2s",
    minWidth: 0,
    maxWidth: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(2),
      marginBottom: theme.spacing(6),
    },
  },
  culturesCardTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: theme.spacing(2),
    fontSize: 32,
    [theme.breakpoints.down("md")]: {
      fontSize: 22,
      marginBottom: theme.spacing(1.5),
    },
  },
  culturesCardDesc: {
    fontSize: 20,
    fontWeight: 500,
    color: COLORS.DARK,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      marginBottom: theme.spacing(4),
    },
  },
  culturesCardImg: {
    width: "100%",
    borderRadius: 8,
    marginBottom: theme.spacing(2),
    marginTop: theme.spacing(1),
    display: "block",
  },
}));

export default useCulturesStyles;
