import { makeStyles } from 'tss-react/mui';
import type { Theme } from '@mui/material';

const useHomeStyles = makeStyles()((theme: Theme) => ({
  heroRoot: {
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    background: 'radial-gradient(circle at 60% 40%, #1758B4 0%, #0A264E 100%)',
    overflow: 'hidden',
    [theme.breakpoints.down('md')]: {
      minHeight: '50vh',
    },
  },
  heroLeftArrowBox: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 2,
  },
  heroArrowBtn: {
    width: 150,
    height: 150,
    borderRadius: '50%',
    border: '3px solid #FFFFFF7D',
    background: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'end',
    boxShadow: 'none',
    padding: 0,
    margin: 0,
    '&:hover': {
      background: 'rgba(4,99,238,0.08)',
      boxShadow: 'none',
    },
    [theme.breakpoints.down('md')]: {
      width: 40,
      height: 40,
    },
  },
  heroMain: {
    width: '100%',
    maxWidth: 1400,
    minHeight: '60vh',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    [theme.breakpoints.down('md')]: {
      minHeight: '40vh',
    },
  },
  heroImgBox: {
    flex: '0 0 60%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    [theme.breakpoints.down('md')]: {
      flex: '0 0 40%',
    },
  },
  heroImg: {
    marginTop: 10,
    marginLeft: 0,
    maxHeight: '80vh',
    maxWidth: '100%',
    objectFit: 'contain',
    display: 'block',
    [theme.breakpoints.down('md')]: {
      marginTop: 0,
      marginLeft: 8,
      maxWidth: '120%',
    },
  },
  heroTextBoxWrap: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
  },
  heroTextBox: {
    flex: '0 0 40%',
    display: 'flex',
    maxWidth: 600,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    height: '100%',
    paddingLeft: 48,
    color: '#fff',
    marginRight: 120,
    textAlign: 'right',
    fontFamily: 'DM Serif Display',
    [theme.breakpoints.down('md')]: {
      flex: '0 0 100%',
      maxWidth: 300,
      paddingLeft: 0,
      marginRight: 0,
    },
  },
  heroTitle: {
    fontWeight: 700,
    fontSize: 60,
    maxWidth: 430,
    lineHeight: '80px',
    textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
    letterSpacing: 0,
    marginTop: 0,
    marginRight: 24,
    [theme.breakpoints.down('md')]: {
      fontSize: 16,
      maxWidth: 210,
      lineHeight: '26px',
      letterSpacing: 1,
    },
  },
  heroTitleBlue: {
    color: '#2B7BFF',
    minWidth: 430,
    textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
    [theme.breakpoints.down('md')]: {
      minWidth: 0,
    },
  },
  heroRemoveIcon: {
    color: 'white',
    fontSize: 40,
    verticalAlign: 'middle',
    marginRight: 4,
    marginLeft: 4,
    [theme.breakpoints.down('md')]: {
      fontSize: 12,
    },
  },
  heroSubtitle: {
    fontWeight: 700,
    fontSize: 60,
    maxWidth: 430,
    lineHeight: '80px',
    textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
    letterSpacing: 0,
    [theme.breakpoints.down('md')]: {
      fontSize: 14,
      maxWidth: 120,
      lineHeight: '20px',
      letterSpacing: 1,
    },
  },
  heroBlueText: {
    color: '#2B7BFF',
    minWidth: 430,
    textShadow: '0px 4px 24px rgba(0, 0, 0, 0.18)',
  },
  heroRightArrowBox: {
    position: 'absolute',
    right: 0,
    top: '50%',
    transform: 'translate(50%, -50%)',
    zIndex: 2,
  },
  heroArrowBtnRight: {
    width: 150,
    height: 150,
    borderRadius: '50%',
    border: '3px solid #FFFFFF7D',
    background: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'start',
    boxShadow: 'none',
    padding: 0,
    margin: 0,
    '&:hover': {
      background: 'rgba(4,99,238,0.08)',
      boxShadow: 'none',
    },
    [theme.breakpoints.down('md')]: {
      width: 40,
      height: 40,
    },
  },
  heroArrowBackIcon: {
    fontSize: 32,
    marginRight: 32,
    color: theme.palette.primary.main,
    [theme.breakpoints.down('md')]: {
      fontSize: 8,
      marginRight: 8,
    },
  },
  heroArrowForwardIcon: {
    fontSize: 32,
    marginLeft: 32,
    color: theme.palette.primary.main,
    [theme.breakpoints.down('md')]: {
      fontSize: 8,
      marginLeft: 8,
    },
  },
  mottoCardRoot: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 300,
  },
  mottoCardHeadWrap: {
    position: 'relative',
    width: 240,
    height: 70,
    marginBottom: -24,
    zIndex: 2,
  },
  mottoCardHeadImg: {
    width: '100%',
    height: '100%',
  },
  mottoCardFishText: {
    position: 'absolute',
    top: '50%',
    left: '55%',
    transform: 'translate(-50%, -50%)',
    fontWeight: 600,
    color: '#0A4FA4',
    fontSize: 20,
    whiteSpace: 'nowrap',
  },
  mottoCardBox: {
    width: 320,
    height: 300,
    background: '#fff',
    borderRadius: 4,
    boxShadow: '0 4px 24px 0 #00000022',
    position: 'relative',
    overflow: 'hidden',
    padding: 0,
    marginBottom: theme.spacing(2),
  },
  mottoCardImgWrap: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 1,
  },
  mottoCardImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  mottoCardButtonWrap: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    zIndex: 3,
    background: 'rgba(10, 79, 164, 0.7)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 48,
  },
  mottoCardButton: {
    width: '100%',
    height: '100%',
    background: 'transparent',
    color: '#fff',
    fontWeight: 600,
    fontSize: 20,
    boxShadow: 'none',
    borderRadius: 0,
    '&:hover': {
      background: 'rgba(10, 79, 164, 0.85)',
    },
  },
  mottoCardTitle: {
    textAlign: 'center',
    fontWeight: 600,
    color: '#fff',
    maxWidth: 240,
    fontSize: 22,
    lineHeight: 1.2,
  },
  newsRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#fff',
    position: 'relative',
    [theme.breakpoints.down('md')]: {
      paddingTop: theme.spacing(2),
      paddingBottom: theme.spacing(2),
    },
  },
  newsFishesImg: {
    position: 'absolute',
    left: 0,
    top: -10,
    zIndex: 0,
    display: 'block',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  newsScrollWrap: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    marginTop: theme.spacing(6),
    gap: theme.spacing(8),
    width: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    [theme.breakpoints.down('md')]: {
      gap: '10%',
    },
  },
  newsScrollCenter: {
    justifyContent: 'center',
  },
  newsScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  newsOverflowBox: {
    marginLeft: "-5%",
  },
  newsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: 'border-box',
    flex: '0 0 auto',
    height: '100%',
    display: 'flex',
    alignItems: 'stretch',
  },
  newsCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  newsCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  newsCardInner: {
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: '100%',
  },
  newsCardRoot: {
    width: 370,
    height: 480,
    overflow: 'hidden',
    boxShadow: '0 2px 12px 0 #e0e7ef',
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 3,
    position: 'relative',
    [theme.breakpoints.down('md')]: {
      width:"100%"
    },
  },
  newsCardImgWrap: {
    position: 'relative',
    height: 400,
    width: '100%',
  },
  newsCardImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    objectPosition: 'center',
  },
  newsCardDateBox: {
    position: 'absolute',
    top: 12,
    left: 12,
    background: '#E0E2E3C2',
    paddingLeft: theme.spacing(1),
    paddingRight: theme.spacing(1),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    boxShadow: theme.shadows[1],
    textAlign: 'center',
  },
  newsCardDateDay: {
    fontWeight: 700,
    fontSize: 18,
    color: '#1976d2',
    lineHeight: 1,
  },
  newsCardDateMonth: {
    fontSize: 14,
    fontWeight: 700,
    color: '#1976d2',
    lineHeight: 1,
  },
  newsCardDateYear: {
    fontSize: 15,
    fontWeight: 700,
    marginTop: theme.spacing(0.5),
    color: '#1976d2',
    lineHeight: 1,
  },
  newsCardContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    background: '#F7FAFC',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    padding: theme.spacing(2),
  },
  newsCardTitle: {
    fontWeight: 700,
    fontSize: 22,
  },
  newsCardDesc: {
    fontSize: 14,
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    lineHeight: 1.25,
  },
  newsCardAuthor: {
    fontSize: 14,
  },
  newsCardAuthorLink: {
    color: '#1976d2',
    textDecoration: 'underline',
    fontWeight: 600,
  },
  newsCardAuthorSpan: {
    color: '#1976d2',
    fontWeight: 600,
  },
  newsCardFooter: {
    background: '#fff',
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    paddingBottom: theme.spacing(2),
    display: 'flex',
    justifyContent: 'flex-start',
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
  },
  newsCardButton: {
    color: '#1976d2',
    borderColor: '#1976d2',
    fontWeight: 600,
    borderRadius: 999,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    background: '#F7FAFC',
  },
  ourMottoRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: 'linear-gradient(180deg, #0A4FA4 0%, #041E3E 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    overflowY: 'visible',
    position: 'relative',
  },
  ourMottoTitleWrap: {
    position: 'absolute',
    top: -25,
    marginBottom: '10px',
    [theme.breakpoints.down('md')]: {
      top: -15,
    },
  },
  ourMottoScrollWrap: {
    display: 'flex',
    gap: theme.spacing(14),
    justifyContent: 'center',
    marginTop: theme.spacing(10),
    flexWrap: 'nowrap',
    overflowX: 'auto',
    overflowY: 'hidden',
    width: '100%',
    scrollbarWidth: 'none',
    marginBottom: theme.spacing(5),
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
  },
  ourMottoScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  ourMottoOverflowBoxLeft: {
    marginRight: theme.spacing(-8),
  },
  ourMottoOverflowBoxRight: {
    marginLeft: theme.spacing(-8),
  },
  aboutUsRoot: {
    width: '100%',
    background: '#fff',
    boxShadow: '0 0 0 2px #e0e7ef',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
    minHeight: 380,
    paddingTop: 0,
    flexDirection: 'row',
    [theme.breakpoints.down('md')]: {
      gap: 2,
      paddingTop: theme.spacing(6),
      flexDirection: 'column',
    },
  },
  aboutUsLeft: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    height: '100%',
    padding: theme.spacing(4),
    [theme.breakpoints.down('md')]: {
      alignItems: 'center',
      padding: theme.spacing(1.5),
    },
  },
  aboutUsTitleWrap: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    gap: theme.spacing(3),
    marginBottom: theme.spacing(3),
    alignItems: 'center',
    justifyContent: 'flex-start',
    [theme.breakpoints.down('md')]: {
      gap: theme.spacing(1.5),
      marginBottom: theme.spacing(2),
    },
  },
  aboutUsTitle1: {
    paddingLeft: theme.spacing(6),
    paddingRight: theme.spacing(6),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    borderRadius: 999,
    background: 'linear-gradient(180deg, #0A4FA4 0%, #041E3E 100%)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 40,
    boxShadow: '0 2px 8px 0 #0A4FA422',
    border: '2px solid #0A4FA4',
    transition: 'all 0.2s',
    textAlign: 'center',
    minWidth: 'unset',
    [theme.breakpoints.down('md')]: {
      fontSize: 16,
      minWidth: 90,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
    },
  },
  aboutUsTitle2: {
    paddingLeft: theme.spacing(6),
    paddingRight: theme.spacing(6),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    borderRadius: 999,
    background: '#fff',
    color: '#0A4FA4',
    fontWeight: 700,
    fontSize: 40,
    border: '2px solid #e0e7ef',
    boxShadow: '0 2px 10px 0 #0463EE66',
    transition: 'all 0.2s',
    textAlign: 'center',
    minWidth: 'unset',
    [theme.breakpoints.down('md')]: {
      fontSize: 16,
      minWidth: 90,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
    },
  },
  aboutUsDesc: {
    color: theme.palette.primary.dark,
    padding: theme.spacing(2),
    letterSpacing: '0.5px',
    fontSize: 20,
    marginBottom: theme.spacing(2),
    maxWidth: '90%',
    lineHeight: 1.6,
    fontWeight: 400,
    paddingLeft: 0,
    paddingRight: 0,
    [theme.breakpoints.down('md')]: {
      fontSize: 15,
      maxWidth: '98%',
      marginBottom: theme.spacing(1.5),
      padding: theme.spacing(0.5),
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  aboutUsBtn: {
    color: theme.palette.primary.main,
    marginLeft: 0,
    marginRight: 0,
    borderColor: '#0A4FA4',
    fontWeight: 400,
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    fontSize: 14,
    borderRadius: 999,
    width: 'fit-content',
    alignSelf: 'flex-start',
    marginTop: 0,
    '&:hover': {
      borderColor: '#0A4FA4',
      background: '#eaf2fb',
    },
    [theme.breakpoints.down('md')]: {
      fontSize: 10,
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
      marginTop: theme.spacing(1),
    },
  },
  aboutUsRight: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  aboutUsImg: {
    width: '100%',
    borderRadius: 5,
    objectFit: 'cover',
    marginTop: 0,
    maxWidth: 540,
    [theme.breakpoints.down('md')]: {
      width: '90%',
      maxWidth: 340,
      marginTop: theme.spacing(2),
      marginBottom:50,
    },
  },
  aboutUsVideoWrap: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'visible',
  },
  aboutUsVideo: {
    width: '100%',
    height: '100vh',
    objectFit: 'cover',
    top: 0,
    left: 0,
    minWidth: '100%',
    minHeight: '100%',
  },
  contactRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#fff',
  },
  contactMain: {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: theme.spacing(6),
  },
  contactImgWrap: {
    width: '95%',
    height: 300,
    display: 'flex',
    justifyContent: 'center',
    marginBottom: theme.spacing(2),
    [theme.breakpoints.up('md')]: {
      display: 'none',
    }
  },
  contactImg: {
    width: '100%',
    objectFit: 'cover',
  },
  contactFormWrap: {
    width: '80%',
    marginTop: 0,
    maxWidth: 420,
    borderRadius: 12,
    boxShadow: '0 4px 16px 0 #0A4FA422',
    background: 'linear-gradient(180deg, #0A4FA4 0%, #041E3E 100%)',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
    alignItems: 'center',
    padding: theme.spacing(4),
    [theme.breakpoints.down('md')]: {
      marginTop: theme.spacing(4),
    },
  },
  contactFieldWrap: {
    width: '100%',
  },
  contactLabel: {
    color: '#fff',
    fontWeight: 500,
    marginBottom: theme.spacing(1),
  },
  contactTextField: {
    background: '#fff',
    borderRadius: theme.shape.borderRadius,
    '& input': {
      color: '#222',
    },
    '& textarea': {
      color: '#222',
    },
  },
  contactButton: {
    marginTop: theme.spacing(2),
    background: '#fff',
    color: '#0A4FA4',
    fontWeight: 600,
    borderRadius: 999,
    paddingLeft: theme.spacing(5),
    paddingRight: theme.spacing(5),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    boxShadow: 'none',
    textTransform: 'none',
    '&:hover': {
      background: '#eaf2fb',
    },
  },
  ourProjectsRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#f8fafc',
  },
  ourProjectsInner: {
    paddingTop: theme.spacing(4),
    width: '100%',
  },
  ourProjectsCategories: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    background: '#fff',
    borderRadius: 3,
    maxWidth: '92%',
    margin: 'auto',
    boxShadow: '0 2px 10px 0 #0463EE66',
    position: 'relative',
    minHeight: 56,
    paddingLeft: theme.spacing(2),
    overflowX: 'auto',
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
  },
  ourProjectsCategory: {
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(1.2),
    paddingBottom: theme.spacing(1.2),
    borderRadius: 2,
    fontWeight: 500,
    fontSize: 20,
    color: '#0A4FA4',
    background: 'transparent',
    boxShadow: 'none',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s',
  },
  ourProjectsCategoryActive: {
    color: '#fff',
    background: '#0A4FA4',
    boxShadow: '0 2px 10px 0 #0463EE33',
  },
  ourProjectsScroll: {
    marginTop: theme.spacing(6),
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: theme.spacing(3),
    justifyContent: 'center',
    alignItems: 'stretch',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
  },
  ourProjectsScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  ourProjectsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: 'border-box',
    height: '100%',
    display: 'flex',
    alignItems: 'stretch',
  },
  projectCardRoot: {
    width: 350,
    height: 600,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    position: 'relative',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
  },
  projectCardHighlight: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(10,79,164,0.75)',
    color: '#fff',
    padding: theme.spacing(3),
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    zIndex: 2,
  },
  projectCardHighlightTitle: {
    fontWeight: 700,
    marginBottom: theme.spacing(4),
    fontSize: 20,
  },
  projectCardHighlightDesc: {
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 2,
  },
  projectCardNormal: {
    width: '100%',
    background: 'linear-gradient(180deg, rgba(10,79,164,0.85) 40%, rgba(4,30,62,0.75) 100%)',
    color: '#fff',
    padding: theme.spacing(2),
    zIndex: 2,
  },
  projectCardNormalTitle: {
    fontWeight: 700,
    fontSize: 16,
  },
  projectCardNormalDesc: {
    fontSize: 14,
    fontWeight: 400,
    marginTop: theme.spacing(0.5),
  },
  partnersRoot: {
    position: 'relative',
    paddingTop: theme.spacing(4),
    background: '#fff',
    width: '100%',
    left: '50%',
    right: '50%',
    marginLeft: '-50vw',
    marginRight: '-50vw',
    paddingLeft: 0,
    paddingRight: 0,
  },
  partnersInner: {
    width: '100%',
    margin: 'auto',
    position: 'relative',
    zIndex: 1,
    background: '#fff',
  },
  partnersScroll: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    gap: theme.spacing(4),
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: theme.spacing(6),
    marginBottom: theme.spacing(16),
    boxShadow: '0 2px 10px 0 #0463EE66',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
  },
  partnersScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  partnersCard: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    minWidth: 120,
    maxWidth: 180,
  },
  partnersImg: {
    width: '100%',
    objectFit: 'contain',
  },
  partnersBgImg: {
    position: 'absolute',
    right: 60,
    top: 55,
    height: 140,
    opacity: 0.5,
    zIndex: 0,
    pointerEvents: 'none',
    display: 'block',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  pricingRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#fff',
    position: 'relative',
  },
  pricingTopImg: {
    position: 'absolute',
    top: -45,
    right: 100,
    width: 400,
    zIndex: 0,
    display: 'block',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  pricingScroll: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginTop: theme.spacing(10),
    gap: theme.spacing(10),
    width: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    position: 'relative',
    zIndex: 1,
    '&::-webkit-scrollbar': { display: 'none' },
  },
  pricingScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  pricingCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: 'border-box',
    flex: '0 0 auto',
    height: '100%',
    display: 'flex',
    alignItems: 'stretch',
  },
  pricingCardInner: {
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: '100%',
  },
  pricingCardRoot: {
    width: 320,
    boxShadow: '0 2px 10px 0 #0463EE66',
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: theme.spacing(3),
    borderTopLeftRadius: '50% 25%',
    borderTopRightRadius: '50% 25%',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    position: 'relative',
    border: '2px solid #E0E7EF',
  },
  pricingCardImgWrap: {
    width: 280,
    height: 280,
    borderRadius: '50%',
    background: '#0A4FA4',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing(2),
  },
  pricingCardImg: {
    width: 200,
    height: 200,
    objectFit: 'contain',
  },
  pricingCardTitle: {
    fontWeight: 700,
    color: '#0A4FA4',
    fontSize: 24,
    marginBottom: theme.spacing(2),
  },
  pricingCardFeatures: {
    color: '#222',
    fontSize: 15,
    paddingRight: theme.spacing(2),
    marginBottom: theme.spacing(3),
    listStyle: 'disc',
    textAlign: 'left',
    width: '100%',
  },
  pricingCardFeatureItem: {
    marginBottom: 8,
    fontSize: 18,
  },
  pricingCardButton: {
    color: theme.palette.primary.main,
    borderColor: theme.palette.primary.main,
    fontWeight: 600,
    borderRadius: 999,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    background: '#fff',
  },
  sectionTitleRoot: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing(3),
  },
  sectionTitleInner: {
    borderRadius: 10,
    backgroundColor: 'white',
    boxShadow: '0 2px 10px 0 #0463EE66',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    border: '3px #0463EE',
  },
  sectionTitleImg: {
    height: 12,
    transform: 'scaleX(-1)',
    [theme.breakpoints.down('md')]: {
      height: 4,
    },
  },
  sectionTitleText: {
    color: theme.palette.primary.main,
    fontSize: 40,
    fontWeight: 400,
    fontFamily: 'DM Serif Display, serif',
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    [theme.breakpoints.down('md')]: {
      fontSize: 20,
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
    },
  },
  teamRoot: {
    width: '100%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#fff',
    position: 'relative',
    overflow: 'hidden',
  },
  teamFishesImg: {
    position: 'absolute',
    top: 0,
    right: 40,
    width: 500,
    zIndex: 1,
    display: 'block',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  teamTabs: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing(2),
    marginTop: theme.spacing(4),
    marginBottom: theme.spacing(2),
  },
  teamTabActive: {
    color: '#1976d2',
    fontWeight: 500,
    fontSize: 24,
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  teamTabDivider: {
    marginLeft: theme.spacing(2),
    marginRight: theme.spacing(2),
    color: '#bbb',
    fontSize: 22,
  },
  teamTabInactive: {
    color: '#222',
    fontWeight: 500,
    fontSize: 24,
    cursor: 'pointer',
  },
  teamScrollWrap: {
    width: '100%',
    position: 'relative',
    height: '70vh',
    maxHeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: theme.spacing(4),
    zIndex: 2,
  },
  teamBgImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 0,
  },
  teamCardsScroll: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: theme.spacing(12),
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'relative',
    zIndex: 2,
    marginTop: theme.spacing(4),
    width: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
  },
  teamCardsScrollFlexStart: {
    justifyContent: 'flex-start',
    gap: theme.spacing(5),
  },
  teamCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: 'border-box',
    flex: '0 0 auto',
    height: '100%',
    display: 'flex',
    alignItems: 'stretch',
    marginLeft: 0,
    marginRight: 0,
  },
  teamCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  teamCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  teamCardInner: {
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: '100%',
  },
  teamCardRoot: {
    width: 262,
    background: '#fff',
    borderRadius: 2,
    boxShadow: '0 2px 10px 0 #0463EE66',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    marginTop: theme.spacing(10),
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(18),
    paddingBottom: theme.spacing(2),
    border: '2px solid #E0E7EF',
  },
  teamCardAvatar: {
    width: 230,
    height: 230,
    position: 'absolute',
    top: -85,
    left: '50%',
    transform: 'translateX(-50%)',
    background: '#fff',
  },
  teamCardRole: {
    color: theme.palette.primary.main,
    fontWeight: 500,
    fontSize: 18,
    textAlign: 'center',
    width: '100%',
    marginTop: theme.spacing(1),
  },
  teamCardInfoRow: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    marginTop: theme.spacing(1),
  },
  teamCardInfoCol: {
    display: 'flex',
    marginTop: theme.spacing(0.5),
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  teamCardName: {
    fontWeight: 900,
    color: '#222',
    fontSize: 25,
    textAlign: 'left',
  },
  teamCardLocation: {
    color: '#222',
    fontSize: 16,
    textAlign: 'left',
    marginBottom: 0,
  },
  teamCardButton: {
    minWidth: 0,
    width: 36,
    height: 36,
    borderRadius: '50%',
    background: theme.palette.primary.main,
    color: '#fff',
    boxShadow: theme.shadows[1],
    padding: 0,
  },
  teamCardArrow: {
    fontSize: 22,
  },
  testimonialsRoot: {
    width: '100%',
    position: 'relative',
    left: '50%',
    right: '50%',
    marginLeft: '-50%',
    marginRight: '-50v%',
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: '#fff',
  },
  testimonialsScroll: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginTop: theme.spacing(6),
    width: '100%',
    gap: theme.spacing(5),
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
  },
  testimonialsScrollFlexStart: {
    justifyContent: 'flex-start',
  },
  testimonialsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: 'border-box',
    flex: '0 0 auto',
    height: '100%',
    display: 'flex',
    alignItems: 'stretch',
    marginLeft: 0,
    marginRight: 0,
  },
  testimonialsCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  testimonialsCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  testimonialCardRoot: {
    flex: 1,
    minWidth: 320,
    maxWidth: 500,
    minHeight: 280,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
  },
  testimonialCardCloudWrap: {
    width: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  testimonialCardCloudImg: {
    width: '100%',
    height: 200,
    display: 'block',
  },
  testimonialCardQuote: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '90%',
    height: 200,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: theme.palette.primary.main,
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 1.3,
    paddingTop: theme.spacing(0.25),
    paddingLeft: theme.spacing(2),
    margin: 'auto',
    marginTop: -14,
  },
  testimonialCardAvatar: {
    width: 64,
    height: 64,
    position: 'absolute',
    left: '10%',
    bottom: -24,
    transform: 'translateX(-50%)',
    border: '3px solid #fff',
    boxShadow: theme.shadows[2],
    background: '#fff',
  },
  testimonialCardInfo: {
    position: 'absolute',
    left: '10%',
    top: 220,
    transform: 'translateX(-50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 120,
    marginTop: theme.spacing(1),
  },
  testimonialCardName: {
    fontWeight: 600,
    color: '#222',
  },
  testimonialCardRole: {
    fontSize: 14,
    color: theme.palette.primary.main,
  },
}));

export default useHomeStyles; 