import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, SHADOWS, FONTS } from "../Shared/styles";

const useHomeStyles = makeStyles()((theme: Theme) => ({
  heroRoot: {
    minHeight: "100vh",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    background: `radial-gradient(circle at 60% 40%, ${COLORS.HERO_BLUE} 0%, ${COLORS.DARK_BLUE} 100%)`,
    overflow: "hidden",
    [theme.breakpoints.down("md")]: {
      minHeight: "40vh",
    },
  },
  heroLeftArrowBox: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 2,
  },
  heroArrowBtn: {
    width: 150,
    height: 150,
    borderRadius: "50%",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "end",
    boxShadow: "none",
    padding: 0,
    margin: 0,
    "&:hover": {
      boxShadow: "none",
    },
    [theme.breakpoints.down("md")]: {
      width: 40,
      height: 40,
    },
  },
  heroMainTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: "#57B6FF",
    fontSize: "6rem",
    marginBottom: theme.spacing(1),
    [theme.breakpoints.down("lg")]: {
      fontSize: "4rem",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "2rem",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "1.5rem",
    },
  },
  heroSubTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.WHITE,
    fontSize: "3.5rem",
    textShadow: "0 4px 10px #00000080",
    [theme.breakpoints.down("lg")]: {
      fontSize: "2.5rem",
    },
    [theme.breakpoints.down("md")]: {
      fontSize: "1.75rem",
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "1.25rem",
    },
  },
  heroMain: {
    width: "100%",
    maxWidth: 1400,
    minHeight: "60vh",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    marginTop: "100px",
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
    },
  },
  heroImgBox: {
    flex: "0 0 60%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    [theme.breakpoints.down("md")]: {
      flex: "0 0 40%",
    },
  },
  heroImg: {
    marginTop: 10,
    marginLeft: 0,
    maxHeight: "80vh",
    maxWidth: "100%",
    objectFit: "contain",
    display: "block",
    [theme.breakpoints.down("md")]: {
      marginTop: 0,
      marginLeft: 8,
      maxWidth: "120%",
    },
  },
  heroTextBoxWrap: {
    display: "flex",
    justifyContent: "flex-end",
    width: "100%",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    marginTop: -80,
    [theme.breakpoints.down("md")]: {
      marginTop: -40,
    },
  },
  heroTextBox: {
    flex: "0 0 100%",
    display: "flex",
    maxWidth: 600,
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "center",
    height: "100%",
    paddingLeft: 48,
    color: COLORS.WHITE,
    marginRight: 70,
    textAlign: "left",
    fontFamily: "DM Serif Display",
    [theme.breakpoints.down("lg")]: {
      marginRight: 80,
    },
    [theme.breakpoints.down("md")]: {
      marginRight: 0,
      maxWidth: 300,
      paddingRight: 40,
    },
  },
  heroTitle: {
    fontWeight: 700,
    fontSize: 60,
    maxWidth: 430,
    lineHeight: "80px",
    textShadow: SHADOWS.DARK_TEXT,
    letterSpacing: 0,
    marginTop: 0,
    marginRight: 24,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      maxWidth: 210,
      lineHeight: "26px",
      letterSpacing: 1,
    },
  },
  heroTitleBlue: {
    color: COLORS.LIGHT_BLUE,
    minWidth: 430,
    textShadow: SHADOWS.DARK_TEXT,
    [theme.breakpoints.down("md")]: {
      minWidth: 0,
    },
  },
  heroRemoveIcon: {
    color: COLORS.WHITE,
    fontSize: 40,
    verticalAlign: "middle",
    marginRight: 4,
    marginLeft: 4,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  heroSubtitle: {
    fontWeight: 700,
    fontSize: 60,
    maxWidth: 430,
    lineHeight: "80px",
    textShadow: SHADOWS.DARK_TEXT,
    letterSpacing: 0,

    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      maxWidth: 120,
      lineHeight: "20px",
      letterSpacing: 1,
    },
  },
  heroBlueText: {
    color: COLORS.LIGHT_BLUE,
    minWidth: 430,
    textShadow: SHADOWS.DARK_TEXT,
  },
  heroRightArrowBox: {
    position: "absolute",
    right: 0,
    top: "50%",
    transform: "translate(50%, -50%)",
    zIndex: 2,
  },
  heroArrowBtnRight: {
    width: 150,
    height: 150,
    borderRadius: "50%",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    boxShadow: "none",
    padding: 0,
    margin: 0,
    "&:hover": {
      boxShadow: "none",
    },
    [theme.breakpoints.down("md")]: {
      width: 40,
      height: 40,
    },
  },
  heroArrowBackIcon: {
    fontSize: 32,
    marginRight: 32,
    color: COLORS.WHITE,
    [theme.breakpoints.down("md")]: {
      fontSize: 8,
      marginRight: 8,
    },
  },
  heroArrowForwardIcon: {
    fontSize: 32,
    marginLeft: 32,
    color: COLORS.WHITE,
    [theme.breakpoints.down("md")]: {
      fontSize: 8,
      marginLeft: 8,
    },
  },
  mottoCardRoot: {
    textAlign: "center",
    width: 300,
  },
  mottoCardHeadWrap: {
    position: "relative",
    width: 240,
    height: 70,
    marginBottom: -46,
    zIndex: 2,
  },
  mottoCardHeadImg: {
    width: "100%",
    height: "100%",
  },
  mottoCardFishText: {
    position: "absolute",
    top: "50%",
    left: "55%",
    transform: "translate(-50%, -50%)",
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
    fontSize: 20,
    whiteSpace: "nowrap",
  },
  mottoCardBox: {
    width: 320,
    height: 300,
    background: COLORS.WHITE,
    borderRadius: 4,
    boxShadow: SHADOWS.DARK_CARD,
    position: "relative",
    overflow: "hidden",
    padding: 0,
    marginBottom: theme.spacing(2),
  },
  mottoCardImgWrap: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 1,
  },
  mottoCardImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  mottoCardButtonWrap: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "100%",
    zIndex: 3,
    background: COLORS.TRANSPARENT_DARK_BLUE,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 48,
  },
  mottoCardButton: {
    width: "100%",
    height: "100%",
    background: "transparent",
    color: COLORS.WHITE,
    fontWeight: 600,
    fontSize: 20,
    boxShadow: "none",
    borderRadius: 0,
    "&:hover": {
      background: COLORS.DARKER_BLUE,
    },
  },
  mottoCardTitle: {
    textAlign: "center",
    fontWeight: 600,
    color: COLORS.WHITE,
    maxWidth: 240,
    fontSize: 22,
    lineHeight: 1.2,
  },
  newsRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: COLORS.WHITE,
    position: "relative",
    [theme.breakpoints.down("md")]: {
      paddingTop: theme.spacing(2),
      paddingBottom: theme.spacing(2),
    },
  },
  newsFishesImg: {
    position: "absolute",
    left: 0,
    top: -10,
    zIndex: 0,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  newsScrollWrap: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "stretch",
    marginTop: theme.spacing(6),
    gap: theme.spacing(8),
    width: "100%",
    maxWidth: 1250,
    marginLeft: "auto",
    marginRight: "auto",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    [theme.breakpoints.down("md")]: {
      gap: "10%",
    },
  },
  newsScrollCenter: {
    justifyContent: "center",
  },
  newsScrollFlexStart: {
    justifyContent: "flex-start",
  },
  newsOverflowBox: {
    marginLeft: "-5%",
  },
  newsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: "border-box",
    flex: "0 0 auto",
    height: "100%",
    display: "flex",
    alignItems: "stretch",
    marginBottom: theme.spacing(2),
  },
  newsCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  newsCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  newsCardInner: {
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    height: "100%",
  },
  newsCardRoot: {
    width: 370,
    height: 480,
    overflow: "hidden",
    boxShadow: SHADOWS.CARD,
    background: COLORS.WHITE,
    display: "flex",
    flexDirection: "column",
    borderRadius: 3,
    position: "relative",
    [theme.breakpoints.down("md")]: {
      width: "100%",
    },
  },
  newsCardImgWrap: {
    position: "relative",
    height: 400,
    width: "100%",
  },
  newsCardImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center",
  },
  newsCardDateBox: {
    position: "absolute",
    top: 12,
    left: 12,
    background: COLORS.TRANSPARENT_GRAY,
    paddingLeft: theme.spacing(1),
    paddingRight: theme.spacing(1),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    boxShadow: SHADOWS.SUBTLE,
    textAlign: "center",
  },
  newsCardDateDay: {
    fontWeight: 700,
    fontSize: 18,
    color: COLORS.LIGHT_BLUE,
    lineHeight: 1,
  },
  newsCardDateMonth: {
    fontSize: 14,
    fontWeight: 700,
    color: COLORS.LIGHT_BLUE,
    lineHeight: 1,
  },
  newsCardDateYear: {
    fontSize: 15,
    fontWeight: 700,
    marginTop: theme.spacing(0.5),
    color: COLORS.LIGHT_BLUE,
    lineHeight: 1,
  },
  newsCardContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    background: COLORS.BLUE_GRAY,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    padding: theme.spacing(2),
  },
  newsCardTitle: {
    fontWeight: 700,
    fontSize: 22,
  },
  newsCardDesc: {
    fontSize: 14,
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    lineHeight: 1.25,
  },
  newsCardAuthor: {
    fontSize: 14,
  },
  newsCardAuthorLink: {
    color: COLORS.LIGHT_BLUE,
    textDecoration: "underline",
    fontWeight: 600,
  },
  newsCardAuthorSpan: {
    color: COLORS.LIGHT_BLUE,
    fontWeight: 600,
  },
  newsCardFooter: {
    background: COLORS.WHITE,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    paddingBottom: theme.spacing(2),
    display: "flex",
    justifyContent: "flex-start",
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
  },
  newsCardButton: {
    color: COLORS.LIGHT_BLUE,
    borderColor: COLORS.LIGHT_BLUE,
    fontWeight: 600,
    borderRadius: 999,
    textTransform: "capitalize",
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    background: COLORS.BLUE_GRAY,
  },
  ourMottoRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    overflowY: "visible",
    position: "relative",
  },
  ourMottoTitleWrap: {
    position: "absolute",
    top: -25,
    marginBottom: "10px",
    [theme.breakpoints.down("md")]: {
      top: -15,
    },
  },
  ourMottoScrollWrap: {
    display: "flex",
    gap: theme.spacing(12),
    justifyContent: "center",
    width: "100%",
    maxWidth: 1200,
    margin: "auto",
    marginTop: theme.spacing(10),
    flexWrap: "nowrap",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    marginBottom: theme.spacing(5),
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  ourMottoScrollFlexStart: {
    justifyContent: "flex-start",
  },
  ourMottoOverflowBoxLeft: {
    marginRight: theme.spacing(-8),
  },
  ourMottoOverflowBoxRight: {
    marginLeft: theme.spacing(-8),
  },
  aboutUsRoot: {
    width: "100%",
    background: COLORS.WHITE,
    boxShadow: `0 0 0 2px ${COLORS.LIGHT_GRAY}`,
    minHeight: 380,
    paddingTop: 0,
    placeContent: "center",
    placeItems: "center",
    [theme.breakpoints.down("md")]: {
      paddingTop: theme.spacing(6),
    },
  },
  aboutUsLeft: {
    padding: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(1.5),
    },
  },
  aboutUsTitleWrap: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: theme.spacing(2),
    marginBottom: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginBottom: theme.spacing(2),
      justifyContent: "center",
      textAlign: "center",
    },
  },
  aboutUsTitle1: {
    paddingLeft: theme.spacing(6),
    paddingRight: theme.spacing(6),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    borderRadius: 999,
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    color: COLORS.WHITE,
    fontWeight: 700,
    fontSize: 40,
    boxShadow: SHADOWS.DARK_CARD,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    transition: "all 0.2s",
    textAlign: "center",
    minWidth: "unset",
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      minWidth: 90,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
    },
  },
  aboutUsTitle2: {
    paddingLeft: theme.spacing(6),
    paddingRight: theme.spacing(6),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    borderRadius: 999,
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    fontWeight: 700,
    fontSize: 40,
    border: `2px solid ${COLORS.LIGHT_GRAY}`,
    boxShadow: SHADOWS.CARD,
    transition: "all 0.2s",
    textAlign: "center",
    minWidth: "unset",
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      minWidth: 90,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
    },
  },
  aboutUsDesc: {
    color: COLORS.PRIMARY_BLUE,
    padding: theme.spacing(2),
    letterSpacing: "0.5px",
    fontSize: 20,
    marginBottom: theme.spacing(2),
    maxWidth: "90%",
    lineHeight: 1.6,
    fontWeight: 400,
    paddingLeft: theme.spacing(0.5),
    paddingRight: 0,
    [theme.breakpoints.down("md")]: {
      fontSize: 15,
      maxWidth: "98%",
      marginBottom: theme.spacing(1.5),
      padding: theme.spacing(0.5),
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  aboutUsBtn: {
    color: theme.palette.primary.main,
    marginLeft: 0,
    marginRight: 0,
    borderColor: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    textTransform: "none",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    fontSize: 14,
    borderRadius: 999,
    width: "fit-content",
    marginTop: 0,
    "&:hover": {
      borderColor: COLORS.PRIMARY_BLUE,
      background: COLORS.BLUE_GRAY,
    },
    [theme.breakpoints.down("md")]: {
      fontSize: 10,
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
      marginTop: theme.spacing(1),
    },
  },
  aboutUsRight: {
    width: "100%",
    textAlign: "center",
  },
  aboutUsImg: {
    display: "block",
    margin: "auto",
    width: "100%",
    borderRadius: 5,
    objectFit: "cover",
    maxWidth: 540,
    [theme.breakpoints.down("md")]: {
      width: "90%",
      maxWidth: 340,
      marginTop: theme.spacing(2),
      marginBottom: 50,
    },
  },
  aboutUsVideoWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
    overflow: "visible",
  },
  aboutUsVideo: {
    width: "100%",
    height: "100vh",
    objectFit: "cover",
    top: 0,
    left: 0,
    minWidth: "100%",
    minHeight: "100%",
  },
  contactRoot: {
    width: "90%",
    paddingTop: theme.spacing(2),
    paddingBottom: theme.spacing(2),
    background: COLORS.PRIMARY_BLUE,
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    maxWidth: 1200,
    margin: "auto",
    marginTop: theme.spacing(8),
    marginBottom: theme.spacing(8),
    [theme.breakpoints.down("md")]: {
      paddingTop: theme.spacing(2),
      paddingBottom: theme.spacing(2),
      marginTop: theme.spacing(4),
      marginBottom: theme.spacing(4),
    },
  },
  contactMain: {
    // [theme.breakpoints.down("md")]: {
    //   flexDirection: "column",
    // },
  },
  contactImgWrap: {
    flex: "0 0 50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    [theme.breakpoints.down("md")]: {
      order: 1,
      flex: "0 0 100%",
    },
  },
  contactImg: {
    width: "100%",
    maxWidth: 400,
    height: "auto",
    objectFit: "contain",
    [theme.breakpoints.down("md")]: {
      padding: "10px 0 0 0",
    },
  },
  contactFormWrap: {
    flex: "0 0 50%",
    padding: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      order: 2,
      flex: "0 0 100%",
      padding: theme.spacing(2),
    },
  },
  contactFieldWrap: {
    marginBottom: theme.spacing(1),
    [theme.breakpoints.down("md")]: {
      marginBottom: theme.spacing(0.5),
    },
  },
  contactLabel: {
    color: COLORS.WHITE,
    marginBottom: theme.spacing(0.5),
    fontSize: 18,
  },
  contactTextField: {
    "& .MuiOutlinedInput-root": {
      borderRadius: 8,
      backgroundColor: COLORS.WHITE,
      padding: "2px 0px",
      "& fieldset": {
        borderColor: COLORS.WHITE,
      },
      "&:hover fieldset": {
        borderColor: COLORS.WHITE,
      },
      "&.Mui-focused fieldset": {
        borderColor: COLORS.WHITE,
      },
    },
    "& .MuiInputBase-input": {
      color: COLORS.DARK,
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
      paddingRight: theme.spacing(2),
      paddingLeft: theme.spacing(2),
    },
    "& .MuiInputBase-input::placeholder": {
      color: COLORS.GRAY,
      opacity: 1,
    },
  },
  fullWidth: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    [theme.breakpoints.down("md")]: {
      justifyContent: "flex-start",
      width: "fit-content",
    },
  },
  contactButton: {
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    width: "90%",
    maxWidth: "300px",
    margin: "auto",
    fontWeight: 600,
    borderRadius: 999,
    padding: theme.spacing(1, 5),
    marginTop: theme.spacing(2),
    textTransform: "none",
    "&:hover": {
      background: COLORS.LIGHT_BLUE,
      color: COLORS.WHITE,
    },
    [theme.breakpoints.down("md")]: {
      width: "fit-content",
    },
  },
  ourProjectsRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: COLORS.BLUE_GRAY,
  },
  ourProjectsInner: {
    paddingTop: theme.spacing(4),
    width: "100%",
  },
  ourProjectsCategories: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    background: COLORS.WHITE,
    borderRadius: 7,
    width: "92%",
    maxWidth: 1340,
    margin: "auto",
    boxShadow: SHADOWS.CARD,
    position: "relative",
    minHeight: 56,
    paddingLeft: theme.spacing(2),
    overflowX: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": { display: "none" },
  },
  ourProjectsCategory: {
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 7,
    fontWeight: 500,
    fontSize: 20,
    color: COLORS.SECONDARY_BLUE,
    background: "transparent",
    boxShadow: "none",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.2s",
  },
  ourProjectsCategoryActive: {
    color: COLORS.WHITE,
    background: COLORS.PRIMARY_BLUE,
    boxShadow: SHADOWS.LIGHT_CARD,
  },
  ourProjectsScroll: {
    width: "100%",
    maxWidth: 1400,
    margin: "auto",
    marginTop: theme.spacing(6),
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: theme.spacing(3),
    justifyContent: "center",
    alignItems: "stretch",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": { display: "none" },
  },
  ourProjectsScrollFlexStart: {
    justifyContent: "flex-start",
  },
  ourProjectsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: "border-box",
    height: "100%",
    display: "flex",
    alignItems: "stretch",
  },
  projectCardRoot: {
    width: 350,
    height: 600,
    overflow: "hidden",
    position: "relative",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
  },
  projectCardHighlight: {
    position: "absolute",
    inset: 0,
    background: COLORS.TRANSPARENT_DARK_BLUE,
    color: COLORS.WHITE,
    padding: theme.spacing(3),
    zIndex: 2,
  },
  projectCardHighlightTitle: {
    fontWeight: 700,
    marginBottom: theme.spacing(4),
    fontSize: 20,
  },
  projectCardHighlightDesc: {
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 2,
  },
  projectCardNormal: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 150,
    background: `linear-gradient(180deg, ${COLORS.DARKER_BLUE} 40%, ${COLORS.PRIMARY_DARK}75 100%)`,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    zIndex: 2,
    "&:not(.projectCardHighlight)": {
      background: `linear-gradient(180deg, ${COLORS.DARKER_BLUE} 40%, ${COLORS.PRIMARY_DARK}75 100%)`,
    },
  },
  projectCardNormalTitle: {
    fontWeight: 700,
    fontSize: 16,
  },
  projectCardNormalDesc: {
    fontSize: 14,
    fontWeight: 400,
    marginTop: theme.spacing(0.5),
  },
  partnersRoot: {
    position: "relative",
    paddingTop: theme.spacing(4),
    background: COLORS.WHITE,
    width: "100%",
    left: "50%",
    right: "50%",
    marginLeft: "-50vw",
    marginRight: "-50vw",
    paddingLeft: 0,
    paddingRight: 0,
  },
  partnersInner: {
    width: "100%",
    margin: "20px auto",
    position: "relative",
    zIndex: 1,
  },
  partnersScroll: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    width: "100%",
    maxWidth: 1400,
    margin: "auto",
    gap: theme.spacing(6),
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: theme.spacing(6),
    marginBottom: theme.spacing(16),
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": { display: "none" },
  },
  partnersScrollFlexStart: {
    justifyContent: "flex-start",
  },
  partnersCard: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    paddingTop: theme.spacing(1.5),
    paddingBottom: theme.spacing(1.5),
    minWidth: 120,
    maxWidth: 180,
  },
  partnersImg: {
    width: "150px",
    height: "150px",
    objectFit: "contain",
  },
  partnersBgImg: {
    position: "absolute",
    right: 60,
    top: 55,
    height: 140,
    opacity: 0.5,
    zIndex: 0,
    pointerEvents: "none",
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  pricingRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: COLORS.WHITE,
    position: "relative",
  },
  pricingTopImg: {
    position: "absolute",
    top: -45,
    right: 100,
    width: 400,
    zIndex: 0,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  pricingScroll: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "stretch",
    marginTop: theme.spacing(10),
    gap: theme.spacing(14),
    width: "100%",
    maxWidth: 1400,
    margin: "auto",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    position: "relative",
    zIndex: 1,
    "&::-webkit-scrollbar": { display: "none" },
    [theme.breakpoints.down("md")]: {
      gap: theme.spacing(10),
    },
  },
  pricingScrollFlexStart: {
    justifyContent: "flex-start",
  },
  pricingCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: "border-box",
    flex: "0 0 auto",
    height: "100%",
    display: "flex",
    alignItems: "stretch",
  },
  pricingCardInner: {
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    height: "100%",
  },
  pricingCardRoot: {
    width: 360,
    boxShadow: SHADOWS.CARD,
    background: COLORS.WHITE,
    padding: theme.spacing(3),
    borderTopLeftRadius: "50% 25%",
    borderTopRightRadius: "50% 25%",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    border: `2px solid ${COLORS.LIGHT_GRAY}`,
    textAlign: "center",
  },
  pricingCardImgWrap: {
    width: 280,
    height: 280,
    borderRadius: "50%",
    background: COLORS.PRIMARY_BLUE,
    margin: "auto",
    marginBottom: theme.spacing(2),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pricingCardImg: {
    width: 200,
    height: 200,
    objectFit: "contain",
    display: "block",
    margin: "auto",
  },
  pricingCardTitle: {
    fontWeight: 700,
    color: COLORS.PRIMARY_BLUE,
    fontSize: 24,
  },
  pricingCardFeatures: {
    color: COLORS.DARK,
    fontSize: 15,
    listStyle: "disc",
    textAlign: "left",
    width: "100%",
    padding: "0 15px",
  },
  pricingCardFeatureItem: {
    marginBottom: 8,
    fontSize: 18,
  },
  pricingCardButton: {
    color: theme.palette.primary.main,
    borderColor: theme.palette.primary.main,
    textTransform: "none",
    borderRadius: 999,
    paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    paddingTop: theme.spacing(0.5),
    paddingBottom: theme.spacing(0.5),
    background: COLORS.WHITE,
  },
  sectionTitleRoot: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: theme.spacing(3),
  },
  sectionTitleInner: {
    borderRadius: 999,
    backgroundColor: COLORS.WHITE,
    // boxShadow: SHADOWS.CARD,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: theme.spacing(4),
    paddingRight: theme.spacing(4),
    border: `3px ${COLORS.SECONDARY_BLUE}`,
  },
  sectionTitleImg: {
    height: 2,
    transform: "scaleX(1.5)",
    margin: "0 12px",
    [theme.breakpoints.down("md")]: {
      height: 1,
      transform: "scaleX(1)",
      margin: "0 8px",
    },
  },
  sectionTitleText: {
    color: theme.palette.primary.main,
    fontSize: 40,
    fontWeight: 400,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
      paddingLeft: theme.spacing(1),
      paddingRight: theme.spacing(1),
    },
  },
  teamRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: COLORS.WHITE,
    position: "relative",
    overflow: "hidden",
  },
  teamFishesImg: {
    position: "absolute",
    top: 0,
    right: 40,
    width: 500,
    zIndex: 1,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  teamTabs: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(2),
    marginTop: theme.spacing(4),
    marginBottom: theme.spacing(2),
  },
  teamTabActive: {
    color: COLORS.SECONDARY_BLUE,
    fontWeight: 500,
    fontSize: 24,
    cursor: "pointer",
    textDecoration: "underline",
  },
  teamTabDivider: {
    marginLeft: theme.spacing(1.5),
    marginRight: theme.spacing(1.5),
    width: 2,
    color: COLORS.PRIMARY_BLUE,
    fontSize: 22,
  },
  teamTabInactive: {
    color: COLORS.DARK,
    fontWeight: 500,
    fontSize: 24,
    cursor: "pointer",
  },
  teamScrollWrap: {
    width: "100%",
    position: "relative",
    height: "70vh",
    maxHeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing(4),
    zIndex: 2,
  },
  teamBgImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 0,
  },
  teamCardsScroll: {
    display: "flex",
    flexDirection: "row",
    gap: theme.spacing(1),
    justifyContent: "center",
    alignItems: "flex-end",
    position: "relative",
    zIndex: 2,
    width: "100%",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    maxWidth: "1150px",
    margin: "auto",
    "&::-webkit-scrollbar": { display: "none" },
  },
  teamCardsScrollFlexStart: {
    justifyContent: "flex-start",
    gap: theme.spacing(4),
  },
  teamCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: "border-box",
    flex: "0 0 auto",
    height: "100%",
    display: "flex",
    alignItems: "stretch",
    marginLeft: 0,
    marginRight: 0,
  },
  teamCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  teamCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  teamCardInner: {
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    height: "100%",
  },
  teamCardRoot: {
    width: 280,
    background: COLORS.WHITE,
    borderRadius: 4,
    boxShadow: SHADOWS.CARD,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    paddingBottom: theme.spacing(2),
  },
  teamCardAvatar: {
    width: "100%",
    height: 280,
    background: COLORS.WHITE,
    borderRadius: "4px 4px 0 0",
  },
  teamCardRole: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 500,
    fontSize: 17,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    textAlign: "center",
    width: "100%",
    marginTop: theme.spacing(1),
  },
  teamCardInfoRow: {
    width: "90%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "auto",
  },
  teamCardInfoCol: {
    display: "flex",
    marginTop: theme.spacing(0.5),
    flexDirection: "column",
    alignItems: "flex-start",
  },
  teamCardName: {
    fontWeight: 900,
    color: COLORS.DARK,
    fontSize: 22,
    textAlign: "left",
  },
  teamCardLocation: {
    color: COLORS.DARK,
    fontSize: 15,
    fontWeight: 600,
    textAlign: "left",
    marginBottom: 0,
  },
  teamCardButton: {
    minWidth: 0,
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: theme.palette.primary.main,
    color: COLORS.WHITE,
    boxShadow: SHADOWS.SUBTLE,
    padding: 0,
  },
  teamCardArrow: {
    fontSize: 22,
  },
  testimonialsRoot: {
    width: "100%",
    position: "relative",
    left: "50%",
    right: "50%",
    marginLeft: "-50%",
    marginRight: "-50%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    background: COLORS.WHITE,
  },
  testimonialsScroll: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "center",
    alignItems: "stretch",
    width: "100%",
    maxWidth: 1180,
    margin: "auto",
    marginTop: theme.spacing(6),
    gap: theme.spacing(5),
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": { display: "none" },
  },
  testimonialsScrollFlexStart: {
    justifyContent: "flex-start",
  },
  testimonialsCardOuter: {
    minWidth: 320,
    maxWidth: 380,
    width: 340,
    boxSizing: "border-box",
    flex: "0 0 auto",
    height: "100%",
    display: "flex",
    alignItems: "stretch",
    marginLeft: 0,
    marginRight: 0,
  },
  testimonialsCardOuterFirst: {
    marginLeft: theme.spacing(4),
  },
  testimonialsCardOuterLast: {
    marginRight: theme.spacing(4),
  },
  testimonialCardRoot: {
    flex: 1,
    minWidth: 320,
    maxWidth: 500,
    minHeight: 280,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
  },
  testimonialCardCloudWrap: {
    width: "100%",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  testimonialCardCloudImg: {
    width: "100%",
    height: 200,
    display: "block",
  },
  testimonialCardQuote: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "90%",
    height: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.primary.main,
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 1.3,
    paddingTop: theme.spacing(0.25),
    paddingLeft: theme.spacing(2),
    margin: "auto",
    marginTop: -14,
  },
  testimonialCardAvatar: {
    width: 64,
    height: 64,
    position: "absolute",
    left: "10%",
    bottom: -24,
    transform: "translateX(-50%)",
    border: `3px solid ${COLORS.WHITE}`,
    boxShadow: SHADOWS.SUBTLE,
    background: COLORS.WHITE,
  },
  testimonialCardInfo: {
    position: "absolute",
    left: "10%",
    top: 220,
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: 120,
    marginTop: theme.spacing(1),
  },
  testimonialCardName: {
    fontWeight: 600,
    color: COLORS.DARK,
  },
  testimonialCardRole: {
    fontSize: 14,
    color: theme.palette.primary.main,
  },

  // Testimonial Carousel Styles
  testimonialCarouselWrapper: {
    maxWidth: 1200,
    margin: "40px auto",
    position: "relative",
  },
  testimonialCarouselCard: {
    background: COLORS.WHITE,
    borderRadius: 12,
    boxShadow: SHADOWS.LARGE,
    padding: 32,
    position: "relative",
    marginBottom: 24,
    [theme.breakpoints.down("md")]: {
      padding: 24,
      marginBottom: 16,
    },
  },
  testimonialCarouselContent: {
    display: "flex",
    gap: 32,
    alignItems: "flex-start",
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      gap: 16,
      alignItems: "center",
    },
  },
  testimonialImageContainer: {
    flexShrink: 0,
    width: 140,
    height: 140,
    [theme.breakpoints.down("md")]: {
      width: 120,
      height: 120,
    },
  },
  testimonialImage: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    objectFit: "cover",
    boxShadow: SHADOWS.CARD,
  },
  testimonialTextContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minHeight: 140,
    justifyContent: "space-between",
  },
  testimonialHeading: {
    fontSize: 22,
    fontWeight: 700,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    marginBottom: 4,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
      textAlign: "center",
    },
  },
  testimonialQuote: {
    fontSize: 16,
    lineHeight: 1.5,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    marginBottom: 8,
    flex: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      textAlign: "center",
    },
  },
  testimonialReadMore: {
    fontSize: 14,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    marginBottom: 8,
    cursor: "pointer",
    textDecoration: "underline",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      textAlign: "center",
    },
  },
  testimonialName: {
    fontSize: 18,
    fontWeight: 700,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    marginBottom: 2,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      textAlign: "center",
    },
  },
  testimonialDesignation: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.GRAY,
    fontFamily: FONTS.INTER,
    marginBottom: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      textAlign: "center",
    },
  },
  testimonialPlace: {
    fontSize: 12,
    fontWeight: 400,
    color: COLORS.GRAY,
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      fontSize: 11,
      textAlign: "center",
    },
  },
  testimonialAttribution: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    marginTop: 4,
  },
  testimonialArrowButton: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 48,
    height: 48,
    boxShadow: SHADOWS.CARD,
    zIndex: 10,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    "&:first-of-type": {
      left: -24,
    },
    "&:last-of-type": {
      right: -24,
    },
    [theme.breakpoints.down("md")]: {
      width: 40,
      height: 40,
      "&:first-of-type": {
        left: -20,
      },
      "&:last-of-type": {
        right: -20,
      },
    },
  },
  testimonialDotsWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 24,
  },
  testimonialDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    backgroundColor: "transparent",
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    cursor: "pointer",
    transition: "all 0.3s ease",
    opacity: 0.4,
    "&:hover": {
      opacity: 0.7,
      transform: "scale(1.1)",
    },
  },
  testimonialActiveDot: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    opacity: 1,
    transform: "scale(1.1)",
  },
}));

export default useHomeStyles;
