// src/components/userflow/About/aboutStyles.tsx
import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";

const useAboutStyles = makeStyles()((theme: Theme) => ({
  aboutHeaderTitle: {
    color: theme.palette.primary.dark,
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 55,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      maxWidth: "fit-content",
      margin: "auto",
      textAlign: "center",
      marginTop: "-10px",
      marginBottom: "15px",
      padding: "0.5px 60px",
      borderRadius: 999,
      color: COLORS.WHITE,
      background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    },
  },
  mileStoneHeader: {
    textAlign: "center",
    fontSize: 28,
    borderRadius: 999,
    color: COLORS.WHITE,
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    width: "90%",
    maxWidth: 200,
    margin: "10px auto",
    marginTop: "40px",
    padding: "0.5px 60px",
    [theme.breakpoints.down("md")]: {
      padding: "0.5px 20px",
    },
  },
  mileStoneSubtitle: {
    textAlign: "center",
    fontSize: 30,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: "20px",
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      fontFamily: FONTS.INTER,
      fontWeight: 600,
    },
  },
  mileStoneImg: {
    minHeight: "90vh",
    width: "100%",
    marginBottom: "100px",
    [theme.breakpoints.down("md")]: {
      minHeight: "60vh",
      marginBottom: "60px",
    },
  },
  aboutHeaderSubtitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 1.3,
    marginTop: 0,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      marginTop: theme.spacing(1),
    },
  },
  aboutHeaderImg: {
    width: "100%",
    marginTop: theme.spacing(5),
    borderRadius: 12,
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(3),
    },
  },
  aboutHeaderSideGrid: {
    display: "grid",
    placeItems: "center",
    [theme.breakpoints.down("lg")]: {
      marginTop: theme.spacing(2),
      marginBottom: theme.spacing(1),
    },
  },
  aboutCard: {
    background: COLORS.WHITE_GRAY,
    borderRadius: 12,
    boxShadow: SHADOWS.LARGE,
    padding: theme.spacing(4),
    marginBottom: theme.spacing(8),
    position: "relative",
    transition: "box-shadow 0.2s",
    minWidth: 0,
    maxWidth: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(2),
      marginBottom: theme.spacing(6),
    },
  },
  aboutCardTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: theme.spacing(1),
    fontSize: 32,
    [theme.breakpoints.down("md")]: {
      fontSize: 22,
    },
  },
  aboutCardDesc: {
    fontSize: 17,
    fontWeight: 500,
    color: COLORS.DARK,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      marginBottom: theme.spacing(4),
    },
  },
  milestoneItemText: {
    fontSize: 20,
    lineHeight: 38,
    paddingBottom: 10,
    [theme.breakpoints.down("md")]: {
      lineHeight: 12,
    },
  },
  aboutCardImg: {
    width: "100%",
    borderRadius: 8,
    marginBottom: theme.spacing(2),
    marginTop: theme.spacing(1),
    display: "block",
  },
  aboutCardExpandBtn: {
    position: "absolute",
    right: 12,
    bottom: 12,
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    width: 40,
    height: 40,
    zIndex: 2,
    transition: "transform 0.2s",
    [theme.breakpoints.down("md")]: {
      right: 6,
      bottom: 0,
      width: 48,
      height: 48,
    },
  },
  Upicon: {
    fontSize: 36,
    color: COLORS.PRIMARY_BLUE,
  },
  downIcon: {
    transform: "rotate(180deg)",
  },
  aboutCardLargeDesc: {
    fontSize: 20,
    color: COLORS.DARK,
    fontWeight: 500,
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },
  sideImg: {
    maxWidth: "200px",
    maxHeight: "200px",
    display: "block",
    [theme.breakpoints.down("lg")]: {
      marginLeft: "auto",
      marginRight: "auto",
    },
  },
  aboutLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  aboutHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  aboutHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  aboutHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  aboutHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  aboutHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 64,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  aboutHeroSubtitle: {
    color: COLORS.WHITE,
    fontWeight: 700,
    fontSize: 22,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  aboutHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      marginTop: theme.spacing(2),
    },
  },
  aboutSidebarWrapper: {
    width: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  aboutSidebar: {
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  aboutSidebarNavTitle: {
    fontWeight: 700,
    fontSize: 40,
    margin: theme.spacing(1),
  },
  aboutSidebarNavItem: {
    fontWeight: 500,
    fontSize: 15,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 999,
    cursor: "pointer",
    fontFamily: FONTS.INTER,
    background: "transparent",
    color: COLORS.WHITE,
    textDecoration: "none",
    transition: "300ms ease",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 600,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  aboutSidebarContact: {
    width: "100%",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: 12,
    boxShadow: SHADOWS.DARK_CARD,
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    fontSize: 16,
    gap: theme.spacing(1.5),
  },
  aboutSidebarFish: {
    marginTop: theme.spacing(4),
    width: "100%",
    display: "flex",
    justifyContent: "center",
    "& img": {
      width: "80%",
      objectFit: "contain",
      opacity: 0.7,
    },
  },
  aboutMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(20),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },
  aboutMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
      minHeight: "fit-content",
    },
  },
  aboutSidebarContactTitle: {
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 18,
    color: COLORS.SECONDARY_BLUE,
    marginBottom: 4,
  },
  aboutSidebarContactLabel: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
    marginBottom: 4,
  },
  aboutSidebarContactValue: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
  },
  aboutSidebarContactIcon: {
    color: COLORS.SECONDARY_BLUE,
    fontSize: 18,
  },
  aboutSidebarContactRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  aboutMainFish: {
    position: "absolute",
    top: -50,
    right: -20,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  milestoneContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
    padding: "8px 15px 0 15px",
  },
  milestoneItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    maxWidth: 1200,
    margin: theme.spacing(20, 0),
    marginTop: "0",
    position: "relative",
    [theme.breakpoints.down("md")]: {
      textAlign: "center",
      marginBottom: "25px",
    },
  },
  milestoneScrollContainer: {
    maxHeight: "100vh",
    overflowY: "scroll",
    scrollbarWidth: "none",
    marginBottom: "120px",
  },
  milestoneImg: {
    flex: "0 0 50%",
    maxWidth: "45%",
    height: "auto",
    borderRadius: 8,
    zIndex: 2,
    [theme.breakpoints.down("md")]: {
      maxWidth: "45%",
      height: "125px",
      marginBottom: theme.spacing(2),
    },
  },

  milestoneText: {
    flex: "0 0 45%",
    width: "50%",
    maxWidth: 500,
    margin: "0 20px",
    fontWeight: 400,
    display: "flex",
    textAlign: "left",
    flexDirection: "column",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    zIndex: 2,
    [theme.breakpoints.down("md")]: {
      margin: 0,
    },
  },
  milestoneDesc: {
    lineHeight: "28px",
    fontFamily: FONTS.INTER,
    letterSpacing: "0%",
    fontWeight: 500,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      lineHeight: 1.4,
    },
  },
  milestoneYear: {
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 28,
    marginBottom: theme.spacing(1),
    [theme.breakpoints.down("md")]: {
      fontSize: 17,
    },
  },
  milestoneDot: {
    position: "absolute",
    left: "50%",
    top: "0%",
    transform: "translate(-50%, -50%)",
    width: 32,
    height: 32,
    zIndex: 3,
  },
  rotate180: {
    transform: "translate(-50%, -50%) rotate(180deg)",
  },
  dottedLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: "2px",
    backgroundImage: "linear-gradient(to bottom, #0000FF 50%, transparent 50%)",
    backgroundSize: "2px 12px",
    backgroundRepeat: "repeat-y",
    zIndex: 1,
  },

  // Our Team
  teamHeader: {
    textAlign: "center",
    fontSize: 28,
    borderRadius: 999,
    color: COLORS.WHITE,
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    width: "90%",
    maxWidth: "fit-content",
    margin: "10px auto",
    marginTop: "0px",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    padding: "0.5px 40px",
  },
  teamSubtitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: "20px",
    paddingTop: "10px",
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      fontWeight: 600,
      paddingTop: "5px",
      textAlign: "center",
    },
  },
  gridWrapper: {
    maxWidth: 1200,
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 40,
  },
  memberCard: {
    cursor: "pointer",
    transition: "transform 0.3s ease",
    boxShadow: "none",
    maxWidth: "270px",
    "&:hover": {
      transform: "scale(1.03)",
    },
    [theme.breakpoints.down("md")]: {
      margin: "0 auto",
    },
  },
  memberImage: {
    objectFit: "cover",
  },
  sectionWrapper: {
    marginBottom: theme.spacing(4),
  },
  sectionTitle: {
    fontWeight: 700,
    fontSize: "1.5rem",
    textDecoration: "underline",
    marginBottom: theme.spacing(2.5),
    color: theme.palette.primary.main,
    fontFamily: FONTS.INTER,
  },
  teamPaper: {
    boxShadow: "none",
    padding: "4px 5px",
  },
  memberName: {
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    fontSize: 16,
  },
  memberDesignation: {
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    fontSize: 14,
    color: COLORS.PRIMARY_BLUE,
  },
  carouselWrapper: {
    maxWidth: 1200,
    margin: "auto",
  },
  carouselCard: {
    marginTop: theme.spacing(3),
    padding: theme.spacing(3),
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.1)",
    borderRadius: 8,
    backgroundColor: COLORS.WHITE,
  },
  carouselImage: {
    width: "100%",
    height: "auto",
    borderRadius: 8,
    objectFit: "cover",
  },
  carouselTitle: {
    fontSize: 20,
    fontWeight: 600,
    fontFamily: FONTS.INTER,
    color: COLORS.PRIMARY_BLUE,
  },
  carouselName: {
    fontSize: 18,
    fontWeight: 700,
    margin: "10px 0",
    fontFamily: FONTS.INTER,
  },
  navWrapper: {
    marginTop: theme.spacing(3),
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dotsWrapper: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    backgroundColor: COLORS.SECONDARY_BLUE,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    cursor: "pointer",
    transition: "all 0.3s ease",
    marginTop: 20,
    opacity: 0.4,
    "&:hover": {
      opacity: 0.7,
      transform: "scale(1.1)",
    },
  },
  activeDot: {
    width: 12,
    height: 12,
    backgroundColor: COLORS.PRIMARY_BLUE,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    opacity: 1,
    transform: "scale(1.1)",
  },
  backButton: {
    marginTop: theme.spacing(2),
    display: "flex",
    alignItems: "center",
    gap: 4,
    color: COLORS.WHITE,
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    backgroundColor: COLORS.SECONDARY_BLUE,
    "&:hover": {
      backgroundColor: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
  },
  backButtonWrapper: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
  },
  backIconSmall: {
    fontSize: 18,
  },
  carouselDetailsWrapper: {
    display: "flex",
  },
  carouselDetails: {
    fontSize: 18,
    fontWeight: 400,
    fontFamily: FONTS.INTER,
    color: "black",
    margin: "30px 0",
    width: "90%",
    [theme.breakpoints.down("md")]: {
      width: "100%",
      fontSize: 14,
    },
  },

  // Custom for OurTeam new carousel UI
  headerSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: 32,
    position: "relative",
  },
  headerPill: {
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    borderRadius: 999,
    padding: "8px 32px",
    color: COLORS.WHITE,
    fontWeight: 700,
    fontSize: 24,
    marginBottom: 8,
    boxShadow: SHADOWS.LARGE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    display: "inline-block",
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
      textAlign: "center",
    },
  },
  headerIconContainer: {
    position: "absolute",
    right: 0,
    top: "50%",
    transform: "translateY(-50%)",
    [theme.breakpoints.down("lg")]: {
      display: "none",
    },
  },
  headerIcon: {
    width: 120,
    height: 120,
    opacity: 0.8,
  },
  autoHeaderTabWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "16px",
  },
  
  autoHeaderTab: {
    fontSize: 22,
    fontFamily:FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    color: theme.palette.text.secondary,
    paddingBottom: 4,
    position: "relative",
    cursor: "pointer",
  },
  
  autoHeaderTabActive: {
    fontWeight: 600,
    color:COLORS.SECONDARY_BLUE ,
    textDecoration: "underline",
    textUnderlineOffset:2, 
    textDecorationThickness: 2,
  },
  
  autoHeaderTabSeparator: {
    fontSize: 22,
    color: theme.palette.text.secondary,
    fontWeight: 500,
  },
  
  tabContainer: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginTop: 16,
  },
  tabItem: {
    fontWeight: 700,
    fontSize: 18,
    color: COLORS.GRAY,
    cursor: "pointer",
    padding: "8px 0px 1px 0px",
    margin: "0 8px",
    transition: "all 0.3s ease",
    textTransform: "uppercase",
    "&:hover": {
      color: COLORS.PRIMARY_BLUE,
    },
  },
  tabItemActive: {
    color: COLORS.SECONDARY_BLUE,
    borderBottom: `2px solid ${COLORS.SECONDARY_BLUE}`,
    paddingBottom: "1px",
  },
  tabDivider: {
    width: 1,
    height: 25,
    marginTop: 5,
    backgroundColor: COLORS.GRAY,
    opacity: 0.5,
  },
  tabItemInactive: {
    fontWeight: 700,
    fontSize: 18,
    minHeight: 0,
    color: COLORS.PRIMARY_BLUE,
    opacity: 0.5,
  },
  carouselWrapperCustom: {
    background: "#ECF7FF",
    borderRadius: 8,
    padding: 24,
    margin: "auto",
    maxWidth: 1200,
    boxShadow: "0 2px 8px 0 #0A4FA42E",
  },
  arrowGrid: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  arrowButton: {
    background: "transparent",
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    padding: 0,
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg": {
      fontSize: 18,
    },
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
  },
  arrowButtonDesktop: {
    background: "transparent",
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    padding: 0,
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
    "& svg": {
      fontSize: 18,
    },
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    "&:first-of-type": {
      left: -16,
    },
    "&:last-of-type": {
      right: -16,
    },
  },
  arrowButtonMobile: {
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 36,
    height: 36,
    minWidth: 36,
    minHeight: 36,
    padding: 0,
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    "& svg": {
      fontSize: 18,
    },
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
  },
  imageGrid: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  carouselImageCustom: {
    width: 180,
    height: 180,
    borderRadius: 12,
    objectFit: "cover",
    boxShadow: SHADOWS.CARD,
    background: COLORS.WHITE,
  },
  detailsGrid: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingLeft: 16,
    paddingRight: 16,
  },
  designationPill: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    fontSize: 16,
    display: "inline-block",
    marginBottom: 30,
    marginTop: 4,
    [theme.breakpoints.down("md")]: {
      marginBottom: 0,
    },
  },
  carouselNameCustom: {
    fontWeight: 700,
    fontSize: 18,
    marginTop: 8,
    fontFamily: FONTS.INTER,
    color: COLORS.DARK,
    [theme.breakpoints.down("md")]: {
      textAlign: "center",
    },
  },
  bigDesignationCustom: {
    fontWeight: 500,
    fontSize: 15,
    color: "black",
    maxWidth: "350px",
    marginTop: 4,
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      maxWidth: "100%",
      textAlign: "center",
    },
  },
  qualificationCustom: {
    fontWeight: 400,
    fontSize: 15,
    color: COLORS.DARK,
    marginBottom: 8,
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      textAlign: "center",
    },
  },
  descriptionBoxCustom: {
    maxHeight: 180,
    overflowY: "auto",
    background: "transparent",
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
    width: "100%",
  },
  carouselDetailsCustom: {
    fontSize: 16,
    wordBreak: "break-word",
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
  },
  dotsWrapperCustom: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 24,
    position: "relative",
    zIndex: 10,
    [theme.breakpoints.down("md")]: {
      marginTop: 16,
    },
  },
  memberGridItem: {
    cursor: "pointer",
    display: "flex",
    justifyContent: "flex-start",
    [theme.breakpoints.down("md")]: {
      justifyContent: "center",
      margin: "0 auto",
    },
  },
  carouselDesktopBox: {
    display: "flex",
    flexDirection: "row",
    gap: 32,
    alignItems: "flex-start",
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      gap: 0,
    },
  },
  carouselDesktopTopRow: {
    display: "flex",
    flexDirection: "row",
    gap: 32,
    alignItems: "flex-start",
    marginBottom: 24,
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      gap: 0,
      marginBottom: 16,
    },
  },
  carouselDesktopImgBox: {
    minWidth: 180,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    [theme.breakpoints.down("md")]: {
      width: "100%",
      marginRight: 0,
      marginBottom: 16,
    },
  },
  carouselDesktopInfoBox: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    [theme.breakpoints.down("md")]: {
      alignItems: "center",
    },
  },
  carouselDesktopDescRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    width: "100%",
    background: "none",
    boxSizing: "border-box",
    position: "relative",
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      marginTop: 8,
    },
  },
  carouselDesktopDescBox: {
    flex: 1,
    background: "transparent",
    borderRadius: 8,
    padding: 12,
    margin: "0 8px",
    overflowY: "auto",
    minWidth: 0,
    [theme.breakpoints.down("md")]: {
      margin: 0,
      width: "100%",
    },
  },
  carouselMobileImgBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginBottom: 16,
  },
  carouselMobileInfoBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: 16,
  },
  carouselMobileDescBox: {
    width: "100%",
    background: "transparent",
    borderRadius: 8,
    // padding: 16,
    marginBottom: 16,
    overflowY: "auto",
  },
  carouselMobileArrowsBox: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    position: "absolute",
    top: "50%",
    left: 0,
    right: 0,
    transform: "translateY(-50%)",
    padding: "0 16px",
    pointerEvents: "none",
    "& > *": {
      pointerEvents: "auto",
    },
  },
  carouselMobileBottomArrowsBox: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
  },

  // Testimonials Styles
  
  testimonialCarouselWrapper: {
    maxWidth: 1200,
    margin: "40px auto",
    position: "relative",
  },
testimonialRoot: {
    width: "100%",
    paddingTop: theme.spacing(6),
    paddingBottom: theme.spacing(6),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      paddingTop: theme.spacing(2),
      paddingBottom: theme.spacing(2),
    },
  },
  testimonialFishesImg: {
    position: "absolute",
    right:-150,
    top: -70,
    zIndex: 100,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  testimonialFishesImg2: {
    position: "absolute",
    left:-600,
    bottom:80,
    zIndex: 100,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  testimonialCarouselCard: {
    background: COLORS.WHITE,
    borderRadius: 6,
    boxShadow: SHADOWS.MEDIUM,
    overflow: "hidden",
    position: "relative",
    marginBottom: 24,
    minHeight: 400,
    [theme.breakpoints.down("md")]: {
      marginBottom: 16,
      minHeight: 300,
    },
  },
  testimonialCarouselContent: {
    display: "flex",
    gap: 12,
    alignItems: "stretch",
    height: "100%",
  },
  testimonialImageContainer: {
    flexShrink: 0,
    width: 260,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  testimonialImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: 0,
  },
  testimonialTextContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "32px 16px",
    justifyContent: "space-between",
  },
  testimonialTitle: {
    fontSize: 32,
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    marginBottom: 8,
    [theme.breakpoints.down("md")]: {
      fontSize: 24,
    },
  },
  testimonialQuote: {
    fontSize: 18,
    lineHeight: "56px",
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    marginBottom: 16,
    flex: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      lineHeight: "20px",
    },
  },
  testimonialReadMore: {
    fontSize: 14,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 500,
    display: "inline",
    marginBottom: 16,
    cursor: "pointer",
    textDecoration: "underline",
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      marginBottom: 12,
    },
  },
  testimonialDots: {
    fontSize: 14,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    display: "inline",
  },
  testimonialName: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    marginBottom: 2,
    textTransform: "capitalize",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  testimonialDesignation: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    marginBottom: 2,
    textTransform: "lowercase",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  testimonialPlace: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    textTransform: "lowercase",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  testimonialAttribution: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    marginTop: 8,
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  testimonialArrowButton: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: "50%",
    width: 100,
    height: 100,
    boxShadow: SHADOWS.CARD,
    zIndex: 10,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    "&:first-of-type": {
      left: -55,
      "& svg": {
        marginLeft: 40,
        fontSize: 25,
      },
    },
    "&:last-of-type": {
      right: -55,
      "& svg": {
        marginRight: 40,
        fontSize: 25,
      },
    },
    [theme.breakpoints.down("md")]: {
      width: 50,
      height: 50,
      "&:first-of-type": {
        left: -25,
        "& svg": {
          marginLeft: 20,
          fontSize: 15,
        },
      },
      "&:last-of-type": {
        right: -25,
        "& svg": {
          marginLeft: 20,
          fontSize: 15,
        },
      },
    },
  },
  testimonialDotsWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 24,
  },
  testimonialDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    backgroundColor: "transparent",
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    cursor: "pointer",
    transition: "all 0.3s ease",
    opacity: 0.4,
    "&:hover": {
      opacity: 0.7,
      transform: "scale(1.1)",
    },
  },
  testimonialActiveDot: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    opacity: 1,
    transform: "scale(1.1)",
    cursor: "pointer",
  },
  testimonialBottomSection: {
    marginTop: 48,
    [theme.breakpoints.down("md")]: {
      marginTop: 32,
    },
  },
  testimonialFishIcons: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
    marginBottom: 24,
    [theme.breakpoints.down("md")]: {
      gap: 12,
      marginBottom: 16,
    },
  },
  testimonialFishIcon: {
    fontSize: 24,
    opacity: 0.6,
    [theme.breakpoints.down("md")]: {
      fontSize: 20,
    },
  },
  testimonialScrollableCards: {
    display: "flex",
    gap: 24,
    overflowX: "auto",
    padding: "8px 0",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    [theme.breakpoints.down("md")]: {
      gap: 16,
    },
  },
  testimonialSmallCard: {
    minWidth: 400,
    background: COLORS.WHITE,
    borderRadius: 8,
    boxShadow: SHADOWS.CARD,
    padding: 20,
    [theme.breakpoints.down("md")]: {
      minWidth: 300,
      padding: 16,
    },
  },
  testimonialSmallCardContent: {
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
  },
  testimonialSmallImage: {
    width: 60,
    height: 60,
    borderRadius: "50%",
    objectFit: "cover",
    flexShrink: 0,
    [theme.breakpoints.down("md")]: {
      width: 50,
      height: 50,
    },
  },
  testimonialSmallText: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  testimonialSmallQuote: {
    fontSize: 14,
    lineHeight: 1.5,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    [theme.breakpoints.down("md")]: {
      fontSize: 13,
    },
  },
  testimonialSmallName: {
    fontSize: 16,
    fontWeight: 700,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },
  testimonialSmallDesignation: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.GRAY,
    fontFamily: FONTS.INTER,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },

  // Bottom section full-width
  testimonialBottomWrapper: {
    width: "100%",
    background: "#DBECF9",
    paddingTop: 24,
    paddingBottom: 48,
    marginTop: 62,
    marginBottom: 80,
    [theme.breakpoints.down("md")]: {
      paddingTop: 16,
      paddingBottom: 32,
      marginTop: 16,
      marginBottom: 40,
    },
  },
  extraWidth: {
    width: 1,
    paddingLeft: "60px",
    [theme.breakpoints.down("md")]: {
      paddingLeft: "20px",
    },
  },
  testimonialWideCards: {
    position:"relative",
    width: "100%",
    display: "flex",
    gap: 24,
    overflowX: "auto",
    paddingLeft: 64,
    paddingRight: 64,
    zIndex:101,
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    [theme.breakpoints.down("md")]: {
      gap: 16,
      paddingLeft: 16,
      paddingRight: 16,
    },
  },
  testimonialWideCard: {
    minWidth: 520,
    height: 220,
    borderRadius: 12,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    position: "relative",
    overflow: "hidden",
    boxShadow: SHADOWS.CARD,
    [theme.breakpoints.down("md")]: {
      minWidth: 400,
      height: 180,
    },
  },
  testimonialWideOverlay: {
    position: "absolute",
    inset: 0,
  },
  testimonialWideTextBox: {
    width: "70%",
    backgroundColor: COLORS.WHITE,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    borderRadius: "0 8px 8px 0",
    color: COLORS.DARK,
  },
  testimonialWideQuote: {
    fontSize: 14,
    lineHeight: 1.8,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    color: "#000",
    fontStyle: "italic",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  testimonialWideName: {
    fontSize: 12,
    fontWeight: 500,
    fontFamily: FONTS.INTER,
    color: COLORS.PRIMARY_BLUE,
    [theme.breakpoints.down("md")]: {
      fontSize: 11,
    },
  },
  testimonialWideDesignation: {
    fontSize: 12,
    fontWeight: 500,
    fontFamily: FONTS.INTER,
    paddingBottom: 0,
    marginBottom: 0,
    color: COLORS.PRIMARY_BLUE,
    [theme.breakpoints.down("md")]: {
      fontSize: 11,
    },
  },

  // Pagination styles for Read More mode
  testimonialPaginationWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
    marginBottom: 32,
    [theme.breakpoints.down("md")]: {
      marginTop: 24,
      marginBottom: 24,
    },
  },
  testimonialPagination: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    [theme.breakpoints.down("md")]: {
      gap: 12,
    },
  },
  testimonialBackButton: {
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 40,
    height: 40,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    border: `0.5px solid ${COLORS.LGRAY}`,
    [theme.breakpoints.down("md")]: {
      width: 36,
      height: 36,
    },
  },
  testimonialNextButton: {
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    width: 40,
    height: 40,
    border: `0.5px solid ${COLORS.LGRAY}`,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    [theme.breakpoints.down("md")]: {
      width: 36,
      height: 36,
    },
  },
  smallText: {
    fontSize: 12,
  },
  testimonialPageButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    borderRadius: "50%",
    border: `0.5px solid ${COLORS.PRIMARY_BLUE}`,
    backgroundColor: "transparent",
    color: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
      transform: "scale(1.05)",
    },
    [theme.breakpoints.down("md")]: {
      width: 36,
      height: 36,
      fontSize: 14,
    },
  },
  testimonialActivePageButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `2px solid ${COLORS.PRIMARY_BLUE}`,
    transform: "scale(1.1)",
  },

  // Read More overrides
  testimonialReadMoreCard: {
    background: "transparent",
    borderRadius: 0,
    boxShadow: "none",
    minHeight: "auto",
    marginBottom: 16,
  },
  testimonialReadMoreContent: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    alignItems: "stretch",
    height: "auto",
  },
  testimonialReadMoreImageContainer: {
    width: "100%",
    height: 420,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundPositionY: "calc(50% + 100px)",
    backgroundRepeat: "no-repeat",
    [theme.breakpoints.down("md")]: {
      height: 220,
      backgroundPositionY: "calc(50% - 60px)",
    },
  },
  testimonialReadMoreTextContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "16px 0",
  },
  testimonialQuoteCompact: {
    fontSize: 16,
    lineHeight: 1.6,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    marginBottom: 8,
  },

  // Line pagination styles for bottom carousel
  testimonialLinePagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginTop: 24,
    [theme.breakpoints.down("md")]: {
      gap: 6,
      marginTop: 20,
    },
  },
  testimonialLine: {
    height: 4,
    borderRadius: 2,
    cursor: "pointer",
    transition: "all 0.3s ease",
    backgroundColor: "#0A4FA4FA",
    opacity: 0.6,
    width: 20,
    [theme.breakpoints.down("md")]: {
      height: 3,
      width: 16,
    },
  },
  testimonialActiveLine: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    opacity: 1,
    width: 40,
    [theme.breakpoints.down("md")]: {
      width: 32,
    },
  },

  // Bottom wide card layout styles
  testimonialWideContent: {
    display: "flex",
    width: "100%",
    height: "100%",
  },
  testimonialWideImageContainer: {
    width: "30%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: "8px 0 0 8px",
  },
  testimonialWideAttribution: {
    display: "flex",
    flexDirection: "column",
    marginTop: 12,
  },
  testimonialWidePlace: {
    fontSize: 12,
    fontWeight: 500,
    marginBottom: 0,
    paddingBottom: 0,
    fontFamily: FONTS.INTER,
    color: COLORS.PRIMARY_BLUE,
    [theme.breakpoints.down("md")]: {
      fontSize: 11,
    },
  },

  // Milestones styles
  milestoneItemRow: {
    flexDirection: "row",
  },
  milestoneItemRowReverse: {
    flexDirection: "row-reverse",
  },
  milestoneGridFlex: {
    flex: 1,
  },
  milestoneTextJustify: {
    textAlign: "justify",
    marginBottom: theme.spacing(0.5),
  },

  // AboutCardsSection styles
  aboutCardsGrid: {
    marginTop: theme.spacing(6),
  },
}));

export default useAboutStyles;
