import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";

const useAboutStyles = makeStyles()((theme: Theme) => ({
  aboutHeaderTitle: {
    color: theme.palette.primary.dark,
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 55,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      maxWidth: "fit-content",
      margin: "auto",
      textAlign: "center",
      marginTop: "-10px",
      marginBottom: "15px",
      padding: "0.5px 60px",
      borderRadius: 999,
      color: COLORS.WHITE,
      background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    },
  },
  mileStoneHeader: {
    textAlign: "center",
    fontSize: 28,
    borderRadius: 999,
    color: COLORS.WHITE,
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    width: "90%",
    maxWidth: 200,
    margin: "10px auto",
    marginTop: "40px",
    padding: "0.5px 60px",
  },
  mileStoneSubtitle: {
    textAlign: "center",
    fontSize: 30,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: "20px",
  },
  mileStoneImg: {
    minHeight: "100vh",
    width: "100%",
    marginBottom: "100px",
  },
  aboutHeaderSubtitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 1.3,
    marginTop: 0,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      marginTop: theme.spacing(1),
    },
  },
  aboutHeaderImg: {
    width: "100%",
    marginTop: theme.spacing(5),
    borderRadius: 12,
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(3),
    },
  },
  aboutCard: {
    background: COLORS.WHITE_GRAY,
    borderRadius: 12,
    boxShadow: SHADOWS.LARGE,
    padding: theme.spacing(4),
    marginBottom: theme.spacing(8),
    position: "relative",
    transition: "box-shadow 0.2s",
    minWidth: 0,
    maxWidth: "100%",
    marginLeft: "auto",
    marginRight: "auto",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(2),
      marginBottom: theme.spacing(6),
    },
  },
  aboutCardTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontWeight: 400,
    marginBottom: theme.spacing(2),
    fontSize: 32,
    [theme.breakpoints.down("md")]: {
      fontSize: 22,
      marginBottom: theme.spacing(1.5),
    },
  },
  aboutCardDesc: {
    fontSize: 20,
    fontWeight: 500,
    color: COLORS.DARK,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
      marginBottom: theme.spacing(4),
    },
  },
  aboutCardImg: {
    width: "100%",
    borderRadius: 8,
    marginBottom: theme.spacing(2),
    marginTop: theme.spacing(1),
    display: "block",
  },
  aboutCardExpandBtn: {
    position: "absolute",
    right: 12,
    bottom: 12,
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    width: 40,
    height: 40,
    zIndex: 2,
    transition: "transform 0.2s",
    [theme.breakpoints.down("md")]: {
      right: 6,
      bottom: 0,
      width: 48,
      height: 48,
    },
  },
  Upicon: {
    fontSize: 36,
    color: COLORS.PRIMARY_BLUE,
  },
  downIcon: {
    transform: "rotate(180deg)",
  },
  aboutCardLargeDesc: {
    fontSize: 20,
    color: COLORS.DARK,
    fontWeight: 500,
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },
  sideImg: {
    maxWidth: "200px",
    maxHeight: "200px",
    display: "block",
  },
  aboutLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  aboutHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  aboutHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  aboutHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  aboutHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  aboutHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 48,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  aboutHeroSubtitle: {
    color: COLORS.WHITE,
    fontWeight: 700,
    fontSize: 22,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  aboutHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
      marginTop: theme.spacing(2),
    },
  },
  aboutSidebarWrapper: {
    width: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  aboutSidebar: {
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  aboutSidebarNavTitle: {
    fontWeight: 700,
    fontSize: 40,
    margin: theme.spacing(1),
  },
  aboutSidebarNavItem: {
    fontWeight: 500,
    fontSize: 18,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderRadius: 999,
    cursor: "pointer",
    fontFamily: "Roboto",
    background: "transparent",
    color: COLORS.WHITE,
    transition: "300ms ease",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 600,
      paddingLeft: theme.spacing(2),
      paddingRight: theme.spacing(2),
    },
  },
  aboutSidebarContact: {
    width: "100%",
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    borderRadius: 12,
    boxShadow: SHADOWS.DARK_CARD,
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    fontSize: 16,
    gap: theme.spacing(1.5),
  },
  aboutSidebarFish: {
    marginTop: theme.spacing(4),
    width: "100%",
    display: "flex",
    justifyContent: "center",
    "& img": {
      width: "80%",
      objectFit: "contain",
      opacity: 0.7,
    },
  },
  aboutMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(20),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },
  aboutMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
    },
  },
  aboutSidebarContactTitle: {
    fontWeight: 500,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 18,
    color: COLORS.SECONDARY_BLUE,
    marginBottom: 4,
  },
  aboutSidebarContactLabel: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
    marginBottom: 4,
  },
  aboutSidebarContactValue: {
    fontWeight: 500,
    fontSize: 15,
    color: COLORS.DARK,
  },
  aboutSidebarContactIcon: {
    color: COLORS.SECONDARY_BLUE,
    fontSize: 18,
  },
  aboutSidebarContactRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  aboutMainFish: {
    position: "absolute",
    top: -50,
    right: -20,
    display: "block",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  milestoneContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    padding: theme.spacing(4, 0),
  },
  milestoneItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    maxWidth: 1200,
    margin: theme.spacing(8, 0),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      textAlign: "center",
    },
  },

  milestoneImg: {
    flex: "0 0 50%",
    width: "50%",
    maxWidth: 500,
    height: "auto",
    borderRadius: 8,
    zIndex: 2,
    [theme.breakpoints.down("md")]: {
      maxWidth: 300,
      marginBottom: theme.spacing(2),
    },
  },

  milestoneText: {
    flex: "0 0 50%",
    width: "100%",
    maxWidth: 500,
    margin: "0 20px",
    zIndex: 2,
    [theme.breakpoints.down("md")]: {
      margin: 0,
    },
  },

  milestoneYear: {
    fontWeight: "bold",
    color: COLORS.PRIMARY_BLUE,
    fontSize: 22,
    marginBottom: theme.spacing(1),
  },
  milestoneDot: {
    position: "absolute",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    width: 32,
    height: 32,
    zIndex: 3,
  },
  rotate180: {
    transform: "translate(-50%, -50%) rotate(180deg)",
  },
  dottedLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: "2px",
    backgroundImage: "linear-gradient(to bottom, #0000FF 50%, transparent 50%)",
    backgroundSize: "2px 12px",
    backgroundRepeat: "repeat-y",
    zIndex: 1,
  },
}));

export default useAboutStyles;
