import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";

const useNewsEventsStyles = makeStyles()((theme: Theme) => ({
  newsEventsLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  newsEventsMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
    },
  },
  newsEventsMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(5),
    paddingRight: theme.spacing(15),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },

  newsEventsHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  newsEventsHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  newsEventsHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  newsEventsHeroColorOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "#0A4FA469",
    opacity: 0.45,
    zIndex: 3,
  },
  newsEventsHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  newsEventsHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 48,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  newsEventsHeroSubtitle: {
    color: COLORS.WHITE,
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    fontSize: 18,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  newsEventsHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      marginTop: theme.spacing(2),
    },
  },

  newsEventsSidebarWrapper: {
    width: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  newsEventsSidebar: {
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  newsEventsSidebarNavTitle: {
    fontWeight: 400,
    fontSize: 32,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    textAlign: "left",
    [theme.breakpoints.down("md")]: {
      fontSize: 24,
    },
  },
  newsEventsSidebarNavItem: {
    color: COLORS.WHITE,
    fontWeight: 600,
    fontFamily: FONTS.INTER,
    fontSize: 14,
    padding: theme.spacing(1.5, 2),
    borderRadius: 999,
    transition: "all 0.3s ease",
    textAlign: "left",
    cursor: "pointer",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 700,
    },
  },

  // Side image styles
  newsEventsSideImg: {
    position: "absolute",
    top: -30,
    right: 80,
    width: 120,
    height: "auto",
    opacity: 0.1,
    zIndex: 0,
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },

  // Page styles
  newsEventsPageHeader: {
    marginBottom: theme.spacing(4),
  },
  newsEventsPageBanner: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(3),
    padding: theme.spacing(3),
    background: COLORS.WHITE,
    borderRadius: 12,
    boxShadow: SHADOWS.CARD,
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      textAlign: "center",
    },
  },
  newsEventsPageIcon: {
    width: 80,
    height: 80,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    flexShrink: 0,
    [theme.breakpoints.down("md")]: {
      width: 60,
      height: 60,
    },
  },
  newsEventsPageIconImg: {
    width: "60%",
    height: "60%",
    objectFit: "contain",
  },
  newsEventsPageTextContent: {
    flex: 1,
  },
  newsEventsPageTitle: {
    fontSize: 32,
    fontWeight: 700,
    color: COLORS.PRIMARY_DARK,
    marginBottom: theme.spacing(1),
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    [theme.breakpoints.down("md")]: {
      fontSize: 24,
    },
  },
  newsEventsPageSubtitle: {
    fontSize: 16,
    color: COLORS.MEDIUM_GRAY,
    lineHeight: 1.6,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },

  // Success Stories (carousel) styles
  successStoriesRoot: {
    display: "flex",
    flexDirection: "column",
  },
  successStoriesHeading: {
    marginBottom: 4,
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
  },
  successStoriesHeaderBar: {
    width: "100%",
    margin: "0 auto 12px auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "28px",
    marginBottom: "36px",
  },
  successStoriesHeaderTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 26,
  },
  successStoriesHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  successStoriesCalendarPill: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 8,
    padding: theme.spacing(1),
  },
  successStoriesSelect: {
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    padding: 0,
    "& .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "& .MuiSelect-icon": {
      color: COLORS.WHITE,
    },
    "& .MuiInputBase-input": {
      padding: "4px 8px",
    },
  },
  successStoriesCarousel: {
    position: "relative",
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
    aspectRatio: "16 / 9",
    backgroundColor: "#eee",
  },
  successStoriesBg: {
    position: "absolute",
    inset: 0,
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "background-image 300ms ease",
  },
  successStoriesArrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: "50%",
    width: 100,
    height: 100,
    boxShadow: SHADOWS.CARD,
    zIndex: 10,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    [theme.breakpoints.down("md")]: {
      width: 50,
      height: 50,
    },
  },
  successStoriesArrowLeft: {
    left: -55,
    "& svg": {
      marginLeft: 40,
      fontSize: 32,
      [theme.breakpoints.down("md")]: {
        marginLeft: 20,
        fontSize: 15,
      },
    },
    [theme.breakpoints.down("md")]: {
      left: -25,
    },
  },
  successStoriesArrowRight: {
    right: -55,
    "& svg": {
      marginRight: 40,
      fontSize: 32,
      [theme.breakpoints.down("md")]: {
        marginRight: 20,
        fontSize: 15,
      },
    },
    [theme.breakpoints.down("md")]: {
      right: -25,
    },
  },
  successStoriesOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "15px 20px",
    backgroundColor: "#0B4FA4A6",
    color: COLORS.WHITE,
  },
  successStoriesTitle: {
    fontWeight: 400,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 32,
    textTransform: "capitalize",
    letterSpacing: 0.5,
    textAlign: "center",
  },

  // twoCardsCarousel styles removed

  // Card list with pagination
  cardsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "0",
  },
  storyCard: {
    background: COLORS.WHITE,
    borderRadius: 8,
    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
    overflow: "visible",
    position: "relative",
    maxHeight: 400,
    marginBottom: "20px",
  },
  storyCardTop: {
    position: "relative",
    width: "100%",
    height: 400,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  storyCardImg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "8px",
    border: "0.5px solid #000",
  },
  storyDateBadge: {
    position: "absolute",
    left: 8,
    top: 8,
    background: "#E0E2E3C2",
    backdropFilter: "blur(10px)",
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 6,
    padding: "8px 10px",
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 1.2,
    minWidth: 42,
  },
  bigText: {
    fontSize: 20,
    fontWeight: 500,
  },
  storyCardContent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: "-3px",
    padding: 16,
    background: "rgba(255,255,255)",
    borderRadius: "12px 12px 0 0",
    border: "1px solid #57B6FF",
  },
  storyTitle: {
    fontFamily: FONTS.INTER,
    fontWeight: 900,
    color: COLORS.DARK,
    fontSize: 22,
    marginBottom: 4,
  },
  storyExcerpt: {
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    fontSize: 13,
    color: COLORS.DARK,
    lineHeight: 1.5,
    marginBottom: 12,
  },
  storyTime: {
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 11,
    color: COLORS.PRIMARY_BLUE,
    marginBottom: 10,
  },
  storyButton: {
    display: "inline-block",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    border: `1px solid ${COLORS.SECONDARY_BLUE}`,
    borderRadius: 999,
    padding: "6px 30px",
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
  },
  // Detail view (reuses modal look n feel)
  storyModalContent: {
    width: "95%",
    maxHeight: "92vh",
    background: COLORS.WHITE,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    margin: "0 auto",
  },
  storyModalHero: {
    position: "relative",
    width: "100%",
    height: 360,
    border: "1px solid #3D0A0A",
    borderRadius: 8,
    background: COLORS.LIGHT_GRAY,
  },
  storyCalendarTopRight: {
    position: "absolute",
    top: 16,
    right: 8,
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.WHITE,
    border: "1px solid #0463EE",
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 8,
    padding: theme.spacing(1, 2),
  },
  storyModalImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  storyModalBody: {
    padding: theme.spacing(0, 0, 3, 0),
  },
  storyMetaList: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.2),
    marginBottom: theme.spacing(6),
  },
  storyMetaItem: {
    fontFamily: FONTS.INTER,
    fontSize: 14,
    color: COLORS.DARK,
  },
  storyMetaLabel: {
    fontWeight: 700,
    marginRight: 6,
  },
  storyImageGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: theme.spacing(2),
    marginTop: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
    },
  },
  storyGridItem: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    overflow: "hidden",
    background: COLORS.LIGHT_GRAY,
    cursor: "pointer",
  },
  storyGridImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  storyModalTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 26,
    color: COLORS.PRIMARY_BLUE,
    marginBottom: 8,
  },
  storyModalParagraph: {
    fontFamily: FONTS.INTER,
    fontSize: 14,
    color: COLORS.DARK,
    lineHeight: 1.7,
    marginBottom: 12,
  },
  storyModalAuthor: {
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    color: COLORS.SECONDARY_BLUE,
    marginTop: 8,
    textDecoration: "underline",
  },
  lightboxOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  lightboxContent: {
    position: "relative",
    maxWidth: "90vw",
    // maxHeight: "92vh",
    overflow: "auto",
  },
  lightboxImage: {
    width: "100%",
    height: "100%",
    maxHeight: "90vh",
    objectFit: "contain",
  },
  lightboxClose: {
    position: "absolute",
    top: 2,
    right: 4,
    width: 32,
    height: 32,
    borderRadius: "50%",
    color: COLORS.DARK,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 36,
    fontWeight: 700,
    cursor: "pointer",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 16,
  },
  paginationBar: {
    marginTop: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageArrow: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageButton: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageButtonActive: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },
  // Aliases to match Testimonials "Read More" pagination API
  testimonialPaginationWrapper: {
    marginTop: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  testimonialPagination: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  testimonialBackButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialNextButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialPageButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialActivePageButton: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },
}));

export default useNewsEventsStyles;
