import { makeStyles } from "tss-react/mui";
import type { Theme } from "@mui/material";
import { COLORS, FONTS, SHADOWS } from "../Shared/styles";

const useNewsEventsStyles = makeStyles()((theme: Theme) => ({
  newsEventsLayoutRoot: {
    width: "100%",
    minHeight: "100vh",
    background: COLORS.BLUE_GRAY,
  },
  newsEventsMainRow: {
    display: "flex",
    width: "100%",
    marginLeft: 64,
    marginRight: 64,
    marginTop: 48,
    minHeight: "100vh",
    [theme.breakpoints.down("md")]: {
      marginLeft: 0,
      marginRight: 0,
      marginTop: 16,
    },
  },
  newsEventsMainContent: {
    flex: 1,
    padding: theme.spacing(3),
    paddingLeft: theme.spacing(5),
    paddingRight: theme.spacing(15),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(3),
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },

  newsEventsHero: {
    width: "100vw",
    minHeight: "60vh",
    height: "70vh",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    [theme.breakpoints.down("md")]: {
      minHeight: "30vh",
      height: "30vh",
    },
  },
  newsEventsHeroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: 1,
  },
  newsEventsHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: COLORS.BLACK_TRANSLUCENT,
    zIndex: 2,
  },
  newsEventsHeroColorOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "#0A4FA469",
    opacity: 0.45,
    zIndex: 3,
  },
  newsEventsHeroContent: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    marginTop: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      marginTop: theme.spacing(6),
    },
  },
  newsEventsHeroTitle: {
    color: COLORS.WHITE,
    fontWeight: 400,
    fontSize: 48,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    margin: theme.spacing(5, 0, 2, 0),
    textAlign: "center",
    letterSpacing: 1,
    [theme.breakpoints.down("md")]: {
      fontSize: 28,
      margin: theme.spacing(1, 0),
    },
  },
  newsEventsHeroSubtitle: {
    color: COLORS.WHITE,
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    fontSize: 18,
    textAlign: "center",
    maxWidth: 700,
    letterSpacing: 0.5,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      maxWidth: 400,
    },
  },
  newsEventsHeroBreadcrumb: {
    color: COLORS.WHITE,
    fontWeight: 500,
    fontSize: 22,
    marginBottom: theme.spacing(1),
    textAlign: "center",
    letterSpacing: 0.5,
    opacity: 0.9,
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
      marginTop: theme.spacing(2),
    },
  },

  newsEventsSidebarWrapper: {
    width: 240,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    margin: theme.spacing(3),
    marginRight: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  newsEventsSidebar: {
    width: "100%",
    background: `linear-gradient(180deg, ${COLORS.PRIMARY_BLUE} 0%, ${COLORS.PRIMARY_DARK} 100%)`,
    boxShadow: SHADOWS.SIDEBAR,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  newsEventsSidebarNavTitle: {
    fontWeight: 400,
    fontSize: 32,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    textAlign: "left",
    [theme.breakpoints.down("md")]: {
      fontSize: 24,
    },
  },
  newsEventsSidebarNavItem: {
    color: COLORS.WHITE,
    fontWeight: 600,
    fontFamily: FONTS.INTER,
    fontSize: 14,
    padding: theme.spacing(1.5, 2),
    borderRadius: 999,
    transition: "all 0.3s ease",
    textAlign: "left",
    cursor: "pointer",
    "&.active": {
      background: COLORS.WHITE,
      color: COLORS.PRIMARY_BLUE,
      fontWeight: 700,
    },
  },

  // Side image styles
  newsEventsSideImg: {
    position: "absolute",
    top: -50,
    right: 50,
    width: 190,
    height: "auto",
    zIndex: 0,
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },

  // Page styles
  newsEventsPageHeader: {
    marginBottom: theme.spacing(4),
  },
  newsEventsPageBanner: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(3),
    padding: theme.spacing(3),
    background: COLORS.WHITE,
    borderRadius: 12,
    boxShadow: SHADOWS.CARD,
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      textAlign: "center",
    },
  },
  newsEventsPageIcon: {
    width: 80,
    height: 80,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.PRIMARY_BLUE,
    borderRadius: "50%",
    flexShrink: 0,
    [theme.breakpoints.down("md")]: {
      width: 60,
      height: 60,
    },
  },
  newsEventsPageIconImg: {
    width: "60%",
    height: "60%",
    objectFit: "contain",
  },
  newsEventsPageTextContent: {
    flex: 1,
  },
  newsEventsPageTitle: {
    fontSize: 32,
    fontWeight: 700,
    color: COLORS.PRIMARY_DARK,
    marginBottom: theme.spacing(1),
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    [theme.breakpoints.down("md")]: {
      fontSize: 24,
    },
  },
  newsEventsPageSubtitle: {
    fontSize: 16,
    color: COLORS.MEDIUM_GRAY,
    lineHeight: 1.6,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },

  // Success Stories (carousel) styles
  successStoriesRoot: {
    display: "flex",
    flexDirection: "column",
  },
  successStoriesHeading: {
    marginBottom: 4,
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
    },
  },
  successStoriesHeaderBar: {
    width: "100%",
    margin: "0 auto 12px auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "28px",
    marginBottom: "36px",
  },
  successStoriesHeaderTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 26,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
    },
  },
  successStoriesHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  successStoriesCalendarPill: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 8,
    padding: theme.spacing(1),
  },
  successStoriesSelect: {
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    padding: 0,
    "& .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "& .MuiSelect-icon": {
      color: COLORS.WHITE,
    },
    "& .MuiInputBase-input": {
      padding: "4px 8px",
    },
  },
  successStoriesCarousel: {
    position: "relative",
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
    aspectRatio: "16 / 9",
    backgroundColor: "#eee",
  },
  successStoriesBg: {
    position: "absolute",
    inset: 0,
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "background-image 300ms ease",
  },
  successStoriesBgImg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  successStoriesArrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: "50%",
    width: 100,
    height: 100,
    boxShadow: SHADOWS.CARD,
    zIndex: 10,
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    [theme.breakpoints.down("md")]: {
      width: 50,
      height: 50,
    },
  },
  successStoriesArrowLeft: {
    left: -55,
    "& svg": {
      marginLeft: 40,
      fontSize: 32,
      [theme.breakpoints.down("md")]: {
        marginLeft: 20,
        fontSize: 15,
      },
    },
    [theme.breakpoints.down("md")]: {
      left: -25,
    },
  },
  successStoriesArrowRight: {
    right: -55,
    "& svg": {
      marginRight: 40,
      fontSize: 32,
      [theme.breakpoints.down("md")]: {
        marginRight: 20,
        fontSize: 15,
      },
    },
    [theme.breakpoints.down("md")]: {
      right: -25,
    },
  },
  successStoriesOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "15px 20px",
    backgroundColor: "#0B4FA4A6",
    color: COLORS.WHITE,
  },
  successStoriesPlayOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    cursor: "pointer",
    zIndex: 3,
  },
  successStoriesPlayCircle: {
    width: 80,
    height: 80,
    backgroundColor: "#FF0000",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
  },
  videoPlayIcon: {
    color: "white",
    fontSize: 24,
  },
  successStoriesTitle: {
    fontWeight: 400,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 32,
    textTransform: "capitalize",
    letterSpacing: 0.5,
    textAlign: "center",
    [theme.breakpoints.down("md")]: {
      fontSize: 10,
    },
  },

  // twoCardsCarousel styles removed

  // Card list with pagination
  cardsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "0",
  },
  storyCard: {
    background: COLORS.WHITE,
    borderRadius: 8,
    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
    overflow: "visible",
    position: "relative",
    maxHeight: 400,
    marginBottom: "20px",
  },
  storyCardTop: {
    position: "relative",
    width: "100%",
    height: 400,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  storyCardImg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "8px",
    border: "0.5px solid #000",
  },
  storyDateBadge: {
    position: "absolute",
    left: 8,
    top: 8,
    background: "#E0E2E3C2",
    backdropFilter: "blur(10px)",
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 6,
    padding: "8px 10px",
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    fontSize: 12,
    textAlign: "center",
    lineHeight: 1.2,
    minWidth: 42,
  },
  bigText: {
    fontSize: 20,
    fontWeight: 500,
  },
  storyCardContent: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: "-3px",
    padding: 16,
    background: "rgba(255,255,255)",
    borderRadius: "12px 12px 0 0",
    border: "1px solid #57B6FF",
  },
  storyTitle: {
    fontFamily: FONTS.INTER,
    fontWeight: 900,
    color: COLORS.DARK,
    fontSize: 22,
    marginBottom: 4,
  },
  storyExcerpt: {
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    fontSize: 13,
    color: COLORS.DARK,
    lineHeight: 1.5,
    marginBottom: 12,
  },
  storyTime: {
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 11,
    color: COLORS.PRIMARY_BLUE,
    marginBottom: 10,
  },
  storyButton: {
    display: "inline-block",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    border: `1px solid ${COLORS.SECONDARY_BLUE}`,
    borderRadius: 999,
    padding: "6px 30px",
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
  },
  // Detail view (reuses modal look n feel)
  storyModalContent: {
    width: "95%",
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    margin: "0 auto",
  },
  storyModalHero: {
    position: "relative",
    width: "100%",
    height: 360,
    border: "1px solid #3D0A0A",
    borderRadius: 8,
    background: COLORS.LIGHT_GRAY,
    marginBottom: "10px",
  },
  storyCalendarTopRight: {
    position: "absolute",
    top: 16,
    right: 8,
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.WHITE,
    border: "1px solid #0463EE",
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 8,
    padding: theme.spacing(1, 2),
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(0.5, 1),
      "& .MuiTypography-root": {
        fontSize: 12,
      },
    },
  },
  storyModalImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  storyModalBody: {
    padding: theme.spacing(0, 0, 3, 0),
  },
  storyMetaList: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.2),
    marginBottom: theme.spacing(6),
  },
  storyMetaItem: {
    fontFamily: FONTS.INTER,
    fontSize: 14,
    color: COLORS.DARK,
  },
  storyMetaLabel: {
    fontWeight: 700,
    marginRight: 6,
  },
  storyImageGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: theme.spacing(2),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(5),
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
    },
  },
  storyGridItem: {
    width: "100%",
    height: 300,
    overflow: "hidden",
    background: COLORS.LIGHT_GRAY,
    cursor: "pointer",
    [theme.breakpoints.down("md")]: {
      height: 270,
    },
  },
  storyGridImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  storyModalTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 26,
    color: COLORS.PRIMARY_BLUE,
    marginBottom: 8,
  },
  storyModalParagraph: {
    fontFamily: FONTS.INTER,
    fontSize: 14,
    color: COLORS.DARK,
    lineHeight: 1.7,
    marginBottom: 12,
  },
  storyModalAuthor: {
    fontFamily: FONTS.INTER,
    fontWeight: 700,
    color: COLORS.SECONDARY_BLUE,
    marginTop: 8,
    textDecoration: "underline",
  },
  lightboxOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  lightboxContent: {
    position: "relative",
    maxWidth: "90vw",
    // maxHeight: "92vh",
    overflow: "auto",
  },
  lightboxImage: {
    width: "100%",
    height: "100%",
    maxHeight: "90vh",
    objectFit: "contain",
  },
  lightboxClose: {
    position: "absolute",
    top: 2,
    right: 4,
    width: 32,
    height: 32,
    borderRadius: "50%",
    color: COLORS.DARK,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 36,
    fontWeight: 700,
    cursor: "pointer",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 16,
  },
  paginationBar: {
    marginTop: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageArrow: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageButton: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageButtonActive: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },
  // Aliases to match Testimonials "Read More" pagination API
  testimonialPaginationWrapper: {
    marginTop: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  testimonialPagination: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  testimonialBackButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialNextButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialPageButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  testimonialActivePageButton: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },

  // News styles
  newsContainer: {
    maxHeight: "400px",
    overflow: "hidden",
    position: "relative",
    borderRadius: "12px",
    border: "1px solid #57B6FF",
    borderTop: "none",
  },
  scrollableContent: {
    maxHeight: "350px",
    overflowY: "auto",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    backgroundColor: "#DBECF9",
    borderBottom: "1px solid #57B6FF",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    paddingRight: "8px",
  },
  newsCard: {
    background: "transparent",
    marginBottom: theme.spacing(2),
    boxShadow: "none",
    borderRadius: "12px",
    "& .MuiCardContent-root": {
      borderBottom: "0.5px solid black",
    },
    "&:last-child": {
      marginBottom: 1,
    },
  },
  newsTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 600,
    textDecoration: "underline",
    cursor: "pointer",
    "&:hover": {
      color: COLORS.PRIMARY_DARK,
    },
  },
  newsDate: {
    color: COLORS.DARK,
    fontSize: "0.875rem",
    marginBottom: theme.spacing(0.5),
    fontFamily: FONTS.INTER,
    fontWeight: 400,
  },
  newsDescription: {
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: "0.8rem",
    lineHeight: 1.6,
  },
  newsHeader: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    padding: theme.spacing(2),
    borderRadius: "12px 12px 0 0",
  },
  newsHeaderTitle: {
    fontWeight: 400,
    padding: "0 15px",
    fontFamily: FONTS.DM_SERIF_DISPLAY,
  },
  newsDivider: {
    margin: theme.spacing(1, 0),
    opacity: 0.3,
  },

  // Latest Updates horizontal scroll section
  latestUpdatesSection: {
    marginTop: theme.spacing(4),
  },
  latestUpdatesTitle: {
    fontSize: 24,
    fontWeight: 600,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    marginBottom: theme.spacing(2),
  },
  latestUpdatesScrollContainer: {
    display: "flex",
    overflowX: "auto",
    gap: theme.spacing(2),
    padding: theme.spacing(1, 0),
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  latestUpdatesCard: {
    minWidth: 200,
    height: 250,
    overflow: "hidden",
    position: "relative",
    cursor: "pointer",
    transition: "transform 0.3s ease",
  },
  latestUpdatesImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  latestUpdatesOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    background: "linear-gradient(transparent, rgba(0,0,0,0.7))",
    padding: theme.spacing(2),
    color: COLORS.WHITE,
  },
  latestUpdatesCardTitle: {
    fontSize: 14,
    fontWeight: 600,
    marginBottom: theme.spacing(0.5),
    fontFamily: FONTS.INTER,
  },
  latestUpdatesCardDate: {
    fontSize: 12,
    opacity: 0.9,
    fontFamily: FONTS.INTER,
  },

  // Read More News & Updates section
  readMoreNewsSection: {
    marginTop: theme.spacing(6),
  },
  readMoreNewsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing(4),
  },
  readMoreNewsTitle: {
    fontSize: 26,
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    [theme.breakpoints.down("md")]: {
      fontSize: 16,
    },
  },
  readMoreNewsHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  readMoreNewsCalendarPill: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 8,
    padding: theme.spacing(0.5, 1),
    cursor: "pointer",
  },
  readMoreNewsCalendarIcon: {
    width: 16,
    height: 16,
  },
  readMoreNewsSelect: {
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    padding: 0,
    "& .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "& .MuiSelect-icon": {
      color: COLORS.WHITE,
    },
    "& .MuiInputBase-input": {
      padding: "4px 8px",
    },
    "& .MuiSelect-select": {
      padding: "4px 8px",
    },
  },
  newsSelectMenuPaper: {
    maxHeight: 200,
    overflowY: "auto",
  },
  newsSelectMenuList: {
    maxHeight: 200,
    overflowY: "auto",
  },
  readMoreNewsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: theme.spacing(3),
    marginBottom: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
    },
  },
  readMoreVideosGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(1, 1fr)",
    gap: theme.spacing(3),
    marginBottom: theme.spacing(4),
    placeItems: "center",
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
    },
  },
  readMoreNewsPagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(1),
  },
  readMoreNewsPaginationArrow: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    "&:disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  readMoreNewsPaginationButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  readMoreNewsPaginationButtonActive: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },

  // News Detail View styles
  newsDetailView: {
    width: "100%",
    maxWidth: 1200,
    margin: "0 auto",
    background: COLORS.WHITE,
    borderRadius: 12,
  },
  newsDetailHeader: {
    position: "relative",
    width: "100%",
    background: COLORS.LIGHT_GRAY,
  },
  newsDetailCalendarTopRight: {
    position: "absolute",
    top: 16,
    right: 16,
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 8,
    padding: theme.spacing(1, 2),
    zIndex: 99,
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(0.5, 1),
      "& .MuiTypography-root": {
        fontSize: 12,
      },
    },
  },
  newsDetailHero: {
    position: "relative",
    width: "100%",
    height: "100%",
  },
  newsDetailImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: 0,
  },
  newsDetailContent: {
    padding: theme.spacing(2, 0, 4, 0),
    background: COLORS.WHITE,
  },
  newsDetailTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 28,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    lineHeight: 1.3,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
    },
  },
  newsDetailDescription: {
    color: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    lineHeight: 1.6,
    marginBottom: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  newsDetailParagraph: {
    color: COLORS.DARK,
    fontSize: 14,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    lineHeight: 1.7,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  newsDetailAuthor: {
    color: COLORS.SECONDARY_BLUE,
    fontSize: 16,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    marginTop: theme.spacing(3),
    textAlign: "left",
    textDecoration: "underline",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  newsDetailBackButton: {
    display: "inline-block",
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    padding: theme.spacing(1.5, 3),
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    margin: theme.spacing(3),
    transition: "all 0.3s ease",
    "&:hover": {
      background: COLORS.PRIMARY_DARK,
    },
  },

  // Awards styles
  awardsRoot: {
    display: "flex",
    flexDirection: "column",
  },
  awardsHeading: {
    marginBottom: 12,
    fontWeight: 400,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
    },
  },
  awardsHeaderBar: {
    width: "100%",
    margin: "0 auto 12px auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "28px",
    marginBottom: "36px",
  },
  awardsHeaderTitle: {
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 26,
    [theme.breakpoints.down("md")]: {
      fontSize: 14,
    },
  },
  awardsHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  awardsCalendarPill: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    borderRadius: 8,
    padding: theme.spacing(1),
    cursor: "pointer",
  },
  awardsSelect: {
    backgroundColor: "transparent",
    color: COLORS.WHITE,
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 12,
    padding: 0,
    "& .MuiOutlinedInput-notchedOutline": {
      border: 0,
    },
    "& .MuiSelect-icon": {
      color: COLORS.WHITE,
    },
    "& .MuiInputBase-input": {
      padding: "4px 8px",
    },
  },
  awardsCarousel: {
    position: "relative",
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
    aspectRatio: "16 / 9",
    backgroundColor: "#eee",
  },
  awardsBg: {
    position: "absolute",
    inset: 0,
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "background-image 300ms ease",
  },
  awardsArrow: {
    position: "absolute",
    cursor: "pointer",
    top: "50%",
    transform: "translateY(-50%)",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: "50%",
    width: 100,
    height: 100,
    boxShadow: SHADOWS.CARD,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      background: COLORS.PRIMARY_BLUE,
      color: COLORS.WHITE,
    },
    [theme.breakpoints.down("md")]: {
      width: 60,
      height: 60,
    },
  },
  awardsArrowLeft: {
    left: -60,
    "& svg": {
      fontSize: 32,
      marginLeft: "50px",
      [theme.breakpoints.down("md")]: {
        marginRight: "30px",
        fontSize: 24,
      },
    },
    [theme.breakpoints.down("md")]: {
      left: -30,
    },
  },
  awardsArrowRight: {
    right: -60,
    "& svg": {
      fontSize: 32,
      marginRight: "50px",
      [theme.breakpoints.down("md")]: {
        marginRight: "20px",
        fontSize: 24,
      },
    },
    [theme.breakpoints.down("md")]: {
      right: -30,
    },
  },
  awardsOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "15px 20px",
    backgroundColor: "#0B4FA4A6",
    color: COLORS.WHITE,
  },
  awardsTitle: {
    fontWeight: 400,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: 32,
    textTransform: "capitalize",
    letterSpacing: 0.5,
    textAlign: "left",
    marginBottom: "8px",
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },

  // Awards cards grid and pagination
  awardsCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: theme.spacing(3),
    marginBottom: theme.spacing(4),
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "1fr",
    },
  },
  awardsCard: {
    background: COLORS.WHITE,
    borderRadius: "12px 12px 0 0",
    overflow: "hidden",
    border: `1px solid ${COLORS.LIGHT_GRAY}`,
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    marginBottom: "10px",
  },
  awardsCardImage: {
    width: "100%",
    height: 240,
    objectFit: "cover",
  },
  awardsCardContent: {
    padding: theme.spacing(2),
    border: "1px solid #57B6FF",
    marginTop: "-15px",
    zIndex: "10",
    position: "relative",
    background: "white",
    borderRadius: "12px 12px 0 0",
  },
  awardsCardTitle: {
    fontSize: 18,
    fontWeight: 600,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    marginBottom: theme.spacing(1),
    lineHeight: 1.3,
  },
  awardsCardDescription: {
    fontSize: 10,
    color: COLORS.DARK,
    fontFamily: FONTS.INTER,
    fontWeight: 500,
    lineHeight: 1.5,
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(2),
  },
  awardsCardButton: {
    display: "inline-block",
    background: COLORS.WHITE,
    color: COLORS.SECONDARY_BLUE,
    padding: theme.spacing(1, 4),
    borderRadius: 999,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    border: "1px solid #0463EE",
    fontSize: 14,
    cursor: "pointer",
    transition: "background 0.3s ease",
  },
  awardsPagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(1),
    marginTop: theme.spacing(3),
  },
  awardsPaginationArrow: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    "&:disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  awardsPaginationButton: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    border: `1px solid ${COLORS.LGRAY}`,
    background: COLORS.WHITE,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  awardsPaginationButtonActive: {
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
  },

  // Awards Detail View styles
  awardsDetailView: {
    width: "100%",
    maxWidth: 1200,
    margin: "0 auto",
    background: COLORS.WHITE,
    borderRadius: 12,
    overflow: "hidden",
  },
  awardsDetailHeader: {
    position: "relative",
    width: "100%",
    background: COLORS.LIGHT_GRAY,
    overflow: "hidden",
  },
  awardsDetailCalendarTopRight: {
    position: "absolute",
    top: 16,
    right: 16,
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.WHITE,
    border: `1px solid ${COLORS.PRIMARY_BLUE}`,
    color: COLORS.SECONDARY_BLUE,
    borderRadius: 8,
    padding: theme.spacing(1, 2),
    zIndex: 99,
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(0.5),
    },
  },
  awardsDetailImage: {
    width: "100%",
    height: 400,
    objectFit: "cover",
    borderRadius: 0,
  },
  awardsDetailContent: {
    padding: theme.spacing(3, 0),
    background: COLORS.WHITE,
  },
  awardsDetailTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 400,
    fontSize: 32,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    marginBottom: theme.spacing(3),
    lineHeight: 1.3,
    [theme.breakpoints.down("md")]: {
      fontSize: 18,
    },
  },
  awardsDetailDescription: {
    color: COLORS.DARK,
    fontSize: 16,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    lineHeight: 1.7,
    marginBottom: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  awardsDetailParagraph: {
    color: COLORS.DARK,
    fontSize: 14,
    fontFamily: FONTS.INTER,
    fontWeight: 400,
    lineHeight: 1.7,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("md")]: {
      fontSize: 12,
    },
  },
  awardsDetailBackButton: {
    display: "inline-block",
    background: COLORS.PRIMARY_BLUE,
    color: COLORS.WHITE,
    padding: theme.spacing(1.5, 3),
    borderRadius: 8,
    fontFamily: FONTS.INTER,
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    margin: theme.spacing(3),
    transition: "all 0.3s ease",
    "&:hover": {
      background: COLORS.PRIMARY_DARK,
    },
  },

  // Video styles
  videoRow: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  videoRowContent: {
    display: "flex",
    gap: theme.spacing(2),
    width: "100%",
    marginBottom: theme.spacing(2),
    flexWrap: "wrap",
  },
  videoItem: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  videoThumbnailsContainer: {
    display: "flex",
    gap: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
  videoThumbnail: {
    cursor: "pointer",
    flex: 1,
    minWidth: "200px",
  },
  videoThumbnailImage: {
    position: "relative",
    overflow: "hidden",
    aspectRatio: "16/9",
  },
  videoThumbnailImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  videoPlayButton: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
  },
  videoPlayButtonCircle: {
    width: 50,
    height: 50,
    backgroundColor: "#FF0000",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 10px rgba(0,0,0,0.3)",
  },
  videoInfo: {
    padding: "0 8px",
  },
  videoTitle: {
    color: COLORS.PRIMARY_BLUE,
    fontFamily: FONTS.DM_SERIF_DISPLAY,
    fontSize: "26px",
    fontWeight: 400,
    marginBottom: theme.spacing(0.5),
    lineHeight: 1,
  },
  videoDate: {
    color: COLORS.PRIMARY_BLUE,
    fontSize: "16px",
  },
  videoModal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.9)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: theme.spacing(2),
  },
  videoModalContent: {
    position: "relative",
    width: "100%",
    maxWidth: "90vw",
    maxHeight: "90vh",
  },
  videoModalClose: {
    position: "absolute",
    top: -40,
    right: 0,
    color: "white",
    fontSize: "24px",
    zIndex: 1001,
  },
  videoModalIframe: {
    width: "100%",
    height: "100%",
    minHeight: "70vh",
  },

  // Gallery styles
  galleryLoadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  galleryErrorContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
    padding: theme.spacing(3),
  },
  galleryCardClickable: {
    cursor: "pointer",
  },
  galleryCalendarPillClickable: {
    cursor: "pointer",
  },
  gallerySelectMenuPaper: {
    maxHeight: 200,
    overflowY: "auto",
  },
  gallerySelectMenuList: {
    maxHeight: 200,
    overflowY: "auto",
  },

  // OptimizedImage styles
  optimizedImageContainer: {
    position: "relative",
    width: "100%",
    height: "100%",
    backgroundColor: "#f5f5f5",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  optimizedImageLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f5f5f5",
  },
  optimizedImageErrorOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f5f5f5",
    color: "#666",
  },
  optimizedImage: {
    opacity: 0,
    transition: "opacity 0.3s ease",
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  optimizedImageLoaded: {
    opacity: 1,
  },

  // News styles
  newsLoadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  newsErrorContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
    padding: theme.spacing(3),
  },
  newsErrorAlert: {
    maxWidth: 600,
  },
  newsCardContent: {
    padding: theme.spacing(2),
  },
  newsCalendarPillClickable: {
    cursor: "pointer",
  },

  // SuccessStories styles
  successStoriesCalendarPillClickable: {
    cursor: "pointer",
  },
  successStoriesSelectMenuPaper: {
    maxHeight: 200,
    overflowY: "auto",
  },
  successStoriesSelectMenuList: {
    maxHeight: 200,
    overflowY: "auto",
  },
  successStoriesDetailContainer: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
  },

  // Blog styles
  blogCalendarPillClickable: {
    cursor: "pointer",
  },
  blogSelectMenuPaper: {
    maxHeight: 200,
    overflowY: "auto",
  },
  blogSelectMenuList: {
    maxHeight: 200,
    overflowY: "auto",
  },

  // Video styles
  videoPlayIconWhite: {
    color: "white",
    fontSize: 24,
  },

  backButtonContainer: {
    display: "flex",
    justifyContent: "flex-end",
  },
  backButton: {
    background: COLORS.SECONDARY_BLUE,
    color: COLORS.WHITE,
    padding: "8px",
    borderRadius: 999,
    cursor: "pointer",
    margin: theme.spacing(3, 0),
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg": {
      fontSize: 16,
    },
  },
}));

export default useNewsEventsStyles;
